Repository KissKissBankBank/kitten, pull requests merged in 2018-04, with the labels that each got.

#1131 [Browsing] Add `backgroundColor` prop on `CrowdfundingCard` component.
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
  assets/javascripts/kitten/components/cards/article-card.test.js
  assets/javascripts/kitten/components/cards/crowdfunding-card.js
  assets/javascripts/kitten/components/cards/crowdfunding-card.test.js
Labels: Needs review :hand:

#1136 Allow `CrowdfundingCard` to have truncated `cardSubTitle`
  CHANGELOG.md
  app/views/kitten/components/cards/crowdfunding-card.html.erb
  assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card.js
Labels: Needs review :hand:

#1141 Fix deploy by adding removed foreman gem
  .dockerignore
  CodeBuildDockerfile
  Dockerfile
  bin/kitten
Labels: Bug :bug:

#1138 Update `:hover` and `:focus` state on `azote` button.
  CHANGELOG.md
  assets/stylesheets/kitten/helpers/button/_colors.scss
Labels: Needs review :hand:

#1139 Add `horizontalStroke` props to `SimpleCard`
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/cards/simple-card.html.erb
  assets/javascripts/kitten/components/cards/__snapshots__/simple-card.test.js.snap
  assets/javascripts/kitten/components/cards/simple-card.js
  assets/javascripts/kitten/components/cards/simple-card.test.js
Labels: Needs review :hand:

#1144 Fix `CrowdfundingCard` margins
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card.js
Labels: Needs review :hand:

#1146 v20.6.0
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review :hand:

#1150 Add `k-FormInfo__error__link` class and all states.
  CHANGELOG.md
  app/views/kitten/components/form/form-info.html.erb
  assets/stylesheets/kitten/components/form/_form-info.scss
Labels: To release :rocket:

#1149 [Authentication] Add `KarlHorizontalStrokesWithContent` example
  KARL_CHANGELOG.md
  assets/javascripts/kitten/karl/layout/horizontal-stroke.js
Labels: Needs review :hand:

#1152 [Browsing/Search] Fix bad truncated subTitle in `CrowdfundingCard` component
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card.js
Labels: Needs review :hand:

#1153 v20.7.1
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review :hand:

#1122 Add A11Y on `Modal`
  CHANGELOG.md
  KARL_CHANGELOG.md
  assets/javascripts/kitten/components/modals/modal.js
  assets/javascripts/kitten/karl/modals/modal.js
Labels: Needs review :hand:

#1120 1/2 - Horizontal nav with notification
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/navigation/horizontal-nav.html.erb
  assets/javascripts/kitten/components/navigation/horizontal-nav.js
  assets/javascripts/kitten/karl/navigation/horizontal-nav.js
  assets/stylesheets/kitten/components/navigation/_horizontal-nav.scss
  assets/stylesheets/kitten/components/notifications/_badge.scss
  spec/dummy/client/entries/app-kitten.js
Labels: Needs review :hand:

#1143 1/2 - [Browsing] Update `ArrowIcon` on `Pagination` component.
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/__snapshots__/pagination.test.js.snap
  assets/javascripts/kitten/components/navigation/pagination.js
Labels: Needs review :hand:

#1158 [Cleaning] Remove useless js file
  KARL_CHANGELOG.md
  app/assets/javascripts/kitten/karl.js
  app/assets/javascripts/kitten/karl/display-shortcut.js
Labels: Needs review :hand:

#1159 Ignore storybook-static directory
  .gitignore
Labels: Needs review :hand:

#1155 [Browsing] Show `LegoGrid` only when DOM is loaded
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/lego-grid.js
  package.json
  yarn.lock
Labels: Needs review :hand:

#1160 Add storybook template `PR`
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs review :hand:

#1166 [Tools] Add storybook addon viewport
  .storybook/addons.js
  package.json
  yarn.lock
Labels: Enhancement, Needs review :hand:

#1161 [Tools] Add GridDecorator
  .storybook/config.js
  .storybook/decorators/grid.js
Labels: Needs review :hand:

#1167 [Tools] Deploy storybook on gh-pages
  package.json
  yarn.lock
Labels: Needs review :hand:

#1169 [Tools] Remove Storybook iFrame margin
  .storybook/stylesheets/app-kitten.scss
Labels: Needs review :hand:

#1170 Create viewport `SOrLess`
  CHANGELOG.md
  assets/javascripts/kitten/hoc/__snapshots__/media-queries.test.js.snap
  assets/javascripts/kitten/hoc/media-queries.js
Labels: Needs review :hand:

#1164 [ProjectPage] Update IconBadge component
  CHANGELOG.md
  assets/javascripts/kitten/karl/notifications/icon-badge.js
  assets/stylesheets/kitten/components/notifications/_icon-badge.scss
Labels: Needs review :hand:

#1174 Fix size on `IconBadge` component
  CHANGELOG.md
  assets/stylesheets/kitten/components/notifications/_icon-badge.scss
Labels: Needs review :hand:

#1175 Add `Italic` props on `Title` component.
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/typography/title.html.erb
  assets/javascripts/kitten/components/typography/paragraph.js
  assets/javascripts/kitten/components/typography/title.js
  assets/javascripts/kitten/components/typography/title.test.js
  assets/stylesheets/kitten/components/typography/_title.scss
Labels: Needs review :hand:

#1173 [ProjectPage] Fix `HorizontalNav` vertical alignment
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/horizontal-nav.js
  assets/javascripts/kitten/components/navigation/horizontal-nav.test.js
  assets/stylesheets/kitten/components/navigation/_horizontal-nav.scss
Labels: Needs review :hand:

#1179 [AgricultureLanding] Fix `name` attribute on `TextInput` textarea version
  CHANGELOG.md
  assets/javascripts/kitten/components/form/text-input.js
  assets/javascripts/kitten/components/form/text-input.test.js
Labels: Needs review :hand:

#1180 v20.8.0
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
  spec/dummy/client/yarn.lock
Labels: Needs review :hand:
