Repository KissKissBankBank/kitten, pull requests merged in 2018-08, with the labels that each got.

#1256 Create `FacebookIconWithBackground` component.
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/social-button-icon-words.js
  assets/javascripts/kitten/components/buttons/social-button-icon-words.test.js
  assets/javascripts/kitten/components/icons/facebook-icon-with-background.js
  assets/stylesheets/kitten/components/buttons/_button.scss
Labels: Needs review :hand:

#1258 [Carousel] Fix click on current page
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/carousel/carousel.html.erb
  assets/javascripts/kitten/components/carousel/carousel-inner.js
  assets/javascripts/kitten/karl/carousel/carousel.js
Labels: Needs review :hand:

#1259 v21.3.1
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review :hand:

#1249 Update `Comment` bottom notes style
  CHANGELOG.md
  assets/javascripts/kitten/components/form/__snapshots__/comment.test.js.snap
  assets/javascripts/kitten/components/form/comment.js
Labels: Needs review :hand:

#1268 [Modal] Update ReactModal
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/modal.js
  package.json
  yarn.lock
Labels: Needs review :hand:

#1269 v21.4.0
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review :hand:

#1262 Update `ContributionCard` component's design
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/donation-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
  assets/javascripts/kitten/components/cards/contribution-card.js
  assets/javascripts/kitten/components/cards/contribution-card.test.js
  assets/javascripts/kitten/components/cards/donation-card.js
  assets/javascripts/kitten/components/cards/reward-card.test.js
  assets/javascripts/kitten/components/notifications/icon-badge.js
  assets/javascripts/kitten/karl/cards/reward-card.js
  assets/javascripts/kitten/karl/cards/reward-card.stories.js
Labels: Needs review :hand:

#1272 [Cart] Change Alert component `onClose` prop to `onAfterClose`
  CHANGELOG.md
  assets/javascripts/kitten/components/notifications/alert.js
  assets/javascripts/kitten/components/notifications/alert.test.js
Labels: Breaking change :broken_heart:, Needs review :hand:

#1271 [Stability] Remove sassy-maps
  CHANGELOG.md
  assets/stylesheets/_kitten.scss
  assets/stylesheets/kitten/helpers/_utility.scss
  assets/stylesheets/kitten/helpers/utility/_map-get.scss
  bin/cleanup
  package.json
  spec/dummy/client/yarn.lock
  src/index.js
  vendor/assets/stylesheets/kitten/sassy-maps/package-lock.json
  vendor/assets/stylesheets/kitten/sassy-maps/package.json
  vendor/assets/stylesheets/kitten/sassy-maps/yarn.lock
Labels: Breaking change :broken_heart:, To release :rocket:

#1267 [CartRewardCard] Exposed methods
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/cart-reward-card.js
  assets/javascripts/kitten/hoc/media-queries.js
  assets/javascripts/kitten/karl/cards/cart-reward-card.js
Labels: Breaking change :broken_heart:, To release :rocket:

#1247 Add onLabelClick prop action to Checkbox
  CHANGELOG.md
  assets/javascripts/kitten/components/form/checkbox.js
  assets/javascripts/kitten/components/form/checkbox.stories.js
  assets/javascripts/kitten/components/form/checkbox.test.js
  assets/javascripts/kitten/components/navigation/__snapshots__/pagination.test.js.snap
  assets/javascripts/kitten/config/test-setup.js
  package.json
  yarn.lock
Labels: Needs review :hand:

#1276 [Cart] Fix garbage button styles on `CartRewardCard`
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/cart-reward-card.test.js.snap
  assets/javascripts/kitten/components/cards/cart-reward-card.js
  spec/dummy/client/yarn.lock
Labels: Needs review :hand:

#1278 [Fix] Revert package dependencies
  assets/javascripts/kitten/components/navigation/__snapshots__/pagination.test.js.snap
  package.json
  yarn.lock
Labels: Needs review :hand:

#1279 v22.1.1
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review :hand:

#1281 Add star feature for reward card
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button.js
  assets/javascripts/kitten/components/cards/contribution-card.js
  assets/javascripts/kitten/components/icons/star-icon.js
  assets/javascripts/kitten/karl/buttons/star-button.js
  assets/javascripts/kitten/karl/cards/reward-card.stories.js
  assets/stylesheets/kitten/components/buttons/_button.scss
  assets/stylesheets/kitten/helpers/button/_color-base.scss
  assets/stylesheets/kitten/helpers/button/_svg.scss
  package.json
  yarn.lock
Labels: Needs review :hand:

#1282 v22.2.0
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review :hand:

#1283 v23.0.0
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
  spec/dummy/client/yarn.lock
Labels: Needs review :hand:

#1275 Add `weight` props on `LinkList` component
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/links/link-list.html.erb
  assets/javascripts/kitten/components/links/link-list.js
  assets/javascripts/kitten/components/links/link-list.test.js
  assets/javascripts/kitten/karl/links/link-list.js
  assets/stylesheets/kitten/components/links/_link-list.scss
  spec/dummy/client/entries/app-kitten.js
Labels: Needs review :hand:

#1280 [Cart] Manage infos spacing
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/cart-reward-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
  assets/javascripts/kitten/components/cards/cart-reward-card.js
  assets/javascripts/kitten/components/cards/contribution-card.js
  assets/javascripts/kitten/components/form/select-with-state.test.js
  assets/javascripts/kitten/components/form/text-input-with-limit.test.js
  assets/javascripts/kitten/components/images/image-cropper.test.js
  assets/javascripts/kitten/components/modals/modal.test.js
  assets/javascripts/kitten/components/navigation/__snapshots__/pagination.test.js.snap
  assets/javascripts/kitten/components/navigation/pagination.js
  assets/javascripts/kitten/components/navigation/pagination.test.js
  assets/javascripts/kitten/components/notifications/alert.test.js
  assets/javascripts/kitten/karl/cards/cart-reward-card.js
  assets/javascripts/kitten/karl/cards/cart-reward-card.stories.js
  assets/javascripts/kitten/karl/cards/reward-card.js
  assets/javascripts/kitten/karl/cards/reward-card.stories.js
Labels: Needs review :hand:

#1284 Manage `weight` props on each elements of `LinkList` component.
  CHANGELOG.md
  assets/javascripts/kitten/components/links/link-list.js
  assets/javascripts/kitten/components/links/link-list.test.js
  assets/javascripts/kitten/karl/links/link-list.js
  assets/stylesheets/kitten/components/links/_link-list.scss
Labels: Needs review :hand:

#1145 [Stability] Build JS files
  .gitignore
  CHANGELOG.md
  bin/cleanup
  bin/postinstall
  package.json
  src/index.js
Labels: Needs review :hand:

#1285 Add `k-TextInputWithButton__button` padding
  CHANGELOG.md
  assets/stylesheets/kitten/components/form/_text-input-with-button.scss
Labels: Needs review :hand:

#1286 Add `k-LinkList__item--tripleMargin` marginBottom
  CHANGELOG.md
  assets/javascripts/kitten/components/links/link-list.js
  assets/stylesheets/kitten/components/links/_link-list.scss
Labels: Needs review :hand:
