Repository KissKissBankBank/kitten, pull requests merged in 2018-03, with the labels that each got.

#1087 Move Radium StyleRoot out of Hero component
  CHANGELOG.md
  app/views/kitten/components/heroes/hero.html.erb
  assets/javascripts/kitten/components/heroes/hero.js
  assets/javascripts/kitten/components/heroes/hero.test.js
  assets/javascripts/kitten/karl/heroes/hero.js
  spec/dummy/client/entries/app-kitten.js
Labels: Needs review

#1085 Remove colors-tag-button comment
  assets/stylesheets/kitten/helpers/button/_colors-tag-button.scss
Labels: Needs review

#1088 Force version of `method_source` for example app
  Gemfile
  Gemfile.lock
Labels: Needs review

#1062 Pagination component
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/navigation/pagination.html.erb
  assets/javascripts/kitten/components/navigation/__snapshots__/pagination.test.js.snap
  assets/javascripts/kitten/components/navigation/pagination.js
  assets/javascripts/kitten/components/navigation/pagination.test.js
  assets/javascripts/kitten/karl/navigation/pagination.js
  assets/stylesheets/kitten/components/icons/_arrow-icon.scss
  lib/kitten/configuration.rb
  spec/dummy/client/entries/app-kitten.js
  spec/dummy/package.json
Labels: Needs review

#1090 v20.0.0
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review

#1091 Update Radium version
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card.js
  package.json
  spec/dummy/client/yarn.lock
  yarn.lock
Labels: Needs review

#1092 [Browsing] Fix font-size on TagButton component
  CHANGELOG.md
  assets/stylesheets/kitten/components/buttons/_tag-button.scss
Labels: Needs review

#1094 Add event to onClick `Pagination`
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/pagination.js
  assets/javascripts/kitten/components/navigation/pagination.test.js
Labels: To release

#1095 v20.0.1
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review

#1096 [Browsing] Fix title truncate to CrowdfundingCard
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card.js
Labels: Needs review

#1097 v20.0.2
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review

#1078 A11Y and update colors examples.
  KARL_CHANGELOG.md
  app/assets/stylesheets/kitten/karl/_layout.scss
  app/views/kitten/components/buttons/button-with-badge.html.erb
  app/views/kitten/components/buttons/image-button-with-text.html.erb
  app/views/kitten/components/buttons/image-button.html.erb
  app/views/kitten/components/cards/project-card.html.erb
  app/views/kitten/components/cards/simple-card.html.erb
  app/views/kitten/components/press/press-quotes.html.erb
  app/views/kitten/components/teaser/teaser.html.erb
  app/views/kitten/components/testimonies/testimony-list.html.erb
  app/views/kitten/components/testimonies/testimony.html.erb
  assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card.js
  assets/javascripts/kitten/components/cards/simple-card.js
  assets/javascripts/kitten/components/heroes/hero.js
  assets/javascripts/kitten/components/icons/arrow-icon.js
  assets/javascripts/kitten/components/icons/cb-icon.js
  assets/javascripts/kitten/components/icons/checked-circle-icon.js
  assets/javascripts/kitten/components/icons/checked-icon.js
  assets/javascripts/kitten/components/icons/clock-circle-icon.js
  assets/javascripts/kitten/components/icons/clock-icon.js
  assets/javascripts/kitten/components/icons/cross-circle-icon.js
  assets/javascripts/kitten/components/icons/cross-icon.js
  assets/javascripts/kitten/components/icons/grabber-icon.js
  assets/javascripts/kitten/components/icons/heart-icon.js
  assets/javascripts/kitten/components/icons/instrument-tag-icon.js
  assets/javascripts/kitten/components/icons/location-icon.js
  assets/javascripts/kitten/components/icons/lock-icon.js
  assets/javascripts/kitten/components/icons/mastercard-icon.js
  assets/javascripts/kitten/components/icons/menu-icon.js
  assets/javascripts/kitten/components/icons/question-mark-icon.js
  assets/javascripts/kitten/components/icons/search-icon.js
  assets/javascripts/kitten/components/icons/typology-tag-icon.js
  assets/javascripts/kitten/components/icons/visa-icon.js
  assets/javascripts/kitten/components/icons/warning-circle-icon.js
  assets/javascripts/kitten/components/illustrations/link-box-illustration.js
  assets/javascripts/kitten/components/illustrations/loudspeaker-illustration.js
  assets/javascripts/kitten/components/illustrations/mix-illustration.js
  assets/javascripts/kitten/components/illustrations/phone-illustration.js
  assets/javascripts/kitten/components/images/image-with-caption.js
  assets/javascripts/kitten/components/navigation/__snapshots__/pagination.test.js.snap
  assets/javascripts/kitten/karl/cards/similar-projects-card.js
  assets/javascripts/kitten/karl/examples/title.js
  assets/javascripts/kitten/karl/headers/header.js
  assets/javascripts/kitten/karl/heroes/hero.js
  assets/javascripts/kitten/karl/organisms/dropdown.js
  assets/stylesheets/kitten/_default-config.scss
  assets/stylesheets/kitten/components/buttons/_button-image.scss
  assets/stylesheets/kitten/components/buttons/_button-with-badge.scss
  spec/dummy/client/stylesheets/app-dummy.scss
Labels: Needs review

#1098 [Kitten] Update button colors
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/loaders/loader.html.erb
  assets/javascripts/kitten/karl/loaders/karl-loaders.js
  assets/stylesheets/kitten/components/loaders/_loader.scss
  assets/stylesheets/kitten/helpers/button/_colors.scss
Labels: Needs review

#1089 Add bin/start command
  Gemfile
  Gemfile.lock
  README.md
  bin/start
Labels: Needs review

#1080 [Browsing] Filter icon animation
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/icons/filter-icon.html.erb
  assets/javascripts/kitten/components/icons/__snapshots__/filter-icon.test.js.snap
  assets/javascripts/kitten/components/icons/filter-icon.js
  assets/javascripts/kitten/components/icons/filter-icon.test.js
  assets/javascripts/kitten/karl/buttons/button-filter.js
  lib/kitten/configuration.rb
  spec/dummy/client/entries/app-kitten.js
Labels: Needs review

#1106 Config circle CI
  .circleci/config.yml
Labels: Needs review

#1107 Update primary colors
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/branding/colors.html.erb
  assets/javascripts/kitten/components/cards/project-card.js
  assets/javascripts/kitten/components/navigation/__snapshots__/pagination.test.js.snap
  assets/javascripts/kitten/constants/colors-config.js
  assets/javascripts/kitten/karl/cards/project-card.js
  assets/stylesheets/kitten/_default-config.scss
  assets/stylesheets/kitten/helpers/button/_color-base.scss
  assets/stylesheets/kitten/helpers/button/_colors-tag-button.scss
  assets/stylesheets/kitten/helpers/button/_colors.scss
Labels: Needs review

#1109 Create `Azote` modifier for all buttons
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/buttons/button.html.erb
  app/views/kitten/components/buttons/icon-button-with-words.html.erb
  app/views/kitten/components/buttons/icon-button.html.erb
  app/views/kitten/components/buttons/tag-button.html.erb
  assets/stylesheets/kitten/components/buttons/_button-icon.scss
  assets/stylesheets/kitten/components/buttons/_button.scss
  assets/stylesheets/kitten/helpers/button/_colors.scss
Labels: Needs review

#1110 Update modifier on `KarlButtonIconFilter` example.
  KARL_CHANGELOG.md
  assets/javascripts/kitten/karl/buttons/button-filter.js
Labels: Needs review

#1108 [Browsing] Add progress percentage in `CrowdfundingCard`
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card.js
Labels: Needs review

#1105 [Browsing] Fix CrowdfundingCard
  CHANGELOG.md
  app/views/kitten/components/cards/crowdfunding-card.html.erb
  assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card.js
Labels: Needs review

#1111 Add `ScrollableContainer`
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/grid/scrollable-container.html.erb
  assets/javascripts/kitten/components/grid/__snapshots__/scrollable-container.test.js.snap
  assets/javascripts/kitten/components/grid/scrollable-container.js
  assets/javascripts/kitten/components/grid/scrollable-container.test.js
  assets/javascripts/kitten/karl/grid/scrollable-container.js
  spec/dummy/client/entries/app-kitten.js
Labels: Needs review

#1103 [Connexion/Inscription] Update `Checkbox` component
  CHANGELOG.md
  app/views/kitten/components/form/checkbox.html.erb
  app/views/kitten/components/form/form-actions.html.erb
  app/views/kitten/components/form/form-amount-and-currency.html.erb
  app/views/kitten/components/form/form-phone-number.html.erb
  app/views/kitten/components/form/label.html.erb
  app/views/kitten/components/form/location-input.html.erb
  app/views/kitten/components/form/radio-button.html.erb
  app/views/kitten/components/form/select.html.erb
  app/views/kitten/components/form/switch.html.erb
  assets/javascripts/kitten/components/form/checkbox.js
  assets/stylesheets/kitten/components/form/_checkbox.scss
Labels: Needs review

#1102 Fix `TagButton` colors.
  CHANGELOG.md
  assets/stylesheets/kitten/helpers/button/_colors-tag-button.scss
Labels: Needs review

#1113 v20.1.0
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review

#1115 [Browsing] Fix Progress value
  CHANGELOG.md
  app/views/kitten/components/meters/progress.html.erb
  assets/javascripts/kitten/components/meters/progress.js
  assets/javascripts/kitten/components/meters/progress.test.js
Labels: Needs review

#1114 [Browsing] Add textProps to Checkbox
  CHANGELOG.md
  assets/javascripts/kitten/components/form/checkbox.js
  assets/javascripts/kitten/components/form/checkbox.test.js
Labels: Needs review

#1116 v20.2.0
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review :hand:

#1121 Update `background-color` on the styleguide.
  KARL_CHANGELOG.md
  app/assets/stylesheets/kitten/karl/_layout.scss
Labels: Needs review :hand:

#1118 Add new oxygene button
  CHANGELOG.md
  KARL_CHANGELOG.md
  app/views/kitten/components/buttons/button.html.erb
  app/views/kitten/components/buttons/icon-button-with-words.html.erb
  app/views/kitten/components/buttons/icon-button.html.erb
  assets/stylesheets/kitten/components/buttons/_button-icon.scss
  assets/stylesheets/kitten/components/buttons/_button.scss
Labels: Needs review :hand:

#1117 [Browsing] Update `CrowdfundingCard` image transition
  CHANGELOG.md
  assets/stylesheets/kitten/components/cards/_card.scss
Labels: Needs review :hand:

#1119 Manage padding on `k-Badge`.
  CHANGELOG.md
  assets/javascripts/kitten/components/notifications/badge.js
  assets/stylesheets/kitten/components/notifications/_badge.scss
Labels: Needs review :hand:

#1112 Add PasswordIcon and PasswordInput components
  CHANGELOG.md
  app/views/kitten/components/form/password-input.html.erb
  assets/javascripts/kitten/components/form/__snapshots__/password-input.test.js.snap
  assets/javascripts/kitten/components/form/password-input.js
  assets/javascripts/kitten/components/form/password-input.test.js
  assets/javascripts/kitten/components/form/text-input.js
  assets/javascripts/kitten/components/icons/password-icon.js
  lib/kitten/configuration.rb
  spec/dummy/client/entries/app-kitten.js
Labels: Needs review :hand:

#1124 Update `loofah` gem
  Gemfile.lock
Labels: Needs review :hand:

#1126 Remove `textProps` props from `inputProps`
  CHANGELOG.md
  assets/javascripts/kitten/components/form/checkbox.js
Labels: Needs review :hand:

#1125 Add `col-sizeScreen-up` props to `LegoGrid` Component
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  app/views/kitten/components/grid/lego-grid.html.erb
  assets/javascripts/kitten/components/grid/lego-grid.js
  assets/javascripts/kitten/components/grid/lego-grid.test.js
  assets/javascripts/kitten/karl/grid/lego-grid.js
  assets/stylesheets/kitten/components/grid/_lego-grid.scss
  spec/dummy/client/entries/app-kitten.js
Labels: Needs review :hand:

#1129 v20.4.0
  CHANGELOG.md
  Gemfile.lock
  KARL_CHANGELOG.md
  lib/kitten/version.rb
  package.json
  public/sassdoc/index.html
Labels: Needs review :hand:
