Repository KissKissBankBank/kitten, pull requests merged in 2019-04, with the labels that each got.

#1600 [BulletList] Fix bullet vertical align
  CHANGELOG.md
  assets/stylesheets/kitten/components/lists/_bullet-list.scss
Labels: To release :rocket:

#1599 [Switch] Add handling of others props
  CHANGELOG.md
  assets/javascripts/kitten/components/form/switch.js
  assets/stylesheets/kitten/components/form/_switch.scss
  src/components/form/switch.js
Labels: To release :rocket:

#1601 add built js files for v1.26.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/switch.js
Labels: Needs review :hand:

#1584 [Tech] Update peerDependencies
  README.md
  package.json
Labels: Breaking change :broken_heart:, To release :rocket:

#1582 [Tech] Initialize index exportation
  .storybook/webpack.config.js
  CHANGELOG.md
  README.md
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/index.js
  assets/javascripts/kitten/config/paths.js
  assets/javascripts/kitten/config/paths.test.js
  assets/javascripts/kitten/index.js
  assets/javascripts/kitten/index.test.js
  assets/javascripts/kitten/karl/pages/partner/components/text-with-video.js
  src/components/carousel/tab-bar-carousel/index.js
  src/config/paths.js
  src/index.js
Labels: Breaking change :broken_heart:, To release :rocket:

#1603 v2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#1604 [Tech] Remove getScssPaths from index
  .storybook/webpack.config.js
  CHANGELOG.md
  assets/javascripts/kitten/index.js
  src/index.js
Labels: Needs review :hand:

#1605 v2.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#1598 [Grid] `AdaptableGrid` and `AdaptableGridCol` components
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/adaptable-grid/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/adaptable-grid/index.js
  assets/javascripts/kitten/components/grid/adaptable-grid/stories.js
  assets/javascripts/kitten/components/grid/adaptable-grid/test.js
  assets/javascripts/kitten/index.js
Labels: To release :rocket:

#1574 [Grid] Sticky container component
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/sticky-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/sticky-container/index.js
  assets/javascripts/kitten/components/grid/sticky-container/stories.js
  assets/javascripts/kitten/components/grid/sticky-container/test.js
  assets/javascripts/kitten/index.js
  package-lock.json
  package.json
Labels: Breaking change :broken_heart:, To release :rocket:

#1606 Add built js files for 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/grid/adaptable-grid/index.js
  src/components/grid/sticky-container/index.js
  src/index.js
Labels: Needs review :hand:

#1610 [VerticalStepper] Add `VerticalStepper.Link` styles
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/warning-icon/index.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/link.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/stories.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/test.js
Labels: Needs review :hand:

#1579 Update Storybook
  .storybook/preview-head.html
  package-lock.json
  package.json
Labels: Needs review :hand:

#1609 [StickyContainer] Fix buggy settings & behaviours
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/sticky-container/index.js
  assets/javascripts/kitten/components/grid/sticky-container/stories.js
Labels: To release :rocket:

#1608 [List] Use styled-components
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
  assets/javascripts/kitten/components/lists/__snapshots__/list.test.js.snap
  assets/javascripts/kitten/components/lists/list.js
  assets/javascripts/kitten/components/lists/list/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/lists/list/components/button-item.js
  assets/javascripts/kitten/components/lists/list/index.js
  assets/javascripts/kitten/components/lists/list/info.js
  assets/javascripts/kitten/components/lists/list/stories.js
  assets/javascripts/kitten/components/lists/list/test.js
Labels: Needs review :hand:

#1612 Add `Details` component
  CHANGELOG.md
  assets/javascripts/kitten/components/details/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/details/index.js
  assets/javascripts/kitten/components/details/info.js
  assets/javascripts/kitten/components/details/stories.js
  assets/javascripts/kitten/components/details/test.js
  assets/javascripts/kitten/index.js
  package-lock.json
  package.json
  src/components/details/index.js
  src/components/details/info.js
  src/index.js
Labels: Needs review :hand:

#1602 [Video] Add player button on Video component
  CHANGELOG.md
  assets/javascripts/kitten/components/videos/video/index.js
  assets/javascripts/kitten/components/videos/video/stories.js
Labels: Needs review :hand:

#1613 Feature Add badge with icon
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button/stories.js
  assets/javascripts/kitten/components/icons/cart.js
  assets/javascripts/kitten/components/notifications/__snapshots__/badge.test.js.snap
  assets/javascripts/kitten/components/notifications/badge.js
  assets/javascripts/kitten/components/notifications/badge.test.js
Labels: Needs review :hand:

#1615 Minor badge updates
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button/stories.js
  assets/javascripts/kitten/components/icons/cart.js
  assets/javascripts/kitten/components/notifications/badge.test.js
Labels: Needs review :hand:

#1614 Add `Radius` props on Button component
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/button.js
  assets/javascripts/kitten/components/buttons/button/stories.js
  assets/javascripts/kitten/components/buttons/button/test.js
Labels: Needs review :hand:

#1607 [Maker] Add `ArrowContainer` component
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/arrow-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/arrow-container/index.js
  assets/javascripts/kitten/components/layout/arrow-container/stories.js
  assets/javascripts/kitten/components/layout/arrow-container/test.js
  assets/javascripts/kitten/index.js
  src/components/layout/arrow-container/index.js
  src/index.js
Labels: Needs review :hand:

#1618 v2.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#1621 [ScrollableContainer] Refactor + new props `shadowColor`, `backgroundColor`
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/scrollable-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/scrollable-container/index.js
  assets/javascripts/kitten/components/grid/scrollable-container/stories.js
  assets/javascripts/kitten/components/grid/scrollable-container/styled.js
  assets/javascripts/kitten/components/grid/scrollable-container/test.js
  package-lock.json
  package.json
Labels: Needs review :hand:

#1620 Create `ButtonGroup` component.
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button-group/index.js
  assets/javascripts/kitten/components/buttons/button-group/stories.js
  assets/javascripts/kitten/components/buttons/button-group/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#1622 [StickyContainer] Always run `setSticky` for `isSticky === 'always'`
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/sticky-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/sticky-container/index.js
Labels: Needs review :hand:

#1624 [Fix] Fix unavailable props in ScrollableContainer
  assets/javascripts/kitten/components/grid/scrollable-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/scrollable-container/index.js
  assets/javascripts/kitten/components/grid/scrollable-container/styled.js
Labels: Needs review :hand:

#1627 [Video] Fix `cursor` for `poster` Video attribute.
  CHANGELOG.md
  assets/javascripts/kitten/components/videos/video/index.js
  assets/javascripts/kitten/components/videos/video/stories.js
Labels: Needs review :hand:

#1628 [ScrollableContainer] Rework container shadow display
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/scrollable-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/scrollable-container/index.js
  assets/javascripts/kitten/components/grid/scrollable-container/styled.js
Labels: To release :rocket:

#1629 v2.4.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/grid/scrollable-container/index.js
  src/components/grid/scrollable-container/styled.js
  src/components/videos/video/index.js
Labels: Needs review :hand:
