Repository KissKissBankBank/kitten, pull requests merged in 2019-08, with the labels that each got.

#1733 Release v2.18.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/reward-card.js
  src/components/icons/email-icon/index.js
  src/components/lines/info-lines.js
  src/components/lines/info-lines/index.js
Labels: Needs review :hand:

#1689 Update packages and CircleCI docker config
  .circleci/config.yml
  .storybook/webpack.config.js
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  package-lock.json
  package.json
Labels: Needs review :hand:

#1736 [Fix] Add old ref prop to TextInputWithUnit
  CHANGELOG.md
  assets/javascripts/kitten/components/form/text-input-with-unit/index.js
Labels: Needs review :hand:

#1739 Release/v2.18.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/backer-card.js
  src/components/cards/crowdfunding-card.js
  src/components/cards/triptych.js
  src/components/cards/vertical-card-with-action.js
  src/components/dropdowns/dropdown.js
  src/components/form/text-input-with-unit/index.js
  src/components/media/embed-player.js
  src/components/tours/header-tour.js
  src/hoc/card.js
Labels: Needs review :hand:

#1740 [Accordeon] Refactor `isAnimated={false}` styles
  CHANGELOG.md
  assets/javascripts/kitten/components/accordeon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/accordeon/components/content.js
  assets/javascripts/kitten/components/accordeon/stories.js
Labels: Needs review :hand:

#1743 [InfoLines] Fix warning error about key conflict in `InfoLines` component
  CHANGELOG.md
  assets/javascripts/kitten/components/lines/info-lines/index.js
Labels: Needs review :hand:

#1744 Release/v2.18.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/lines/info-lines/index.js
Labels: Needs review :hand:

#1735 [Kissbankers] Create new `StatusBullet` component
  CHANGELOG.md
  assets/javascripts/kitten/components/status-with-bullet/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/status-with-bullet/index.js
  assets/javascripts/kitten/components/status-with-bullet/stories.js
  assets/javascripts/kitten/components/status-with-bullet/test.js
  assets/javascripts/kitten/index.js
Labels: New component :hatching_chick:, To release :rocket:

#1737 [Kissbankers] Add `shadow`, `borderRadius`, `borderColor`, `borderWidth` props to `ArrowContainer` component
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/arrow-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/arrow-container/index.js
  assets/javascripts/kitten/components/layout/arrow-container/stories.js
  assets/javascripts/kitten/components/layout/arrow-container/test.js
Labels: New component :hatching_chick:, To release :rocket:

#1738 [Kissbankers] `DoubleArrowIcon` component
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/double-arrow-icon.js
  assets/javascripts/kitten/components/icons/icons.stories.js
Labels: New component :hatching_chick:, To release :rocket:

#1742 [ListTable] New `ListTable` component
  CHANGELOG.md
  assets/javascripts/kitten/components/tables/list-table/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/tables/list-table/components/body.js
  assets/javascripts/kitten/components/tables/list-table/components/col.js
  assets/javascripts/kitten/components/tables/list-table/components/context.js
  assets/javascripts/kitten/components/tables/list-table/components/header.js
  assets/javascripts/kitten/components/tables/list-table/components/row.js
  assets/javascripts/kitten/components/tables/list-table/index.js
  assets/javascripts/kitten/components/tables/list-table/stories.js
  assets/javascripts/kitten/components/tables/list-table/test.js
Labels: Needs review :hand:, New component :hatching_chick:, To release :rocket:

#1732 [Kissbankers] Add `StandaloneRangeDatePicker` component
  CHANGELOG.md
  assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/date-picker/standalone-range/components/navbar.js
  assets/javascripts/kitten/components/date-picker/standalone-range/index.js
  assets/javascripts/kitten/components/date-picker/standalone-range/stories.js
  assets/javascripts/kitten/components/date-picker/standalone-range/test.js
Labels: Needs review :hand:, New component :hatching_chick:

#1747 [KissBankers] New KissBankers order modal page
  assets/javascripts/kitten/karl/pages/kissbankers-modal/components/contributor.js
  assets/javascripts/kitten/karl/pages/kissbankers-modal/components/details.js
  assets/javascripts/kitten/karl/pages/kissbankers-modal/components/group.js
  assets/javascripts/kitten/karl/pages/kissbankers-modal/components/header.js
  assets/javascripts/kitten/karl/pages/kissbankers-modal/components/styles.js
  assets/javascripts/kitten/karl/pages/kissbankers-modal/index.js
  assets/javascripts/kitten/karl/pages/kissbankers-modal/stories.js
Labels: New component :hatching_chick:, To release :rocket:

#1749 [ListTable] Default col style to Flex.
  CHANGELOG.md
  assets/javascripts/kitten/components/tables/list-table/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/tables/list-table/components/col.js
  assets/javascripts/kitten/components/tables/list-table/stories.js
Labels: Needs review :hand:

#1750 v2.19.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/tables/list-table/components/col.js
Labels: Needs review :hand:

#1752 [Pagination] Update with styled-components
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/__snapshots__/pagination.test.js.snap
  assets/javascripts/kitten/components/navigation/pagination.js
  assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/pagination/index.js
  assets/javascripts/kitten/components/navigation/pagination/stories.js
  assets/javascripts/kitten/components/navigation/pagination/test.js
Labels: Needs review :hand:

#1753 [AdaptableGrid] Add `tag` prop to custom rendered tag in grid system
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/adaptable-grid/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/adaptable-grid/index.js
  assets/javascripts/kitten/components/grid/adaptable-grid/stories.js
  assets/javascripts/kitten/components/grid/adaptable-grid/test.js
Labels: To release :rocket:

#1754 [Fix] Add props to `ListTable` component.
  CHANGELOG.md
  assets/javascripts/kitten/components/tables/list-table/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/tables/list-table/components/header.js
  assets/javascripts/kitten/components/tables/list-table/components/row.js
  assets/javascripts/kitten/components/tables/list-table/stories.js
  assets/javascripts/kitten/components/tables/list-table/test.js
Labels: To release :rocket:

#1755 [Modal] Add prop to disable body scroll
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/modal/index.js
  assets/javascripts/kitten/components/modals/modal/stories.js
  assets/stylesheets/kitten/components/modals/modal.scss
Labels: To release :rocket:

#1756 [ListTable] Remove styles not in Abstract
  CHANGELOG.md
  assets/javascripts/kitten/components/tables/list-table/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/tables/list-table/components/row.js
Labels: To release :rocket:

#1760 React 16.9
  assets/javascripts/kitten/components/cards/similar-projects-card.js
  assets/javascripts/kitten/components/carousel/carousel-inner.js
  assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
  assets/javascripts/kitten/components/dropdowns/dropdown.js
  assets/javascripts/kitten/helpers/utils/deprecated.js
  package.json
Labels: Needs review :hand:

#1761 [Pagination] - Update `Text` component styles.
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/pagination/index.js
Labels: Needs review :hand:

#1758 [Modal] Remove `PropType`-related warning in tests
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/modal/index.js
Labels: To release :rocket:

#1759 [TagButton] Update with styled-components.
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/tag-button.js
  assets/javascripts/kitten/components/buttons/tag-button.test.js
  assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/tag-button/index.js
  assets/javascripts/kitten/components/buttons/tag-button/stories.js
  assets/javascripts/kitten/components/buttons/tag-button/test.js
Labels: Needs review :hand:

#1764 [AdaptableGrid] Pass className prop to enable styling
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/adaptable-grid/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/adaptable-grid/index.js
  assets/javascripts/kitten/components/grid/adaptable-grid/test.js
Labels: Needs review :hand:

#1765 v2.22.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/grid/adaptable-grid/index.js
Labels: Needs review :hand:

#1767 [AdaptableGrid] Fix `Grid` width
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/adaptable-grid/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/adaptable-grid/index.js
Labels: Needs review :hand:

#1768 [CommentForm] Add `textareaId` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/comments/comment-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment-form/index.js
  assets/javascripts/kitten/components/comments/comment-form/stories.js
  assets/javascripts/kitten/components/comments/comment-form/test.js
  src/components/comments/comment-form/index.js
Labels: Needs review :hand:

#1766 [StandaloneRangeDatePicker] Clean defaultProps
  CHANGELOG.md
  assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/date-picker/standalone-range/components/navbar.js
  assets/javascripts/kitten/components/date-picker/standalone-range/index.js
  assets/javascripts/kitten/components/date-picker/standalone-range/stories.js
Labels: Needs review :hand:

#1769 v2.23.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/date-picker/standalone-range/components/navbar.js
  src/components/date-picker/standalone-range/index.js
  src/components/grid/adaptable-grid/index.js
Labels: Needs review :hand:
