Repository KissKissBankBank/kitten, pull requests merged in 2019-05, with the labels that each got.

#1630 [Fix] `ScrollableContainer` style fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/scrollable-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/scrollable-container/styled.js
Labels: To release :rocket:

#1633 [Details] Fix `open` prop propagation
  CHANGELOG.md
  assets/javascripts/kitten/components/details/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/details/index.js
  assets/javascripts/kitten/components/details/stories.js
  package-lock.json
  src/components/details/index.js
Labels: Needs review :hand:

#1634 v2.4.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#1635 Add link styles when `VerticalStepper.Step` has `onClick` attribute
  CHANGELOG.md
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js
  src/components/steppers/vertical-stepper/components/step.js
Labels: Needs review :hand:

#1636 v2.4.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#1637 [List] Remove a HTML warning on `List.ButtonItem`
  CHANGELOG.md
  assets/javascripts/kitten/components/lists/list/components/button-item.js
Labels: Needs review :hand:

#1638 v2.4.5
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/lists/list/components/button-item.js
Labels: Needs review :hand:

#1639 [Tech] Update packages
  package-lock.json
  package.json
Labels: Needs review :hand:

#1641 v2.5.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/helpers/utils/typography.js
Labels: Needs review :hand:

#1642 [CartRewardCard] Add `descriptionTag` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/cart-reward-card.js
  src/components/cards/cart-reward-card.js
Labels: Needs review :hand:

#1643 v2.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#1611 [Card] Create `RewardEdition` component
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button-group/index.js
  assets/javascripts/kitten/components/cards/__snapshots__/cart-reward-card.test.js.snap
  assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/reward-edition/components/content.js
  assets/javascripts/kitten/components/cards/reward-edition/components/footer.js
  assets/javascripts/kitten/components/cards/reward-edition/components/header.js
  assets/javascripts/kitten/components/cards/reward-edition/index.js
  assets/javascripts/kitten/components/cards/reward-edition/stories.js
  assets/javascripts/kitten/components/cards/reward-edition/test.js
  assets/javascripts/kitten/components/expandable/expand-board.stories.js
  assets/javascripts/kitten/components/icons/garbage-icon.js
  assets/javascripts/kitten/components/icons/garbage-icon/index.js
  assets/javascripts/kitten/karl/buttons/garbage-button.js
Labels: Work in progress :construction:

#1645 [A11y] New `VisuallyHidden` component for Accessibility.
  CHANGELOG.md
  assets/javascripts/kitten/components/accessibility/visually-hidden/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/accessibility/visually-hidden/index.js
  assets/javascripts/kitten/components/accessibility/visually-hidden/stories.js
  assets/javascripts/kitten/components/accessibility/visually-hidden/test.js
Labels: Needs review :hand:

#1644 [Fix] IE11 Button height compatibility fix
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/button.js
  assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
Labels: To release :rocket:

#1646 [Fix] Add export for `VisuallyHidden`
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#1632 Update `ExpandBoard` component.
  assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
  assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/expandable/expand-board/examples.js
  assets/javascripts/kitten/components/expandable/expand-board/index.js
  assets/javascripts/kitten/components/expandable/expand-board/stories.js
  assets/javascripts/kitten/components/expandable/expand-board/test.js
  assets/javascripts/kitten/components/lists/list/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/lists/list/components/button-item.js
  assets/javascripts/kitten/components/lists/list/index.js
Labels: Needs review :hand:

#1648 Update `rewardEdition` stories with new `ExpandBoard`
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/reward-edition/stories.js
Labels: Needs review :hand:
