Repository KissKissBankBank/kitten, pull requests merged in 2019-01, with the labels that each got.

#1480 [Tech] Install packages before run Storybook/Styleguide
  package.json
Labels: Needs review :hand:

#1479 [Tests] Fix some warnings
  assets/javascripts/kitten/components/accordeon/components/item.js
  assets/javascripts/kitten/components/box/__snapshots__/link-box.test.js.snap
  assets/javascripts/kitten/components/box/doc-link-box.test.js
  assets/javascripts/kitten/components/box/link-box.js
  assets/javascripts/kitten/components/box/link-box.test.js
  assets/javascripts/kitten/components/buttons/button-image-with-text.js
  assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/vertical-card-with-action.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/vertical-card.test.js.snap
  assets/javascripts/kitten/components/cards/cart-reward-card.test.js
  assets/javascripts/kitten/components/cards/contribution-card.js
  assets/javascripts/kitten/components/cards/contribution-card.test.js
  assets/javascripts/kitten/components/cards/reward-card.test.js
  assets/javascripts/kitten/components/cards/team-card.test.js
  assets/javascripts/kitten/components/cards/team-card/icons.js
  assets/javascripts/kitten/components/cards/team-card/title.js
  assets/javascripts/kitten/components/cards/vertical-card-with-action.test.js
  assets/javascripts/kitten/components/cards/vertical-card.test.js
  assets/javascripts/kitten/components/form/label.test.js
  package-lock.json
  package.json
Labels: Needs review :hand:

#1482 Fix vulnerability package
  package-lock.json
  package.json
Labels: Needs review :hand:

#1481 No need to add suffix -next for our releases anymore
  bin/publish
Labels: Needs review :hand:

#1484 [Tech] Update component test/stories filename
  .storybook/config.js
  assets/javascripts/kitten/components/accordeon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/accordeon/stories.js
  assets/javascripts/kitten/components/accordeon/test.js
  package.json
Labels: Needs review :hand:

#1474 Add `HeaderMenu` component
  CHANGELOG.md
  assets/javascripts/kitten/components/menus/header-menu/__snapshots__/header-menu.test.js.snap
  assets/javascripts/kitten/components/menus/header-menu/components/context.js
  assets/javascripts/kitten/components/menus/header-menu/components/item.js
  assets/javascripts/kitten/components/menus/header-menu/header-menu.stories.js
  assets/javascripts/kitten/components/menus/header-menu/header-menu.test.js
  assets/javascripts/kitten/components/menus/header-menu/index.js
Labels: Needs review :hand:

#1483 [PlatformMenu] `BurgerIcon` component
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/burger-icon/__snapshots__/burger-icon.test.js.snap
  assets/javascripts/kitten/components/icons/burger-icon/burger-icon.test.js
  assets/javascripts/kitten/components/icons/burger-icon/index.js
  assets/javascripts/kitten/components/icons/burger-icon/stories.js
Labels: Needs review :hand:

#1486 Fix `BurgerIcon` : new `hover` behaviour
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/burger-icon/__snapshots__/burger-icon.test.js.snap
  assets/javascripts/kitten/components/icons/burger-icon/index.js
Labels: Needs review :hand:

#1487 v1.4.1
  CHANGELOG.md
  KARL_CHANGELOG.md
  package.json
  src/components/icons/burger-icon/index.js
Labels: Needs review :hand:

#1488 [Tech] Update README.md
  README.md
Labels: Needs review :hand:

#1491 Remove margin when `title` prop is empty on `CounterBlock` component.
  CHANGELOG.md
  assets/javascripts/kitten/components/meters/counter-block.js
Labels: Needs review :hand:

#1495 Specify type button for button-question-mark-icon
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button-question-mark-icon.js
  assets/javascripts/kitten/components/buttons/button-question-mark-icon.test.js
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  src/components/buttons/button-question-mark-icon.js
Labels: Needs review :hand:

#1489 [Accordeon] Animation
  CHANGELOG.md
  assets/javascripts/kitten/components/accordeon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/accordeon/components/content.js
  assets/javascripts/kitten/components/accordeon/components/context.js
  assets/javascripts/kitten/components/accordeon/components/header.js
  assets/javascripts/kitten/components/accordeon/index.js
  assets/javascripts/kitten/components/accordeon/stories.js
  assets/javascripts/kitten/components/accordeon/test.js
Labels: Needs review :hand:

#1496 v1.5.0
  CHANGELOG.md
  KARL_CHANGELOG.md
  package.json
  src/components/accordeon/components/content.js
  src/components/accordeon/components/context.js
  src/components/accordeon/components/header.js
  src/components/accordeon/index.js
  src/components/meters/counter-block.js
Labels: Needs review :hand:

#1497 [SearchIcon] Update component
  CHANGELOG.md
  assets/javascripts/kitten/components/form/search.js
  assets/javascripts/kitten/components/icons/search-icon.js
  assets/javascripts/kitten/components/icons/search-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/icons/search-icon/index.js
  assets/javascripts/kitten/components/icons/search-icon/stories.js
  assets/javascripts/kitten/components/icons/search-icon/test.js
  package-lock.json
  src/components/form/search.js
  src/components/icons/search-icon.js
  src/components/icons/search-icon/index.js
Labels: Needs review :hand:

#1499 [SearchInput] new component
  CHANGELOG.md
  assets/javascripts/kitten/components/search/search-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/search/search-input/index.js
  assets/javascripts/kitten/components/search/search-input/stories.js
  assets/javascripts/kitten/components/search/search-input/test.js
  src/components/search/search-input/index.js
Labels: Needs review :hand:, New component :hatching_chick:

#1494 [Overlay]
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/overlay/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/modals/overlay/index.js
  assets/javascripts/kitten/components/modals/overlay/stories.js
  assets/javascripts/kitten/components/modals/overlay/test.js
  src/components/modals/overlay/index.js
Labels: Needs review :hand:

#1498 Update size of the bullets on `BulletList`
  CHANGELOG.md
  assets/stylesheets/kitten/components/lists/_bullet-list.scss
Labels: Needs review :hand:

#1500 v1.6.0
  CHANGELOG.md
  KARL_CHANGELOG.md
  package.json
Labels: Needs review :hand:

#1466 [Rebranding] Create pre-deposit pages
  .storybook/preview-head.html
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/triptych.test.js.snap
  assets/javascripts/kitten/components/cards/triptych.js
  assets/javascripts/kitten/components/carousel/__snapshots__/simple-carousel.test.js.snap
  assets/javascripts/kitten/components/carousel/simple-carousel.js
  assets/javascripts/kitten/components/carousel/simple-carousel.test.js
  assets/javascripts/kitten/components/lists/bullet-list.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/carousel-section.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/header-with-background.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/key-section.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/partners-section.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/pre-deposit.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/timeline-section.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/tips/simple-carousel.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/tips/tips-section.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/triptych/card-with-button.js
  assets/javascripts/kitten/karl/pages/pre-deposit/components/triptych/solutions-triptych.js
  assets/javascripts/kitten/karl/pages/pre-deposit/pre-deposit.stories.js
Labels: Needs review :hand:

#1501 [Feature] Add autoFill prop to Select
  CHANGELOG.md
  assets/javascripts/kitten/components/form/select-with-state.js
  assets/javascripts/kitten/components/form/select-with-state.test.js
  assets/javascripts/kitten/karl/pages/contribute/payment-choices/components/payment-choices.js
  package-lock.json
Labels: Needs review :hand:

#1509 [Field.Select] Add onChange handler when autofill input change
  CHANGELOG.md
  assets/javascripts/kitten/components/form/select-with-state.js
  package-lock.json
  src/components/form/select-with-state.js
Labels: Needs review :hand:

#1505 [SearchInput] Remove search results cross
  CHANGELOG.md
  assets/javascripts/kitten/components/search/search-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/search/search-input/index.js
Labels: Needs review :hand:

#1504 [NavTabCarousel] Create `NavTabCarousel` component
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/__snapshots__/tab-bar-carousel.test.js.snap
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/components/next.js
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/components/pagination.js
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/components/prev.js
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/index.js
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/stories.js
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/tab-bar-carousel.test.js
Labels: Needs review :hand:

#1511 [SimpleCard] Stories and fix some styles
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/simple-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/simple-card/index.js
  assets/javascripts/kitten/components/cards/simple-card/stories.js
  assets/javascripts/kitten/components/cards/simple-card/test.js
  assets/javascripts/kitten/components/cards/team-card.stories.js
  package-lock.json
Labels: Needs review :hand:

#1512 Add built js files for V1.8.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/simple-card/index.js
  src/components/carousel/tab-bar-carousel/components/next.js
  src/components/carousel/tab-bar-carousel/components/pagination.js
  src/components/carousel/tab-bar-carousel/components/prev.js
  src/components/carousel/tab-bar-carousel/index.js
  src/components/search/search-input/index.js
Labels: Needs review :hand:

#1513 [Tech] Remove KARL_CHANGELOG notifications in README
  README.md
Labels: Needs review :hand:

#1514 [Pre-Depot] Add some props on `SimpleCarousel` and `BulletList`
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/simple-carousel.js
  assets/javascripts/kitten/components/lists/bullet-list.js
Labels: Needs review :hand:

#1503 [Feature] New `HighlightHalo` in the `Tour` group
  CHANGELOG.md
  assets/javascripts/kitten/components/tours/highlight-halo/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/tours/highlight-halo/index.js
  assets/javascripts/kitten/components/tours/highlight-halo/stories.js
  assets/javascripts/kitten/components/tours/highlight-halo/test.js
Labels: To release :rocket:

#1516 [HighlightHalo] add `onHaloAnimationEnd` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/tours/highlight-halo/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/tours/highlight-halo/index.js
  assets/javascripts/kitten/components/tours/highlight-halo/stories.js
Labels: Needs review :hand:

#1507 [Rebranding] Create Thanks page
  assets/javascripts/kitten/components/layout/marger.js
  assets/javascripts/kitten/karl/pages/common/projects-carousel.js
  assets/javascripts/kitten/karl/pages/contribute/thanks/components/thanks-comment.js
  assets/javascripts/kitten/karl/pages/contribute/thanks/components/thanks-header.js
  assets/javascripts/kitten/karl/pages/contribute/thanks/components/thanks-social.js
  assets/javascripts/kitten/karl/pages/contribute/thanks/thanks.js
  assets/javascripts/kitten/karl/pages/contribute/thanks/thanks.stories.js
Labels: Needs review :hand:

#1519 [NavTabCarousel] Fix component tree view + minor style issue
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/__snapshots__/nav-tab-carousel.test.js.snap
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/components/next.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/components/pagination.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/components/prev.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/index.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/nav-tab-carousel.test.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/stories.js
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/index.js
Labels: Needs review :hand:

#1520 Release/v1.10.1
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/tab-bar-carousel/index.js
  package-lock.json
  package.json
  src/components/carousel/nav-tab-carousel/components/next.js
  src/components/carousel/nav-tab-carousel/components/pagination.js
  src/components/carousel/nav-tab-carousel/components/prev.js
  src/components/carousel/nav-tab-carousel/index.js
  src/components/carousel/tab-bar-carousel/index.js
  src/components/layout/marger.js
Labels: Needs review :hand:

#1521 Release 1.11.0
  CHANGELOG.md
  package.json
Labels: Needs review :hand:

#1528 [NavTablCarousel] Fix NavTablCarousel responsive layout for small device
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/__snapshots__/nav-tab-carousel.test.js.snap
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/components/next.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/components/pagination.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/components/prev.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/components/styled-components.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/index.js
  package-lock.json
  src/components/carousel/nav-tab-carousel/components/next.js
  src/components/carousel/nav-tab-carousel/components/pagination.js
  src/components/carousel/nav-tab-carousel/components/prev.js
  src/components/carousel/nav-tab-carousel/components/styled-components.js
  src/components/carousel/nav-tab-carousel/index.js
Labels: Needs review :hand:
