Repository KissKissBankBank/kitten, pull requests merged in 2019-07, with the labels that each got.

#1681 [DonationCard] Update `DonationCard` with styled-components
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/donation-card.js
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/donation-card/index.js
  assets/javascripts/kitten/components/cards/donation-card/stories.js
  assets/javascripts/kitten/components/cards/donation-card/test.js
  assets/javascripts/kitten/karl/cards/donation-card.js
  assets/javascripts/kitten/karl/cards/donation-card.stories.js
Labels: Needs review :hand:

#1680 [Comments] Update Comments with styled-components.
  CHANGELOG.md
  assets/javascripts/kitten/components/comments/comment-avatar/index.js
  assets/javascripts/kitten/components/comments/comment-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment-form/index.js
  assets/javascripts/kitten/components/comments/comment-form/stories.js
  assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment/index.js
  assets/javascripts/kitten/components/comments/comment/stories.js
  assets/javascripts/kitten/components/form/comment-avatar.js
  assets/javascripts/kitten/components/form/comment-form.js
  assets/javascripts/kitten/components/form/comment.js
  assets/javascripts/kitten/components/form/text-input/stories.js
Labels: Needs review :hand:

#1679 Autocomplete
  CHANGELOG.md
  assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/autocomplete/index.js
  assets/javascripts/kitten/components/form/autocomplete/stories.js
  assets/javascripts/kitten/components/form/autocomplete/test.js
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/field/components/autocomplete.js
  assets/javascripts/kitten/components/form/field/field.examples.js
  assets/javascripts/kitten/components/form/field/field.stories.js
  assets/javascripts/kitten/components/form/field/field.test.js
  assets/javascripts/kitten/components/form/field/index.js
Labels: Needs review :hand:

#1683 [Pages] Add `comments` example page
  assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment/index.js
  assets/javascripts/kitten/karl/pages/comments/comments.stories.js
  assets/javascripts/kitten/karl/pages/comments/components/comments.js
Labels: Needs review :hand:

#1682 Add `IconContainer` component
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/layout/icon-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/icon-container/index.js
  assets/javascripts/kitten/components/layout/icon-container/stories.js
  assets/javascripts/kitten/components/layout/icon-container/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#1674 [SimpleCarousel] Use fraction for image ratio
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/simple-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/simple-card/components/image.js
  assets/javascripts/kitten/components/cards/simple-card/stories.js
  assets/javascripts/kitten/components/cards/simple-card/test.js
Labels: To release :rocket:

#1684 Create `TextCopy` Component
  CHANGELOG.md
  assets/javascripts/kitten/components/details/index.js
  assets/javascripts/kitten/components/icons/copy-icon/index.js
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/layout/arrow-container/index.js
  assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/text-copy/index.js
  assets/javascripts/kitten/components/text-copy/stories.js
  assets/javascripts/kitten/components/text-copy/test.js
Labels: Needs review :hand:

#1671 [IconList] A11y, chrome bug and semantic fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/lists/icon-list/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/lists/icon-list/components/icon.js
  assets/javascripts/kitten/components/lists/icon-list/components/item.js
  assets/javascripts/kitten/components/lists/icon-list/index.js
  assets/javascripts/kitten/components/lists/icon-list/test.js
Labels: To release :rocket:

#1686 Add messenger and whatsapp icon
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/icons/messenger-icon.js
  assets/javascripts/kitten/components/icons/whatsapp-icon.js
Labels: Needs review :hand:

#1688 Fix same component name errors
  assets/javascripts/kitten/components/form/comment-avatar.js
  assets/javascripts/kitten/components/form/comment-form.js
  assets/javascripts/kitten/components/form/comment.js
Labels: Needs review :hand:

#1691 Fix error warnings
  assets/javascripts/kitten/components/cards/vertical-card/index.js
  assets/javascripts/kitten/components/form/text-input-and-select.test.js
Labels: Needs review :hand:

#1692 v2.13.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/donation-card.js
  src/components/cards/donation-card/index.js
  src/components/cards/simple-card/components/image.js
  src/components/cards/vertical-card/index.js
  src/components/comments/comment-avatar/index.js
  src/components/comments/comment-form/index.js
  src/components/comments/comment/index.js
  src/components/details/index.js
  src/components/form/autocomplete/index.js
  src/components/form/comment-avatar.js
  src/components/form/comment-form.js
  src/components/form/comment.js
  src/components/form/field/components/autocomplete.js
  src/components/form/field/components/input.js
  src/components/form/field/field.examples.js
  src/components/form/field/index.js
  src/components/form/text-input-with-button/index.js
  src/components/form/text-input-with-limit.js
  src/components/form/text-input-with-limit/index.js
  src/components/form/text-input-with-unit-form.js
  src/components/form/text-input-with-unit-form/index.js
  src/components/form/text-input-with-unit.js
  src/components/form/text-input-with-unit/index.js
  src/components/form/text-input/index.js
  src/components/icons/copy-icon/index.js
  src/components/icons/messenger-icon.js
  src/components/icons/whatsapp-icon.js
  src/components/layout/arrow-container/index.js
  src/components/layout/icon-container/index.js
  src/components/lists/icon-list/components/icon.js
  src/components/lists/icon-list/components/item.js
  src/components/lists/icon-list/index.js
  src/components/text-copy/index.js
  src/index.js
Labels: Needs review :hand:

#1695 v2.13.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/details/index.js
Labels: Needs review :hand:

#1696 [TextInput] Fix Regression `TextInputWithUnit` component
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/index.js
  assets/javascripts/kitten/components/form/text-input-with-unit/test.js
Labels: Needs review :hand:

#1700 [Icon] Create `BubbleIcon`component
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/bubble-icon/index.js
  assets/javascripts/kitten/components/icons/icons.stories.js
Labels: Needs review :hand:

#1699 [Fix] Fix `TextInput` props propagation
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/index.js
  assets/javascripts/kitten/components/form/text-input-with-button/stories.js
  assets/javascripts/kitten/components/form/text-input-with-button/test.js
  assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-limit/index.js
  assets/javascripts/kitten/components/form/text-input-with-limit/stories.js
  assets/javascripts/kitten/components/form/text-input-with-unit-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/index.js
  assets/javascripts/kitten/components/form/text-input-with-unit/stories.js
Labels: Needs review :hand:

#1703 [Comment] Remove HTML warning to `Comment`
  CHANGELOG.md
  assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment/index.js
  assets/javascripts/kitten/components/comments/comment/stories.js
Labels: Needs review :hand:

#1704 v2.14.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/comments/comment/index.js
Labels: Needs review :hand:

#1705 [Field] Provide props to `Error` subcomponent
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/components/error.js
Labels: Needs review :hand:

#1706 v2.15.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/field/components/error.js
Labels: Needs review :hand:

#1685 [Comment] Create `avatarBadge` props on `Comments` and `CommentForm`
  CHANGELOG.md
  assets/javascripts/kitten/components/comments/comment-avatar/index.js
  assets/javascripts/kitten/components/comments/comment-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment-form/index.js
  assets/javascripts/kitten/components/comments/comment-form/stories.js
  assets/javascripts/kitten/components/comments/comment-form/test.js
  assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment/index.js
  assets/javascripts/kitten/components/comments/comment/stories.js
  assets/javascripts/kitten/components/comments/comment/test.js
  assets/javascripts/kitten/components/icons/checked-circle-icon.js
  assets/javascripts/kitten/karl/pages/comments/components/comments.js
Labels: Needs review :hand:

#1697 [Input] Update `PasswordInput` with styled-component
  CHANGELOG.md
  assets/javascripts/kitten/components/form/__snapshots__/password-input.test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/field/components/password.js
  assets/javascripts/kitten/components/form/password-input.js
  assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/password-input/index.js
  assets/javascripts/kitten/components/form/password-input/stories.js
  assets/javascripts/kitten/components/form/password-input/test.js
  assets/javascripts/kitten/components/icons/password-icon.js
Labels: Needs review :hand:

#1698 [Comment] Create `likeButtonProps` props for `Comment`
  CHANGELOG.md
  assets/javascripts/kitten/components/comments/comment-form/stories.js
  assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment/components/like-button.js
  assets/javascripts/kitten/components/comments/comment/index.js
  assets/javascripts/kitten/components/comments/comment/stories.js
  assets/javascripts/kitten/components/comments/comment/test.js
  assets/javascripts/kitten/components/icons/heart-icon.js
  assets/javascripts/kitten/karl/pages/comments/components/comments.js
Labels: Needs review :hand:

#1707 v2.16.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/comments/comment-avatar/index.js
  src/components/comments/comment-form/index.js
  src/components/comments/comment/components/like-button.js
  src/components/comments/comment/index.js
  src/components/form/field/components/password.js
  src/components/form/password-input.js
  src/components/form/password-input/index.js
  src/components/icons/checked-circle-icon.js
  src/components/icons/heart-icon.js
  src/components/icons/password-icon.js
Labels: Needs review :hand:

#1708 [Comments] Add like button event styles only when an event is attached
  CHANGELOG.md
  assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment/components/like-button.js
Labels: Needs review :hand:

#1709 v2.16.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/comments/comment/components/like-button.js
Labels: Needs review :hand:

#1717 fix text-input-with-limit
  assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-limit/index.js
  src/components/form/text-input-with-limit/index.js
Labels: Needs review :hand:

#1720 v2.16.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#1722 [KissbankersPage] Update `EmailIcon` and create `ExportIcon` components
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/team-card.test.js.snap
  assets/javascripts/kitten/components/icons/email-icon.js
  assets/javascripts/kitten/components/icons/email-icon/index.js
  assets/javascripts/kitten/components/icons/export-icon/index.js
  assets/javascripts/kitten/components/icons/icons.stories.js
Labels: Needs review :hand:

#1725 Fix `title` defaultProps on `ExportIcon` component
  assets/javascripts/kitten/components/icons/export-icon/index.js
Labels: Needs review :hand:

#1721 [KissbankersPage] Built files
  assets/javascripts/kitten/karl/pages/kissbankers-page/components/board.js
  assets/javascripts/kitten/karl/pages/kissbankers-page/components/header.js
  assets/javascripts/kitten/karl/pages/kissbankers-page/components/pagination.js
  assets/javascripts/kitten/karl/pages/kissbankers-page/index.js
  assets/javascripts/kitten/karl/pages/kissbankers-page/stories.js
Labels: Needs review :hand:

#1726 Add forceOneLine prop to TextCopy component.
  CHANGELOG.md
  assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/text-copy/index.js
  assets/javascripts/kitten/components/text-copy/stories.js
  assets/javascripts/kitten/components/text-copy/test.js
Labels: Needs review :hand:

#1727 Release v2.17.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/icons/email-icon.js
  src/components/icons/email-icon/index.js
  src/components/icons/export-icon/index.js
  src/components/text-copy/index.js
Labels: Needs review :hand:

#1730 Add old input refs on text-input
  CHANGELOG.md
  assets/javascripts/kitten/components/form/text-input-with-unit/index.js
  assets/javascripts/kitten/components/form/text-input/index.js
  src/components/form/text-input-with-unit/index.js
  src/components/form/text-input/index.js
Labels: Bug :bug:, Needs review :hand:

#1729 [Fix] Fix warning `EmailIcon`
  assets/javascripts/kitten/components/icons/email-icon/index.js
Labels: Needs review :hand:

#1710 Add `withoutBorder` prop and passing `RewardCard` to `styled-component`
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
  assets/javascripts/kitten/components/cards/reward-card.js
  assets/javascripts/kitten/karl/cards/reward-card.stories.js
Labels: Needs review :hand:

#1731 Clicking on TextCopy input just select the text (no copy)
  CHANGELOG.md
  assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/text-copy/index.js
  src/components/text-copy/index.js
Labels: Needs review :hand:

#1724 [KissbankersPage] Update `InfoLines` component with styled-components.
  CHANGELOG.md
  assets/javascripts/kitten/components/lines/info-lines.js
  assets/javascripts/kitten/components/lines/info-lines.test.js
  assets/javascripts/kitten/components/lines/info-lines/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/lines/info-lines/index.js
  assets/javascripts/kitten/components/lines/info-lines/stories.js
  assets/javascripts/kitten/components/lines/info-lines/test.js
Labels: Needs review :hand:
