Repository KissKissBankBank/kitten, pull requests merged in 2020-04, with the labels that each got.

#1963 [Fix] Fix warning in `SelectWithState` component
  CHANGELOG.md
  assets/javascripts/kitten/components/form/select-with-state.js
  assets/javascripts/kitten/components/form/select-with-state.test.js
  assets/javascripts/kitten/components/form/select-with-state/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select-with-state/index.js
  assets/javascripts/kitten/components/form/select-with-state/stories.js
  assets/javascripts/kitten/components/form/select-with-state/test.js
  assets/javascripts/kitten/helpers/dom/events.js
Labels: To release :rocket:

#1980 add built js files for 2.60.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/select-with-state.js
  src/components/form/select-with-state/index.js
  src/helpers/dom/events.js
Labels: Needs review :hand:

#1973 Add eslint
  .eslintrc.js
  package-lock.json
  package.json
Labels: Needs review :hand:

#1976 [NewHomepage] New NewsBlock page in Karl
  assets/javascripts/kitten/karl/pages/homepage/news/components/news-block.js
  assets/javascripts/kitten/karl/pages/homepage/news/index.js
  assets/javascripts/kitten/karl/pages/homepage/news/stories.js
Labels: Needs review :hand:

#1979 [utils] Add `cssPropertyDistributor` util to distribute CSS properties
  CHANGELOG.md
  assets/javascripts/kitten/helpers/dom/css-property-distributor/index.js
  assets/javascripts/kitten/karl/css-property-distributor/stories.js
Labels: Needs review :hand:

#1981 [ContinuousIntersectionObserver] Add API check to utils
  CHANGELOG.md
  assets/javascripts/kitten/helpers/utils/continuous-intersection-hook.js
  assets/javascripts/kitten/helpers/utils/continuous-intersection-observer.js
Labels: Needs review :hand:

#1983 Bump packages
  package-lock.json
  package.json
Labels: Needs review :hand:

#1975 [Utilities] Init Storybook Doc
  .storybook/addons.js
  .storybook/config.js
  .storybook/main.js
  .storybook/preview.js
  assets/javascripts/kitten/components/buttons/button/stories.mdx
  assets/javascripts/kitten/components/icons/icons.stories.js
  package-lock.json
  package.json
Labels: Needs review :hand:

#1984 [Alert] Fix onAfterClose error
  CHANGELOG.md
  assets/javascripts/kitten/components/notifications/alert.js
Labels: Needs review :hand:

#1987 [StickyContainer] Fix memory leak
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/sticky-container/index.js
Labels: Needs review :hand:

#1968 [Utilities] Add new `k-u-link` utility class for basic link styling
  CHANGELOG.md
  assets/stylesheets/kitten/utilities/link/_link.scss
Labels: Breaking change :broken_heart:, Needs review :hand:

#1994 [Carousel] Fix prev / next buttons
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/carousel.js
Labels: Needs review :hand:

#1993 [HomePage] News block tablet fixes
  assets/javascripts/kitten/karl/pages/homepage/news/components/news-block.js
  assets/javascripts/kitten/karl/pages/homepage/news/index.js
Labels: Needs review :hand:

#1996 v2.63.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/carousel/carousel/carousel.js
  src/components/dropdowns/dropdown-button.js
  src/components/dropdowns/dropdown.js
  src/components/dropdowns/v2/dropdown-button.js
  src/components/dropdowns/v2/dropdown.js
  src/components/navigation/header-nav/components/burger-menu.js
  src/components/navigation/header-nav/components/user-menu.js
Labels: Needs review :hand:

#1998 [Carousel] Fix prev / next buttons on the other carousel I just discovered was the right one
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel.js
Labels: Needs review :hand:

#1999 v2.64.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/carousel/carousel.js
Labels: Needs review :hand:

#2000 Update PR description
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs review :hand:

#1962 [ProgressRing] Create component
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/icons/rocket-circle-icon/index.js
  assets/javascripts/kitten/components/icons/rocket-icon/index.js
  assets/javascripts/kitten/components/meters/progress-ring/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/meters/progress-ring/index.js
  assets/javascripts/kitten/components/meters/progress-ring/stories.js
  assets/javascripts/kitten/components/meters/progress-ring/test.js
Labels: Needs review :hand:

#1985 [GuideLines] Refacto `Title` component
  .storybook/main.js
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button/stories.mdx
  assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/cart-reward-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/triptych.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/vertical-card-with-action.test.js.snap
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/project-similar-card.test.js
  assets/javascripts/kitten/components/cards/vertical-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/__snapshots__/carousel.test.js.snap
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/meters/counter-block/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/pages/markdown/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/title.js
  assets/javascripts/kitten/components/typography/title.test.js
  assets/javascripts/kitten/components/typography/title/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/title/helpers/modifier-styles.js
  assets/javascripts/kitten/components/typography/title/index.js
  assets/javascripts/kitten/components/typography/title/stories.js
  assets/javascripts/kitten/components/typography/title/test.js
Labels: Needs review :hand:

#2001 [Button] Adjust `button` size to follow mobile guidelines
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/button.js
  assets/javascripts/kitten/components/buttons/checkable-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
  assets/stylesheets/kitten/components/buttons/_button-icon.scss
  assets/stylesheets/kitten/components/buttons/_button-image.scss
  assets/stylesheets/kitten/components/buttons/_button.scss
  assets/stylesheets/kitten/components/buttons/_tag-button.scss
Labels: Needs review :hand:

#2002 [ProgressRing] Fix component name error in stories
  assets/javascripts/kitten/components/meters/progress-ring/stories.js
Labels: Needs review :hand:

#1969 [HomePage] À la une & Notre sélection
  assets/javascripts/kitten/karl/pages/homepage/in-the-news/components/card.js
  assets/javascripts/kitten/karl/pages/homepage/in-the-news/index.js
  assets/javascripts/kitten/karl/pages/homepage/in-the-news/stories.js
Labels: Needs review :hand:

#2006 [HomePage] Add `Title`
  assets/javascripts/kitten/karl/pages/homepage/index.js
  assets/javascripts/kitten/karl/pages/homepage/stories.js
Labels: Needs review :hand:

#2010 [Engagement] Create `EngagementCardWithImage` component
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/engagement-card/withImage/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/engagement-card/withImage/index.js
  assets/javascripts/kitten/components/cards/engagement-card/withImage/stories.js
  assets/javascripts/kitten/components/cards/engagement-card/withImage/test.js
Labels: Needs review :hand:

#2012 Create utilities.stories.mdx
  .storybook/main.js
  CHANGELOG.md
  doc/utilities.stories.mdx
Labels: Needs review :hand:

#2003 [Homepage] Last part
  assets/javascripts/kitten/karl/pages/homepage/dialog-with-picture-border/index.js
  assets/javascripts/kitten/karl/pages/homepage/dialog-with-picture-border/stories.js
Labels: To release :rocket:

#2005 [Homepage] Video section
  assets/javascripts/kitten/karl/pages/homepage/video/index.js
  assets/javascripts/kitten/karl/pages/homepage/video/stories.js
Labels: Needs review :hand:

#2015 [Homepage] Consolidate Homepage Story
  assets/javascripts/kitten/karl/pages/homepage/dialog-with-picture-border/index.js
  assets/javascripts/kitten/karl/pages/homepage/dialog-with-picture-border/stories.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/components/card.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/index.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/stories.js
  assets/javascripts/kitten/karl/pages/homepage/in-the-news/index.js
  assets/javascripts/kitten/karl/pages/homepage/in-the-news/stories.js
  assets/javascripts/kitten/karl/pages/homepage/index.js
  assets/javascripts/kitten/karl/pages/homepage/news/components/news-block.js
  assets/javascripts/kitten/karl/pages/homepage/news/index.js
  assets/javascripts/kitten/karl/pages/homepage/news/stories.js
  assets/javascripts/kitten/karl/pages/homepage/video/index.js
  assets/javascripts/kitten/karl/pages/homepage/video/stories.js
Labels: Needs review :hand:

#2009 [HomePage] Create EngagementsCarousel
  assets/javascripts/kitten/components/cards/engagement-card/withImage/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/engagement-card/withImage/index.js
  assets/javascripts/kitten/components/cards/engagement-card/withImage/stories.js
  assets/javascripts/kitten/components/carousel/carousel/stories.js
  assets/javascripts/kitten/karl/pages/homepage/engagements-carousel/components/engagements.js
  assets/javascripts/kitten/karl/pages/homepage/engagements-carousel/index.js
  assets/javascripts/kitten/karl/pages/homepage/engagements-carousel/stories.js
Labels: Needs review :hand:

#2017 [CodeQuality] Add `eslint` pre-commit hook
  package.json
Labels: Needs review :hand:

#2013 [Homepage] Create `TextWithSideImage`
  assets/javascripts/kitten/karl/pages/homepage/index.js
  assets/javascripts/kitten/karl/pages/homepage/text-with-side-image/index.js
  assets/javascripts/kitten/karl/pages/homepage/text-with-side-image/stories.js
Labels: Needs review :hand:

#2016 [Homepage] Popular Project Carousel
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/carousel/carousel.js
  assets/javascripts/kitten/components/carousel/carousel/stories.js
  assets/javascripts/kitten/karl/pages/homepage/carousel/index.js
  assets/javascripts/kitten/karl/pages/homepage/carousel/stories.js
  assets/javascripts/kitten/karl/pages/homepage/index.js
  assets/javascripts/kitten/karl/pages/homepage/text-with-side-image/stories.js
Labels: Needs review :hand:

#2004 [RemoveRadium] Remove from EmbedPlayer
  CHANGELOG.md
  assets/javascripts/kitten/components/media/__snapshots__/embed-player.test.js.snap
  assets/javascripts/kitten/components/media/embed-player.js
  assets/javascripts/kitten/components/media/embed-player.stories.js
  assets/javascripts/kitten/components/videos/embed-player/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/videos/embed-player/index.js
  assets/javascripts/kitten/components/videos/embed-player/stories.js
  assets/javascripts/kitten/components/videos/embed-player/test.js
Labels: Needs review :hand:

#2019 [Icons] Restore icons list
  .storybook/main.js
Labels: Needs review :hand:

#2011 [Video] Modernize component
  CHANGELOG.md
  assets/javascripts/kitten/components/videos/embed-player/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/videos/embed-player/index.js
  assets/javascripts/kitten/components/videos/embed-player/stories.js
  assets/javascripts/kitten/components/videos/embed-player/test.js
  assets/javascripts/kitten/components/videos/video/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/videos/video/index.js
  assets/javascripts/kitten/components/videos/video/stories.js
  assets/javascripts/kitten/components/videos/video/test.js
Labels: Needs review :hand:

#2022 [Carousel] Add `loop` prop on Carousel (redo)
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/carousel/carousel.js
  assets/javascripts/kitten/components/carousel/carousel/stories.js
  assets/javascripts/kitten/components/carousel/carousel/test.js
Labels: Needs review :hand:

#2021 [Carousel] Add `tinyButtons` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/carousel.js
  assets/javascripts/kitten/components/carousel/carousel/stories.js
  assets/javascripts/kitten/components/carousel/carousel/test.js
Labels: Needs review :hand:

#2023 [Homepage] Homepage consolidation and fixes
  assets/javascripts/kitten/karl/pages/homepage/dialog-with-picture-border/index.js
  assets/javascripts/kitten/karl/pages/homepage/index.js
  assets/javascripts/kitten/karl/pages/homepage/news/components/news-block.js
  assets/javascripts/kitten/karl/pages/homepage/popular-projects/index.js
  assets/javascripts/kitten/karl/pages/homepage/popular-projects/stories.js
  assets/javascripts/kitten/karl/pages/homepage/text-with-side-image/index.js
  assets/javascripts/kitten/karl/pages/homepage/video/index.js
  assets/javascripts/kitten/karl/pages/homepage/video/stories.js
Labels: Needs review :hand:

#2024 [Carousel] Add `preferCompletePaginationOnMobile` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/carousel.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/index.js
Labels: Needs review :hand:

#2025 v2.65.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/button/button.js
  src/components/cards/engagement-card/withImage/index.js
  src/components/carousel/carousel/carousel.js
  src/components/icons/rocket-circle-icon/index.js
  src/components/icons/rocket-icon/index.js
  src/components/layout/horizontal-stroke/common/stroke-modifier-styles.js
  src/components/media/embed-player.js
  src/components/meters/progress-ring/index.js
  src/components/typography/common/title-modifier-styles.js
  src/components/typography/title-with-stroke/index.js
  src/components/typography/title.js
  src/components/typography/title/helpers/modifier-styles.js
  src/components/typography/title/index.js
  src/components/videos/embed-player/index.js
  src/components/videos/video/index.js
Labels: Needs review :hand:

#2018 [Homepage] Product returns
  assets/javascripts/kitten/components/icons/rocket-circle-icon/index.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/components/card.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/index.js
Labels: Needs review :hand:

#2026 [Editor] Add editor icons
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/align-center-icon/index.js
  assets/javascripts/kitten/components/icons/align-left-icon/index.js
  assets/javascripts/kitten/components/icons/align-right-icon/index.js
  assets/javascripts/kitten/components/icons/blockquote-icon/index.js
  assets/javascripts/kitten/components/icons/bold-icon/index.js
  assets/javascripts/kitten/components/icons/button-icon/index.js
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/icons/image-icon/index.js
  assets/javascripts/kitten/components/icons/italic-icon/index.js
  assets/javascripts/kitten/components/icons/link-icon/index.js
  assets/javascripts/kitten/components/icons/list-icon/index.js
  assets/javascripts/kitten/components/icons/title-1-icon/index.js
  assets/javascripts/kitten/components/icons/title-2-icon/index.js
  assets/javascripts/kitten/components/icons/title-3-icon/index.js
  assets/javascripts/kitten/components/icons/title-4-icon/index.js
  assets/javascripts/kitten/components/icons/video-icon/index.js
Labels: Needs review :hand:

#2030 [Editor] Add `ParagraphIcon` component
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/icons/paragraph-icon/index.js
Labels: Needs review :hand:

#2029 [Homepage] Returns produit
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
  assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
  assets/javascripts/kitten/components/icons/checked-circle-icon/index.js
  assets/javascripts/kitten/components/icons/checked-icon/index.js
  assets/javascripts/kitten/components/icons/rocket-circle-icon/index.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/components/card.js
Labels: Needs review :hand:

#2027 [CrowdfundingCards] Adapt style and add `stretch` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button-image.js
  assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/button.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/image.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/informations.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/loading.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/progress.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/subtitle.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/index.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/styles.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/test.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/widget/index.js
  assets/javascripts/kitten/karl/pages/homepage/popular-projects/index.js
Labels: Needs review :hand:

#2034 [Carousel] Add BEM-style classes
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/carousel/carousel.js
  assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
  assets/javascripts/kitten/components/carousel/carousel/components/carousel-page.js
  assets/javascripts/kitten/components/carousel/carousel/stories.js
Labels: Needs review :hand:

#2033 [Homepage] Convert top components to BEM
  assets/javascripts/kitten/karl/pages/homepage/engagements-carousel/components/engagements.js
  assets/javascripts/kitten/karl/pages/homepage/engagements-carousel/index.js
  assets/javascripts/kitten/karl/pages/homepage/engagements-carousel/stories.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/components/card.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/index.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/stories.js
  assets/javascripts/kitten/karl/pages/homepage/index.js
  assets/javascripts/kitten/karl/pages/homepage/popular-projects/index.js
Labels: Needs review :hand:

#2035 v2.66.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/button-image.js
  src/components/cards/crowdfunding-card/components/button.js
  src/components/cards/crowdfunding-card/components/image.js
  src/components/cards/crowdfunding-card/components/informations.js
  src/components/cards/crowdfunding-card/components/loading.js
  src/components/cards/crowdfunding-card/components/progress.js
  src/components/cards/crowdfunding-card/components/subtitle.js
  src/components/cards/crowdfunding-card/components/title.js
  src/components/cards/crowdfunding-card/index.js
  src/components/cards/crowdfunding-card/styles.js
  src/components/cards/crowdfunding-card/widget/index.js
  src/components/carousel/carousel/carousel.js
  src/components/carousel/carousel/components/carousel-inner.js
  src/components/carousel/carousel/components/carousel-page.js
  src/components/icons/align-center-icon/index.js
  src/components/icons/align-left-icon/index.js
  src/components/icons/align-right-icon/index.js
  src/components/icons/blockquote-icon/index.js
  src/components/icons/bold-icon/index.js
  src/components/icons/button-icon/index.js
  src/components/icons/checked-circle-icon/index.js
  src/components/icons/checked-icon/index.js
  src/components/icons/image-icon/index.js
  src/components/icons/italic-icon/index.js
  src/components/icons/link-icon/index.js
  src/components/icons/list-icon/index.js
  src/components/icons/paragraph-icon/index.js
  src/components/icons/rocket-circle-icon/index.js
  src/components/icons/title-1-icon/index.js
  src/components/icons/title-2-icon/index.js
  src/components/icons/title-3-icon/index.js
  src/components/icons/title-4-icon/index.js
  src/components/icons/video-icon/index.js
Labels: Needs review :hand:

#2031 [Editor] Add editor toolbar story
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
  assets/javascripts/kitten/components/buttons/checkable-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/karl/editor/components/actions.js
  assets/javascripts/kitten/karl/editor/components/button.js
  assets/javascripts/kitten/karl/editor/components/layout.js
  assets/javascripts/kitten/karl/editor/components/tag-list.js
  assets/javascripts/kitten/karl/editor/components/toolbar.js
  assets/javascripts/kitten/karl/editor/stories.js
Labels: Needs review :hand:

#2036 [HeaderNav] Fix HeaderNav layout
  CHANGELOG.md
  assets/javascripts/kitten/components/menus/header-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/menus/header-menu/components/item.js
  assets/stylesheets/kitten/components/navigation/_header-nav.scss
Labels: Needs review :hand:

#2037 add built js files for 2.66.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/button/helpers/modifier-styles.js
  src/components/menus/header-menu/components/item.js
Labels: Needs review :hand:

#2039 [ProgressRing] Fix ios bug
  CHANGELOG.md
  assets/javascripts/kitten/components/meters/progress-ring/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/meters/progress-ring/index.js
Labels: Needs review :hand:
