Repository KissKissBankBank/kitten, pull requests merged in 2020-11, with the labels that each got.

#2202 [Fix] Dropdown links ref
  CHANGELOG.md
  assets/javascripts/kitten/components/dropdowns/v2/dropdown.js
  src/components/dropdowns/v2/dropdown.js
Labels: Needs review :hand:

#2203 Release/v2.95.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#2206 [Storybook] Use sideEffect option
  .storybook/main.js
Labels: Needs review :hand:

#2188 [RewardCard] new version
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/reward-card/components/info.js
  assets/javascripts/kitten/components/cards/reward-card/components/title.js
  assets/javascripts/kitten/components/cards/reward-card/stories.js
  assets/javascripts/kitten/components/cards/reward-card/styles.js
Labels: Needs review :hand:

#2204 [Form] Add CreditCardForm
  CHANGELOG.md
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/components/cvc.js
  assets/javascripts/kitten/components/form/credit-card-form/components/expiry.js
  assets/javascripts/kitten/components/form/credit-card-form/components/helpers.js
  assets/javascripts/kitten/components/form/credit-card-form/components/number.js
  assets/javascripts/kitten/components/form/credit-card-form/examples.js
  assets/javascripts/kitten/components/form/credit-card-form/index.js
  assets/javascripts/kitten/components/form/credit-card-form/stories.js
  assets/javascripts/kitten/components/form/credit-card-form/test.js
  package-lock.json
  package.json
Labels: Needs review :hand:

#2216 Release v2.97.0
  CHANGELOG.md
  assets/javascripts/kitten/index.js
  bin/release
  package-lock.json
  package.json
  src/components/form/credit-card-form/components/cvc.js
  src/components/form/credit-card-form/components/expiry.js
  src/components/form/credit-card-form/components/helpers.js
  src/components/form/credit-card-form/components/number.js
  src/components/form/credit-card-form/examples.js
  src/components/form/credit-card-form/index.js
  src/esm/components/cards/reward-card/components/info.js
  src/esm/components/cards/reward-card/components/title.js
  src/esm/components/cards/reward-card/styles.js
  src/esm/components/dropdowns/v2/dropdown.js
  src/esm/components/form/credit-card-form/components/cvc.js
  src/esm/components/form/credit-card-form/components/expiry.js
  src/esm/components/form/credit-card-form/components/helpers.js
  src/esm/components/form/credit-card-form/components/number.js
  src/esm/components/form/credit-card-form/examples.js
  src/esm/components/form/credit-card-form/index.js
  src/esm/components/form/pill-number-input/index.js
  src/esm/components/images/image-cropper/index.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#2217 Fix `ImageCropper`
  .storybook/public/steven.jpg
  CHANGELOG.md
  assets/javascripts/kitten/components/images/image-cropper/image-cropper.stories.js
  assets/javascripts/kitten/components/images/image-cropper/index.js
  package-lock.json
  package.json
Labels: Bug :bug:, Needs review :hand:

#2208 [VerticalStepper] Update Stepper
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/dot-icon/index.js
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/link.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/list.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/status.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/title.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/index.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/stories.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/test.js
Labels: Needs review :hand:

#2207 [TextInput] Add `variant` prop and refactor
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/donation-card/index.js
  assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-icon/index.js
  assets/javascripts/kitten/components/form/text-input-with-icon/text-input-with-icon.stories.js
  assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-limit/index.js
  assets/javascripts/kitten/components/form/text-input-with-limit/text-input-with-limit.stories.js
  assets/javascripts/kitten/components/form/text-input-with-unit-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit-form/index.js
  assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/index.js
  assets/javascripts/kitten/components/form/text-input-with-unit/text-input-with-unit.stories.js
  assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input/index.js
  assets/javascripts/kitten/components/form/text-input/text-input.stories.js
Labels: Needs review :hand:, To release :rocket:

#2209 [RadioButton] Add `variant` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/field/components/radio-button-set.js
  assets/javascripts/kitten/components/form/radio-button-set.js
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/index.js
  assets/javascripts/kitten/components/form/radio-button-set/radio-button-set.stories.js
  assets/javascripts/kitten/components/form/radio-button-set/test.js
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
  assets/javascripts/kitten/components/form/radio-button/radio-button.stories.js
  assets/javascripts/kitten/components/form/radio-button/test.js
  assets/javascripts/kitten/components/icons/dot-icon/index.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/link.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/list.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/status.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/title.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/index.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/stories.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/test.js
Labels: Needs review :hand:, To release :rocket:

#2210 [Checkbox] Refactor styles and reinstate CheckboxSet
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/reward-card/components/title.js
  assets/javascripts/kitten/components/cards/reward-card/stories.js
  assets/javascripts/kitten/components/cards/reward-card/styles.js
  assets/javascripts/kitten/components/form/checkbox-set.js
  assets/javascripts/kitten/components/form/checkbox-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/checkbox-set/checkbox-set.stories.js
  assets/javascripts/kitten/components/form/checkbox-set/index.js
  assets/javascripts/kitten/components/form/checkbox-set/test.js
  assets/javascripts/kitten/components/form/checkbox/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/checkbox/checkbox.stories.js
  assets/javascripts/kitten/components/form/checkbox/index.js
  assets/javascripts/kitten/components/form/checkbox/test.js
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:, To release :rocket:

#2211 [Form] New DropdownSelect with Downshift
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/combobox.js
  assets/javascripts/kitten/components/form/dropdown-select/combobox.test.js
  assets/javascripts/kitten/components/form/dropdown-select/dropdown-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-select/index.js
  assets/javascripts/kitten/components/form/dropdown-select/styles.js
  assets/javascripts/kitten/components/form/dropdown-select/test.js
  assets/javascripts/kitten/index.js
  package-lock.json
  package.json
Labels: Needs review :hand:, To release :rocket:

#2212 [Button] Add Variant to Button
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/button.js
  assets/javascripts/kitten/components/buttons/button/button.stories.js
  assets/javascripts/kitten/components/buttons/button/test.js
  assets/javascripts/kitten/components/buttons/checkable-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/social-button-icon-words/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/social-button-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap
Labels: Needs review :hand:, To release :rocket:

#2214 [Accordeon] Add `variant` styles
  CHANGELOG.md
  assets/javascripts/kitten/components/accordeon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/accordeon/components/content.js
  assets/javascripts/kitten/components/accordeon/components/context.js
  assets/javascripts/kitten/components/accordeon/components/header.js
  assets/javascripts/kitten/components/accordeon/components/item.js
  assets/javascripts/kitten/components/accordeon/index.js
  assets/javascripts/kitten/components/accordeon/stories.js
  assets/javascripts/kitten/components/accordeon/test.js
Labels: Needs review :hand:, To release :rocket:

#2215 [Form] Add new `DropdownSelectWithInput`
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/dropdown-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
  assets/javascripts/kitten/components/form/dropdown-select-with-input/test.js
  assets/javascripts/kitten/components/icons/globe-icon/index.js
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:, To release :rocket:

#2218 [DropdownPhoneSelect]
  .eslintrc.js
  .storybook/main.js
  .storybook/stylesheets/kitten/_utilities.scss
  CHANGELOG.md
  assets/images/icons/flags.png
  assets/javascripts/kitten/components/accessibility/visually-hidden/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/accessibility/visually-hidden/index.js
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/simple-carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-phone-select/data/CountryData.js
  assets/javascripts/kitten/components/form/dropdown-phone-select/data/lang/fr.js
  assets/javascripts/kitten/components/form/dropdown-phone-select/data/rawCountries.js
  assets/javascripts/kitten/components/form/dropdown-phone-select/data/rawTerritories.js
  assets/javascripts/kitten/components/form/dropdown-phone-select/dropdown-phone-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-phone-select/index.js
  assets/javascripts/kitten/components/form/dropdown-phone-select/test.js
  assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
  assets/javascripts/kitten/components/form/dropdown-select-with-input/test.js
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/icons/flag-icon/index.js
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/icon-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap
  assets/javascripts/kitten/index.js
  assets/stylesheets/kitten/_utilities.scss
  assets/stylesheets/kitten/utilities/a11y/visually-hidden.scss
  assets/stylesheets/utilities.scss
  styleguide/style/karl/_utilities.scss
Labels: Needs review :hand:

#2222 [Accordeon] Fix height update frequency
  CHANGELOG.md
  assets/javascripts/kitten/components/accordeon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/accordeon/components/content.js
  assets/javascripts/kitten/components/accordeon/components/header.js
  assets/javascripts/kitten/components/accordeon/index.js
  assets/javascripts/kitten/helpers/utils/debounce.js
Labels: Needs review :hand:

#2223 [RadioButton] Fix min height and optional content margin
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
Labels: Needs review :hand:

#2224 [DropdownSelectWithInput] Add `deactivateDropdown` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/dropdown-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
Labels: Needs review :hand:

#2226 [RadioButton] Style fixes.
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
Labels: Needs review :hand:

#2225 [DropdownSelect] Fix Z index
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/styles.js
Labels: Needs review :hand:

#2228 [RadioButton] Fix styles (2)
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
  assets/javascripts/kitten/components/form/radio-button/test.js
Labels: Needs review :hand:

#2229 v2.100.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/radio-button/index.js
  src/esm/components/form/radio-button/index.js
Labels: Needs review :hand:

#2234 Fix dropdown undefined value
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-phone-select/dropdown-phone-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-phone-select/index.js
Labels: Bug :bug:, Needs review :hand:

#2232 [Storybook] Better ordering
  .storybook/karl.js
  .storybook/manager.js
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/public/kitten.jpg
  .storybook/public/logo-kisskissandco.svg
  assets/javascripts/kitten/components/accordeon/stories.js
  assets/javascripts/kitten/components/box/doc-link-box/doc-link-box.stories.mdx
  assets/javascripts/kitten/components/box/link-box/link-box.stories.mdx
  assets/javascripts/kitten/components/buttons/button-group/button-group.stories.mdx
  assets/javascripts/kitten/components/comments/comment-form/comment-form.stories.mdx
  assets/javascripts/kitten/components/comments/comment/comment.stories.mdx
  assets/javascripts/kitten/components/details/details.stories.mdx
  assets/javascripts/kitten/components/form/text-input-with-unit-form/text-input-with-unit-form.stories.mdx
  assets/javascripts/kitten/components/grid/adaptable-grid/adaptable-grid.stories.mdx
  assets/javascripts/kitten/components/lines/info-lines/info-lines.stories.mdx
  assets/javascripts/kitten/components/lists/check-list/check-list.stories.mdx
  assets/javascripts/kitten/components/lists/list/stories.js
  assets/javascripts/kitten/components/loaders/loaders.stories.js
  assets/javascripts/kitten/components/meters/progress/stories.js
  assets/javascripts/kitten/components/modals/next/Modal.stories.js
  assets/javascripts/kitten/components/notifications/alert.stories.js
  assets/javascripts/kitten/components/pages/markdown/stories.js
  assets/javascripts/kitten/components/popovers/simple-popover/stories.js
  assets/javascripts/kitten/components/status-with-bullet/status-with-bullet.stories.mdx
  assets/javascripts/kitten/components/steppers/next/stepper/Stepper.stories.js
  assets/javascripts/kitten/components/tables/double-entry-table/double-entry-table.stories.mdx
  assets/javascripts/kitten/components/text-copy/stories.js
  assets/javascripts/kitten/components/tours/highlight-halo/stories.js
  assets/javascripts/kitten/components/videos/video/video.stories.mdx
  assets/javascripts/kitten/karl/continuous-intersection-observer/stories.js
  assets/javascripts/kitten/karl/css-property-distributor/stories.js
  assets/javascripts/kitten/karl/intersection-observer/stories.js
  assets/javascripts/kitten/karl/lazy/stories.js
  assets/javascripts/kitten/karl/pages/comments/comments.stories.js
  assets/javascripts/kitten/karl/pages/contribute/payment-choices/payment-choices.stories.js
  assets/javascripts/kitten/karl/pages/contribute/shipping-address/shipping-address.stories.js
  assets/javascripts/kitten/karl/pages/contribute/thanks/thanks.stories.js
  assets/javascripts/kitten/karl/pages/email-preferences/stories.js
  assets/javascripts/kitten/karl/pages/kissbankers-modal/stories.js
  assets/javascripts/kitten/karl/pages/login/login.stories.js
  assets/javascripts/kitten/karl/pages/mobile-modal/stories.js
  assets/javascripts/kitten/karl/pages/news-list/news-list.stories.js
  assets/javascripts/kitten/karl/pages/partner/stories.js
  assets/javascripts/kitten/karl/pages/pre-deposit/pre-deposit.stories.js
  assets/javascripts/kitten/karl/widget/stories.js
  doc/introduction/introduction.stories.mdx
  doc/usage/using-kitten.stories.mdx
  doc/usage/using-react.stories.mdx
  doc/usage/using-utilities.stories.mdx
  doc/utilities/align.stories.mdx
  doc/utilities/colors.stories.mdx
  doc/utilities/cursor.stories.mdx
  doc/utilities/link.stories.mdx
  doc/utilities/links.stories.mdx
  package-lock.json
  package.json
Labels: Kitten, Needs review :hand:

#2230 [PillNumberInput] Add disableInput prop
  CHANGELOG.md
  assets/javascripts/kitten/components/form/pill-number-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/pill-number-input/index.js
  assets/javascripts/kitten/components/form/pill-number-input/pill-number-input.stories.js
Labels: Needs review :hand:

#2151 [Utilities] Add CSS and JS margin utilities
  CHANGELOG.md
  assets/javascripts/kitten/helpers/utils/margin/index.js
  assets/javascripts/kitten/helpers/utils/margin/test.js
  assets/stylesheets/kitten/helpers/utility/_px-to-rem.scss
  assets/stylesheets/kitten/utilities/spacing/_margin.scss
  doc/helpers/margin.stories.mdx
  doc/usage/using-kitten.stories.mdx
  doc/usage/using-utilities.stories.mdx
  doc/utilities/margin.stories.mdx
Labels: Needs review :hand:

#2235 v2.101.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/dropdown-phone-select/index.js
  src/components/form/pill-number-input/index.js
  src/esm/components/form/dropdown-phone-select/index.js
  src/esm/components/form/pill-number-input/index.js
  src/esm/helpers/utils/margin/index.js
  src/helpers/utils/margin/index.js
  src/stylesheets/utilities.css
Labels: Needs review :hand:
