Repository KissKissBankBank/kitten, pull requests merged in 2021-01, with the labels that each got.

#2285 [Utility] Add align-self
  CHANGELOG.md
  assets/stylesheets/kitten/_utilities.scss
  assets/stylesheets/kitten/utilities/flex/_align-self.scss
  assets/stylesheets/utilities.scss
  doc/utilities/flex/align-self.stories.mdx
Labels: Needs review :hand:

#2286 [DropdownSelect] Set default color
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/styles.js
Labels: Needs review :hand:

#2288 [DropdownSelect] Add `menuZIndex` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/dropdown-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/combobox.js
  assets/javascripts/kitten/components/form/dropdown-select/dropdown-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-select/index.js
  assets/javascripts/kitten/components/form/dropdown-select/styles.js
Labels: Needs review :hand:

#2287 [HorizontalStroke] Allow `string` prop types on customSize
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/horizontal-stroke/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/horizontal-stroke/index.js
  assets/javascripts/kitten/components/layout/horizontal-stroke/test.js
Labels: Needs review :hand:

#2292 [RewardCard] Set image ratio to 16/10
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/reward-card/components/image.js
  assets/javascripts/kitten/components/cards/reward-card/components/video.js
  assets/javascripts/kitten/components/cards/reward-card/stories.js
  assets/javascripts/kitten/components/cards/reward-card/styles.js
Labels: Needs review :hand:

#2291 [Utilities] Consolidate `blockAlign` and `flex-alignSelf` to `alignSelf`
  CHANGELOG.md
  assets/stylesheets/kitten/_utilities.scss
  assets/stylesheets/kitten/utilities/align-self/_align-self.scss
  assets/stylesheets/kitten/utilities/flex/_align-self.scss
  assets/stylesheets/utilities.scss
  doc/utilities/align-self.stories.mdx
  doc/utilities/block-align.stories.mdx
  doc/utilities/flex/align-self.stories.mdx
Labels: Needs review :hand:

#2289 [RangeSlider] New component based on `input[type="range"]` HTML element
  CHANGELOG.md
  assets/javascripts/kitten/components/form/pill-number-input/index.js
  assets/javascripts/kitten/components/form/range-slider/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/range-slider/index.js
  assets/javascripts/kitten/components/form/range-slider/stories.js
  assets/javascripts/kitten/components/form/range-slider/test.js
  assets/javascripts/kitten/components/form/slider/stories.js
  assets/javascripts/kitten/components/sliders/slider-bar/index.js
  assets/javascripts/kitten/components/sliders/slider-bar/stories.js
  assets/javascripts/kitten/helpers/dom/create-event/index.js
  assets/javascripts/kitten/helpers/dom/native-input-value-setter/index.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#2293 v2.108.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/reward-card/components/image.js
  src/components/cards/reward-card/components/video.js
  src/components/cards/reward-card/styles.js
  src/components/form/dropdown-select-with-input/index.js
  src/components/form/dropdown-select/combobox.js
  src/components/form/dropdown-select/index.js
  src/components/form/dropdown-select/styles.js
  src/components/form/pill-number-input/index.js
  src/components/form/range-slider/index.js
  src/components/layout/horizontal-stroke/index.js
  src/components/sliders/slider-bar/index.js
  src/esm/components/cards/reward-card/components/image.js
  src/esm/components/cards/reward-card/components/video.js
  src/esm/components/cards/reward-card/styles.js
  src/esm/components/form/dropdown-select-with-input/index.js
  src/esm/components/form/dropdown-select/combobox.js
  src/esm/components/form/dropdown-select/index.js
  src/esm/components/form/dropdown-select/styles.js
  src/esm/components/form/pill-number-input/index.js
  src/esm/components/form/range-slider/index.js
  src/esm/components/layout/horizontal-stroke/index.js
  src/esm/components/sliders/slider-bar/index.js
  src/esm/helpers/dom/create-event/index.js
  src/esm/helpers/dom/native-input-value-setter/index.js
  src/esm/index.js
  src/helpers/dom/create-event/index.js
  src/helpers/dom/native-input-value-setter/index.js
  src/index.js
  src/stylesheets/utilities.css
Labels: Needs review :hand:

#2296 [RewardCard] Return `className` prop transmission to `RewardCard`
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/reward-card/index.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/reward-card-container.js
  assets/javascripts/kitten/components/cards/reward-card/test.js
Labels: Needs review :hand:

#2294 Range slider/fix test warning
  assets/javascripts/kitten/components/form/range-slider/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/range-slider/test.js
Labels: Needs review :hand:

#2290 [ImageCropper] Use RangeSlider istead of deprecated Slider
  CHANGELOG.md
  assets/javascripts/kitten/components/form/range-slider/index.js
  assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/images/image-cropper/index.js
Labels: Needs review :hand:

#2297 v2.109.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/reward-card/index.js
  src/components/cards/reward-card/legacy/reward-card-container.js
  src/components/form/range-slider/index.js
  src/components/images/image-cropper/index.js
  src/esm/components/cards/reward-card/index.js
  src/esm/components/cards/reward-card/legacy/reward-card-container.js
  src/esm/components/form/range-slider/index.js
  src/esm/components/images/image-cropper/index.js
Labels: Needs review :hand:

#2298 [ScrollableContainer] Fix overflow style
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/scrollable-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/scrollable-container/stories.js
  assets/javascripts/kitten/components/grid/scrollable-container/styled.js
Labels: Needs review :hand:

#2299 [CrowdfundingCard] Add buttonText prop
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/article-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/button.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/index.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/test.js
Labels: Needs review :hand:

#2300 v2.110.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/crowdfunding-card/components/button.js
  src/components/cards/crowdfunding-card/index.js
  src/components/grid/scrollable-container/styled.js
  src/esm/components/cards/crowdfunding-card/components/button.js
  src/esm/components/cards/crowdfunding-card/index.js
  src/esm/components/grid/scrollable-container/styled.js
Labels: Needs review :hand:

#2302 [Carousel] A11y & Design fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/carousel/index.js
  assets/javascripts/kitten/components/carousel/carousel/styles.js
Labels: Needs review :hand:

#2301 [CrowdfundingCard] Add forceVersion prop
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/article-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/progress.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/state.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/index.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/styles.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/test.js
Labels: Needs review :hand:

#2305 v2.111.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/crowdfunding-card/components/progress.js
  src/components/cards/crowdfunding-card/components/state.js
  src/components/cards/crowdfunding-card/index.js
  src/components/cards/crowdfunding-card/styles.js
  src/components/carousel/carousel/index.js
  src/components/carousel/carousel/styles.js
  src/esm/components/cards/crowdfunding-card/components/progress.js
  src/esm/components/cards/crowdfunding-card/components/state.js
  src/esm/components/cards/crowdfunding-card/index.js
  src/esm/components/cards/crowdfunding-card/styles.js
  src/esm/components/carousel/carousel/index.js
  src/esm/components/carousel/carousel/styles.js
Labels: Needs review :hand:

#2306 [Github] Add Vercel link part to PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs review :hand:

#2307 [RadioButton] Mobile style fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
Labels: To release :rocket:

#2308 [RangeSlider] Mobile style fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/form/range-slider/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/range-slider/index.js
Labels: To release :rocket:

#2309 [DropdownSelect] Mobile style fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/styles.js
Labels: To release :rocket:

#2310 [DropdownSelectWithInput] mobile style fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/dropdown-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
Labels: To release :rocket:

#2311 v2.112.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/dropdown-select-with-input/index.js
  src/components/form/dropdown-select/styles.js
  src/components/form/radio-button/index.js
  src/components/form/range-slider/index.js
  src/esm/components/form/dropdown-select-with-input/index.js
  src/esm/components/form/dropdown-select/styles.js
  src/esm/components/form/radio-button/index.js
  src/esm/components/form/range-slider/index.js
Labels: Needs review :hand:

#2314 [VerticalStepper] No onClick handler when disabled
  CHANGELOG.md
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js
Labels: Bug :bug:, Needs review :hand:

#2317 [VerticalStepper] Update mobile version
  CHANGELOG.md
  assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/status.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/title.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/index.js
Labels: Needs review :hand:

#2238 [A11y] Ajout du focus sur le Carousel et meilleure navigation clavier
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
  assets/javascripts/kitten/components/carousel/carousel/components/carousel-page.js
  assets/javascripts/kitten/components/carousel/carousel/engagements-carousel.stories.js
  assets/javascripts/kitten/components/carousel/carousel/index.js
  assets/javascripts/kitten/components/carousel/carousel/project-carousel.stories.js
  assets/javascripts/kitten/components/carousel/carousel/styles.js
  assets/javascripts/kitten/components/carousel/nav-tab-carousel/nav-tab-carousel.stories.js
  assets/javascripts/kitten/components/carousel/simple-carousel/simple-carousel.stories.js
Labels: A11y 💗, To release :rocket:

#2316 [Combobox] Filter on label instead of value
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-select/combobox.js
  assets/javascripts/kitten/components/form/dropdown-select/dropdown-select.stories.js
Labels: Needs review :hand:

#2324 [VerticalStepper] Littles mobile style fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/link.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/status.js
  assets/javascripts/kitten/components/steppers/vertical-stepper/components/title.js
Labels: Needs review :hand:

#2323 [KittenV3] Remove LegoGrid
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/lego-grid/index.js
  assets/javascripts/kitten/components/grid/lego-grid/stories.js
  assets/javascripts/kitten/components/grid/lego-grid/test.js
  assets/javascripts/kitten/index.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/grid/_lego-grid.scss
  package-lock.json
  package.json
Labels: Kitten V3 🐱, Needs review :hand:

#2312 [KittenV3] Delete deprecated `cards` components
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/article-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/article-card/article-card.stories.js
  assets/javascripts/kitten/components/cards/article-card/index.js
  assets/javascripts/kitten/components/cards/article-card/test.js
  assets/javascripts/kitten/components/cards/contribution-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/contribution-card/index.js
  assets/javascripts/kitten/components/cards/contribution-card/test.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/styles.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/test.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/widget/index.js
  assets/javascripts/kitten/components/cards/project-card/index.js
  assets/javascripts/kitten/components/cards/project-card/test.js
  assets/javascripts/kitten/components/cards/project-creator-card/index.js
  assets/javascripts/kitten/components/cards/project-creator-card/test.js
  assets/javascripts/kitten/components/cards/project-similar-card/index.js
  assets/javascripts/kitten/components/cards/project-similar-card/test.js
  assets/javascripts/kitten/components/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/reward-card/index.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/action.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/button.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/checked-icon.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/content.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/image.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/info.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/infos.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/manage-contribution.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/reward-card-container.js
  assets/javascripts/kitten/components/cards/reward-card/legacy/styles.js
  assets/javascripts/kitten/components/cards/reward-card/stories.js
  assets/javascripts/kitten/components/cards/reward-card/test.js
  assets/javascripts/kitten/components/cards/similar-projects-card/index.js
  assets/javascripts/kitten/components/cards/similar-projects-card/test.js
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/carousel/test.js
  assets/javascripts/kitten/index.js
  assets/javascripts/kitten/karl/widget/components/widget-card.js
  assets/javascripts/kitten/karl/widget/stories.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/cards/_project-card.scss
  assets/stylesheets/kitten/components/cards/_project-creator-card.scss
  assets/stylesheets/kitten/components/cards/_project-similar-card.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2328 [TextInputWithUnit] Add Orion variant
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/index.js
  assets/javascripts/kitten/components/form/text-input-with-unit/test.js
  assets/javascripts/kitten/components/form/text-input-with-unit/text-input-with-unit.stories.js
Labels: Needs review :hand:

#2327 [TextInput] Update variants
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input/index.js
  assets/javascripts/kitten/components/form/text-input/test.js
  assets/javascripts/kitten/components/form/text-input/text-input.stories.js
  assets/javascripts/kitten/components/form/text-input/text-input.stories.mdx
Labels: Needs review :hand:

#2331 [DocumentManager] Restyling
  CHANGELOG.md
  assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/document-manager/index.js
Labels: Needs review :hand:

#2332 [Release] Add built js files for 2.114.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/text-input-with-unit/index.js
  src/components/form/text-input/index.js
  src/components/steppers/vertical-stepper/components/link.js
  src/components/steppers/vertical-stepper/components/status.js
  src/components/steppers/vertical-stepper/components/title.js
  src/components/uploaders/document-manager/index.js
  src/esm/components/form/text-input-with-unit/index.js
  src/esm/components/form/text-input/index.js
  src/esm/components/steppers/vertical-stepper/components/link.js
  src/esm/components/steppers/vertical-stepper/components/status.js
  src/esm/components/steppers/vertical-stepper/components/title.js
  src/esm/components/uploaders/document-manager/index.js
Labels: Needs review :hand:
