Repository KissKissBankBank/kitten, pull requests merged in 2021-05, with the labels that each got.

#2536 [Modal/Next] Fix negative margin for Modal.Block at XL
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/next/Modal.stories.js
  assets/javascripts/kitten/components/modals/next/index.js
Labels: Needs review :hand:

#2535 Add zIndex to header
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/next/index.js
Labels: Needs review :hand:

#2537 v3.8.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/modals/next/index.js
  src/esm/components/modals/next/index.js
Labels: Needs review :hand:

#2538 [ModalNext] Fix condition for `customContentCols` className
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/next/index.js
Labels: To release :rocket:

#2539 [DashboardLayout] Add background color to `DashboardLayout`
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/index.js
Labels: Needs review :hand:

#2541 [BulletList] Fix class errors
  CHANGELOG.md
  assets/javascripts/kitten/components/lists/bullet-list/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/lists/bullet-list/index.js
Labels: Needs review :hand:

#2542 v3.9.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/layout/dashboard-layout/index.js
  src/components/lists/bullet-list/index.js
  src/components/modals/next/index.js
  src/esm/components/layout/dashboard-layout/index.js
  src/esm/components/lists/bullet-list/index.js
  src/esm/components/modals/next/index.js
Labels: Needs review :hand:

#2543 [DropdownSelectWithInput] Fix input padding
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
  assets/javascripts/kitten/components/form/text-input/text-input.stories.mdx
Labels: Needs review :hand:

#2540 [TextInput] Update disabled color
  CHANGELOG.md
  assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input/index.js
Labels: Needs review :hand:

#2519 [Doc] Listing all components.
  assets/javascripts/kitten/components/carousel/simple-carousel/stories.js
  assets/javascripts/kitten/components/links/link-list/link-list.stories.js
  doc/introduction/component-status.stories.mdx
Labels: Needs review :hand:

#2554 [HeaderNav] Add `as` prop to `HeaderNav.Item`
  CHANGELOG.md
  assets/javascripts/kitten/components/menus/header-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/menus/header-menu/components/item.js
  assets/javascripts/kitten/components/menus/header-menu/stories.js
  assets/javascripts/kitten/components/menus/header-menu/styles.js
  assets/javascripts/kitten/components/menus/header-menu/test.js
Labels: Needs review :hand:

#2555 v3.11.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/menus/header-menu/components/item.js
  src/components/menus/header-menu/styles.js
  src/esm/components/menus/header-menu/components/item.js
  src/esm/components/menus/header-menu/styles.js
Labels: Needs review :hand:

#2553 [Color] Add new color
  CHANGELOG.md
  assets/javascripts/kitten/constants/colors-config.js
Labels: Needs review :hand:

#2551 [Button] Add boron modifier
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button/button.stories.js
  assets/javascripts/kitten/components/buttons/button/button.stories.mdx
  assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
  assets/javascripts/kitten/components/buttons/button/index.js
  assets/javascripts/kitten/components/cards/vertical-card-with-action/vertical-card-with-action.stories.js
  assets/javascripts/kitten/components/menus/header-menu/components/item.js
Labels: Needs review :hand:

#2556 [Modal/Next] Add `sticky` and `fullSize` props on Actions
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/next/Modal.stories.js
  assets/javascripts/kitten/components/modals/next/index.js
Labels: Needs review :hand:

#2557 [HeaderNav] Add Border styles
  .storybook/stylesheets/app-kitten.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
  assets/javascripts/kitten/components/navigation/header-nav/index.js
  assets/javascripts/kitten/components/navigation/header-nav/stories.js
  assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank-new.js
  assets/javascripts/kitten/components/navigation/header-nav/styles.js
Labels: Needs product review :watermelon:, Needs review :hand:

#2559 v3.12.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/button/helpers/modifier-styles.js
  src/components/buttons/button/index.js
  src/components/menus/header-menu/components/item.js
  src/components/modals/next/index.js
  src/components/navigation/header-nav/index.js
  src/components/navigation/header-nav/stories/kisskissbankbank-new.js
  src/components/navigation/header-nav/styles.js
  src/constants/colors-config.js
  src/esm/components/buttons/button/helpers/modifier-styles.js
  src/esm/components/buttons/button/index.js
  src/esm/components/menus/header-menu/components/item.js
  src/esm/components/modals/next/index.js
  src/esm/components/navigation/header-nav/index.js
  src/esm/components/navigation/header-nav/stories/kisskissbankbank-new.js
  src/esm/components/navigation/header-nav/styles.js
  src/esm/constants/colors-config.js
Labels: Needs review :hand:

#2558 [LinkBox] Update component
  CHANGELOG.md
  assets/javascripts/kitten/components/box/doc-link-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/box/link-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/box/link-box/index.js
  assets/javascripts/kitten/components/box/link-box/link-box.stories.js
  assets/javascripts/kitten/components/box/link-box/link-box.stories.mdx
  assets/javascripts/kitten/components/box/link-box/styles.js
  assets/javascripts/kitten/components/box/link-box/test.js
Labels: Needs review :hand:

#2560 [Modal/Next] Fix Button style when alone in fullSize Action.
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/next/index.js
Labels: Needs review :hand:

#2561 [Dropdown] Add default value for onBlur
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-select/index.js
Labels: Needs review :hand:

#2552 [VerticalProgress] Add new component
  CHANGELOG.md
  assets/javascripts/kitten/components/steppers/vertical-progress/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-progress/components/status.js
  assets/javascripts/kitten/components/steppers/vertical-progress/components/step.js
  assets/javascripts/kitten/components/steppers/vertical-progress/index.js
  assets/javascripts/kitten/components/steppers/vertical-progress/test.js
  assets/javascripts/kitten/components/steppers/vertical-progress/vertical-progress.stories.js
Labels: Needs review :hand:

#2562 [Release] add built js files for 3.13.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/box/link-box/index.js
  src/components/box/link-box/styles.js
  src/components/form/dropdown-select/index.js
  src/components/modals/next/index.js
  src/components/steppers/vertical-progress/components/status.js
  src/components/steppers/vertical-progress/components/step.js
  src/components/steppers/vertical-progress/index.js
  src/esm/components/box/link-box/index.js
  src/esm/components/box/link-box/styles.js
  src/esm/components/form/dropdown-select/index.js
  src/esm/components/modals/next/index.js
  src/esm/components/steppers/vertical-progress/components/status.js
  src/esm/components/steppers/vertical-progress/components/step.js
  src/esm/components/steppers/vertical-progress/index.js
Labels: Needs review :hand:

#2564 [Doc] VerticalProgress
  assets/javascripts/kitten/components/steppers/vertical-progress/vertical-progress.stories.mdx
  doc/introduction/component-status.stories.mdx
Labels: Needs review :hand:

#2563 [DashboardLayout] Specify size for `DashboardLayout.Flow` content column.
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
Labels: Needs review :hand:

#2565 [VerticalProgress] export
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#2566 [Release] add built js files for 3.13.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/layout/dashboard-layout/flow/index.js
  src/esm/components/layout/dashboard-layout/flow/index.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#2567 [Button] Add neon modifier
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button/button.stories.js
  assets/javascripts/kitten/components/buttons/button/button.stories.mdx
  assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
  assets/javascripts/kitten/components/buttons/button/index.js
  assets/javascripts/kitten/components/cards/vertical-card-with-action/vertical-card-with-action.stories.js
  assets/javascripts/kitten/components/menus/header-menu/components/item.js
Labels: Needs review :hand:

#2568 [VerticalProgress] Fix z-index value
  CHANGELOG.md
  assets/javascripts/kitten/components/steppers/vertical-progress/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-progress/components/status.js
  assets/javascripts/kitten/components/steppers/vertical-progress/index.js
Labels: Needs review :hand:

#2570 [Colors] Add orange2 and orange3 colors
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
  assets/javascripts/kitten/constants/colors-config.js
  doc/design/colors.js
Labels: Needs review :hand:

#2573 [Release] Add built js files for V3.14.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/button/helpers/modifier-styles.js
  src/components/buttons/button/index.js
  src/components/menus/header-menu/components/item.js
  src/components/steppers/vertical-progress/components/status.js
  src/components/steppers/vertical-progress/index.js
  src/constants/colors-config.js
  src/esm/components/buttons/button/helpers/modifier-styles.js
  src/esm/components/buttons/button/index.js
  src/esm/components/menus/header-menu/components/item.js
  src/esm/components/steppers/vertical-progress/components/status.js
  src/esm/components/steppers/vertical-progress/index.js
  src/esm/constants/colors-config.js
Labels: Needs review :hand:

#2574 [CrowdfundingCard] Add `progressLabel` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/progress.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/index.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/test.js
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/carousel/test.js
Labels: Needs review :hand:

#2571 [HeaderNav] Fix accessibility error
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/header-nav/index.js
Labels: Needs review :hand:

#2575 [Separator] Reduce style specificity
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/separator/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/separator/index.js
Labels: Needs review :hand:

#2577 [Doc] Update components status
  doc/introduction/component-status.stories.mdx
Labels: Needs review :hand:

#2576 [DashboardLayout] Add Alert subcomponent
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
  assets/javascripts/kitten/components/layout/dashboard-layout/test.js
Labels: Needs review :hand:

#2580 [Error] Fix console warning
  assets/javascripts/kitten/components/box/link-box/link-box.stories.js
  assets/javascripts/kitten/components/links/link-list/link-list.stories.js
  assets/javascripts/kitten/components/steppers/vertical-progress/vertical-progress.stories.js
Labels: Needs review :hand:

#2578 [Icons] Add news icons
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/icons/lock-outline-icon/index.js
  assets/javascripts/kitten/components/icons/refund-icon/index.js
  assets/javascripts/kitten/components/icons/shield-check-icon/index.js
  assets/javascripts/kitten/index.js
  doc/introduction/component-status.stories.mdx
Labels: Needs review :hand:

#2581 [DropdownSelectWithInput] Add `size` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-phone-select/dropdown-phone-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/dropdown-select.stories.js
  assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
Labels: Needs review :hand:

#2582 [DashboardMenu] Fix list items spacing
  CHANGELOG.md
  assets/javascripts/kitten/components/menus/dashboard-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/menus/dashboard-menu/index.js
Labels: Needs review :hand:

#2583 [Button] Fix boron modifier
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
  assets/javascripts/kitten/constants/colors-config.js
  assets/stylesheets/kitten/_default-config.scss
  doc/design/colors.js
Labels: Needs review :hand:

#2584 [TextInput] Fix textarea padding
  CHANGELOG.md
  assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/field/field.stories.js
  assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-limit/text-input-with-limit.stories.js
  assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input/index.js
Labels: Needs review :hand:

#2585 v3.15.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/button/helpers/modifier-styles.js
  src/components/cards/crowdfunding-card/components/progress.js
  src/components/cards/crowdfunding-card/index.js
  src/components/form/dropdown-select-with-input/index.js
  src/components/form/text-input/index.js
  src/components/icons/lock-outline-icon/index.js
  src/components/icons/refund-icon/index.js
  src/components/icons/shield-check-icon/index.js
  src/components/layout/dashboard-layout/index.js
  src/components/layout/separator/index.js
  src/components/menus/dashboard-menu/index.js
  src/components/navigation/header-nav/index.js
  src/constants/colors-config.js
  src/esm/components/buttons/button/helpers/modifier-styles.js
  src/esm/components/cards/crowdfunding-card/components/progress.js
  src/esm/components/cards/crowdfunding-card/index.js
  src/esm/components/form/dropdown-select-with-input/index.js
  src/esm/components/form/text-input/index.js
  src/esm/components/icons/lock-outline-icon/index.js
  src/esm/components/icons/refund-icon/index.js
  src/esm/components/icons/shield-check-icon/index.js
  src/esm/components/layout/dashboard-layout/index.js
  src/esm/components/layout/separator/index.js
  src/esm/components/menus/dashboard-menu/index.js
  src/esm/components/navigation/header-nav/index.js
  src/esm/constants/colors-config.js
  src/esm/index.js
  src/index.js
  src/stylesheets/utilities.css
Labels: Needs review :hand:

#2586 [Button] Fix color icons default svg style
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button-question-mark-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button/button.stories.js
  assets/javascripts/kitten/components/buttons/button/button.stories.mdx
  assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
  assets/javascripts/kitten/components/buttons/checkable-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/close-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/social-button-icon-words/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/social-button-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/cart-reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/team-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/triptych/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card-with-action/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/icons/bancontact-icon/index.js
  assets/javascripts/kitten/components/icons/cb-icon/index.js
  assets/javascripts/kitten/components/icons/document-icon-empty/index.js
  assets/javascripts/kitten/components/icons/giropay-icon/index.js
  assets/javascripts/kitten/components/icons/ideal-icon/index.js
  assets/javascripts/kitten/components/icons/maestro-icon/index.js
  assets/javascripts/kitten/components/icons/mastercard-icon/index.js
  assets/javascripts/kitten/components/icons/paypal-icon/index.js
  assets/javascripts/kitten/components/icons/sofort-icon/index.js
  assets/javascripts/kitten/components/icons/visa-icon/index.js
  assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/menus/header-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/notifications/alert/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap
Labels: Needs review :hand:

#2587 [Colors] Fix sass colors
  CHANGELOG.md
  assets/stylesheets/kitten/_default-config.scss
Labels: Needs review :hand:

#2588 [CrowdfundingCard] Remove console warning when no Progress
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/index.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
Labels: Needs review :hand:

#2589 [RangeSlider] Add disabled prop
  CHANGELOG.md
  assets/javascripts/kitten/components/form/range-slider/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/range-slider/index.js
  assets/javascripts/kitten/components/form/range-slider/stories.js
  assets/javascripts/kitten/components/form/range-slider/test.js
Labels: Needs review :hand:

#2590 [RadioButton] Fix status style
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
Labels: Needs review :hand:

#2579 [ButtonGroup] Add orion variant
  CHANGELOG.md
  assets/javascripts/kitten/components/box/link-box/link-box.stories.js
  assets/javascripts/kitten/components/box/link-box/link-box.stories.mdx
  assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button-group/button-group.stories.js
  assets/javascripts/kitten/components/buttons/button-group/button-group.stories.mdx
  assets/javascripts/kitten/components/buttons/button-group/index.js
  assets/javascripts/kitten/components/buttons/button-group/test.js
  assets/javascripts/kitten/components/links/link-list/link-list.stories.mdx
Labels: Needs review :hand:

#2591 v3.16.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/button-group/index.js
  src/components/buttons/button/helpers/modifier-styles.js
  src/components/cards/crowdfunding-card/index.js
  src/components/form/radio-button/index.js
  src/components/form/range-slider/index.js
  src/components/icons/bancontact-icon/index.js
  src/components/icons/cb-icon/index.js
  src/components/icons/document-icon-empty/index.js
  src/components/icons/giropay-icon/index.js
  src/components/icons/ideal-icon/index.js
  src/components/icons/maestro-icon/index.js
  src/components/icons/mastercard-icon/index.js
  src/components/icons/paypal-icon/index.js
  src/components/icons/sofort-icon/index.js
  src/components/icons/visa-icon/index.js
  src/esm/components/buttons/button-group/index.js
  src/esm/components/buttons/button/helpers/modifier-styles.js
  src/esm/components/cards/crowdfunding-card/index.js
  src/esm/components/form/radio-button/index.js
  src/esm/components/form/range-slider/index.js
  src/esm/components/icons/bancontact-icon/index.js
  src/esm/components/icons/cb-icon/index.js
  src/esm/components/icons/document-icon-empty/index.js
  src/esm/components/icons/giropay-icon/index.js
  src/esm/components/icons/ideal-icon/index.js
  src/esm/components/icons/maestro-icon/index.js
  src/esm/components/icons/mastercard-icon/index.js
  src/esm/components/icons/paypal-icon/index.js
  src/esm/components/icons/sofort-icon/index.js
  src/esm/components/icons/visa-icon/index.js
  src/stylesheets/utilities.css
Labels: Needs review :hand:

#2593 [TeamCard] Fix button subcomponents
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/button-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/button-icon/index.js
  assets/javascripts/kitten/components/cards/team-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/team-card/components/button-with-tooltip.js
  assets/javascripts/kitten/components/cards/team-card/components/icons.js
  assets/javascripts/kitten/components/cards/team-card/components/phone-icon.js
Labels: Needs review :hand:

#2595 [DashboardLayout] Replace `Alerts` subcomponent with `Alerts` wrapper…
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
  assets/javascripts/kitten/components/layout/dashboard-layout/test.js
Labels: Needs review :hand:

#2596 v3.17.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/button-icon/index.js
  src/components/cards/team-card/components/button-with-tooltip.js
  src/components/cards/team-card/components/icons.js
  src/components/cards/team-card/components/phone-icon.js
  src/components/layout/dashboard-layout/index.js
  src/esm/components/buttons/button-icon/index.js
  src/esm/components/cards/team-card/components/button-with-tooltip.js
  src/esm/components/cards/team-card/components/icons.js
  src/esm/components/cards/team-card/components/phone-icon.js
  src/esm/components/layout/dashboard-layout/index.js
Labels: Needs review :hand:
