Repository KissKissBankBank/kitten, pull requests merged in 2021-07, with the labels that each got.

#2641 v3.22.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/grid/sticky-container/index.js
  src/components/navigation/header-nav/components/logged-out.js
  src/components/navigation/header-nav/components/logged.js
  src/components/navigation/header-nav/components/logo.js
  src/components/navigation/header-nav/components/quick-access-link.js
  src/components/navigation/header-nav/components/user-menu-next.js
  src/components/navigation/header-nav/components/user-menu.js
  src/components/navigation/header-nav/index.js
  src/components/navigation/header-nav/stories/kisskissbankbank-new.js
  src/components/navigation/header-nav/styles.js
  src/esm/components/grid/sticky-container/index.js
  src/esm/components/navigation/header-nav/components/logged-out.js
  src/esm/components/navigation/header-nav/components/logged.js
  src/esm/components/navigation/header-nav/components/logo.js
  src/esm/components/navigation/header-nav/components/quick-access-link.js
  src/esm/components/navigation/header-nav/components/user-menu-next.js
  src/esm/components/navigation/header-nav/components/user-menu.js
  src/esm/components/navigation/header-nav/index.js
  src/esm/components/navigation/header-nav/stories/kisskissbankbank-new.js
  src/esm/components/navigation/header-nav/styles.js
Labels: Needs review :hand:

#2642 [StickyContainer] Fix spacer height
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/sticky-container/index.js
  src/components/grid/sticky-container/index.js
  src/esm/components/grid/sticky-container/index.js
Labels: Needs review :hand:

#2644 [VerticalProgress] Add withoutBorder prop.
  CHANGELOG.md
  assets/javascripts/kitten/components/steppers/vertical-progress/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-progress/index.js
  assets/javascripts/kitten/components/steppers/vertical-progress/vertical-progress.stories.js
  assets/javascripts/kitten/components/steppers/vertical-progress/vertical-progress.stories.mdx
Labels: Needs review :hand:

#2646 [ContributionCard] Add onClose feature
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/contribution-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/contribution-card/index.js
Labels: Needs review :hand:

#2649 [RadioButton] Update hover active states
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
Labels: Enhancement, Feature :hatched_chick:

#2638 [Uploaders] New ImageDropUploader
  CHANGELOG.md
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/components/image-cropper.js
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/hooks/use-drag.js
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/index.js
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/stories.js
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#2647 [GiftIcon] Update
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/gift-icon/index.js
Labels: Needs review :hand:

#2605 [TagInput] Add component
  CHANGELOG.md
  assets/javascripts/kitten/components/form/tag-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/tag-input/index.js
  assets/javascripts/kitten/components/form/tag-input/stories.js
  assets/javascripts/kitten/components/form/tag-input/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#2640 [Uploaders] Documents drop uploader
  CHANGELOG.md
  assets/javascripts/kitten/components/uploaders/documents-drop-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/documents-drop-uploader/index.js
  assets/javascripts/kitten/components/uploaders/documents-drop-uploader/stories.js
  assets/javascripts/kitten/components/uploaders/documents-drop-uploader/test.js
  assets/javascripts/kitten/components/uploaders/documents-status-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/documents-status-box/index.js
  assets/javascripts/kitten/components/uploaders/documents-status-box/stories.js
  assets/javascripts/kitten/components/uploaders/documents-status-box/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#2650 [ContributionCard] Add isInputValid prop
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/contribution-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/contribution-card/components/action.js
  assets/javascripts/kitten/components/cards/contribution-card/components/input.js
  assets/javascripts/kitten/components/cards/contribution-card/contribution-card.stories.js
  assets/javascripts/kitten/components/cards/contribution-card/styles.js
  assets/javascripts/kitten/components/cards/contribution-card/test.js
Labels: Needs review :hand:

#2651 v2.23.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/contribution-card/components/action.js
  src/components/cards/contribution-card/components/input.js
  src/components/cards/contribution-card/index.js
  src/components/cards/contribution-card/styles.js
  src/components/form/radio-button/index.js
  src/components/form/tag-input/index.js
  src/components/icons/gift-icon/index.js
  src/components/steppers/vertical-progress/index.js
  src/components/uploaders/documents-drop-uploader/index.js
  src/components/uploaders/documents-status-box/index.js
  src/components/uploaders/image-drop-uploader/components/image-cropper.js
  src/components/uploaders/image-drop-uploader/hooks/use-drag.js
  src/components/uploaders/image-drop-uploader/index.js
  src/esm/components/cards/contribution-card/components/action.js
  src/esm/components/cards/contribution-card/components/input.js
  src/esm/components/cards/contribution-card/index.js
  src/esm/components/cards/contribution-card/styles.js
  src/esm/components/form/radio-button/index.js
  src/esm/components/form/tag-input/index.js
  src/esm/components/icons/gift-icon/index.js
  src/esm/components/steppers/vertical-progress/index.js
  src/esm/components/uploaders/documents-drop-uploader/index.js
  src/esm/components/uploaders/documents-status-box/index.js
  src/esm/components/uploaders/image-drop-uploader/components/image-cropper.js
  src/esm/components/uploaders/image-drop-uploader/hooks/use-drag.js
  src/esm/components/uploaders/image-drop-uploader/index.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#2655 [Release] add built js files for 3.23.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/contribution-card/styles.js
  src/esm/components/cards/contribution-card/styles.js
Labels: Needs review :hand:

#2653 [ImageDropUploader] Add `canCrop` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/components/image-cropper.js
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/hooks/use-drag.js
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/index.js
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/stories.js
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/utils/pause-event.js
Labels: Needs review :hand:

#2648 [TagButton] Update orion variant
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/tag-button/index.js
  assets/javascripts/kitten/components/buttons/tag-button/tag-button.stories.mdx
  assets/javascripts/kitten/components/buttons/tag-button/test.js
Labels: Needs review :hand:

#2654 [VerticalProgress] Update styles
  CHANGELOG.md
  assets/javascripts/kitten/components/steppers/vertical-progress/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-progress/components/status.js
  assets/javascripts/kitten/components/steppers/vertical-progress/index.js
Labels: Needs review :hand:

#2656 [Release] add built js files for 3.24.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/tag-button/index.js
  src/components/steppers/vertical-progress/components/status.js
  src/components/steppers/vertical-progress/index.js
  src/components/uploaders/image-drop-uploader/components/image-cropper.js
  src/components/uploaders/image-drop-uploader/hooks/use-drag.js
  src/components/uploaders/image-drop-uploader/index.js
  src/components/uploaders/image-drop-uploader/utils/pause-event.js
  src/esm/components/buttons/tag-button/index.js
  src/esm/components/steppers/vertical-progress/components/status.js
  src/esm/components/steppers/vertical-progress/index.js
  src/esm/components/uploaders/image-drop-uploader/components/image-cropper.js
  src/esm/components/uploaders/image-drop-uploader/hooks/use-drag.js
  src/esm/components/uploaders/image-drop-uploader/index.js
  src/esm/components/uploaders/image-drop-uploader/utils/pause-event.js
Labels: Needs review :hand:

#2657 Sanitize html by default
  CHANGELOG.md
  assets/javascripts/kitten/helpers/utils/parser.js
  assets/javascripts/kitten/helpers/utils/parser.test.js
  package-lock.json
  package.json
Labels: Needs review :hand:

#2658 [Release] add built js files for 3.25.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/esm/helpers/utils/parser.js
  src/helpers/utils/parser.js
Labels: Needs review :hand:

#2636 [Title] Update story and doc
  .storybook/main.js
  assets/javascripts/kitten/components/typography/title/index.js
  assets/javascripts/kitten/components/typography/title/stories.js
  package-lock.json
  package.json
Labels: Needs review :hand:

#2660 [VerticalProgress] Remove max-width
  CHANGELOG.md
  assets/javascripts/kitten/components/steppers/vertical-progress/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/vertical-progress/index.js
Labels: Needs review :hand:

#2661 [Release] add built js files for 3.25.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/steppers/vertical-progress/index.js
  src/components/typography/title/index.js
  src/esm/components/steppers/vertical-progress/index.js
  src/esm/components/typography/title/index.js
Labels: Needs review :hand:

#2663 Escape sanitize if we cant use dom
  CHANGELOG.md
  assets/javascripts/kitten/helpers/utils/parser.js
Labels: Needs review :hand:

#2664 V3.25.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/esm/helpers/utils/parser.js
  src/helpers/utils/parser.js
Labels: Needs review :hand:

#2662 [HeaderNav] Fix user menu position on mobile
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/header-nav/components/burger-menu-next.js
  assets/javascripts/kitten/components/navigation/header-nav/components/button.js
  assets/javascripts/kitten/components/navigation/header-nav/components/logged-out.js
  assets/javascripts/kitten/components/navigation/header-nav/components/logged.js
  assets/javascripts/kitten/components/navigation/header-nav/components/quick-access-link.js
  assets/javascripts/kitten/components/navigation/header-nav/components/user-menu-next.js
  assets/javascripts/kitten/components/navigation/header-nav/components/user-menu.js
  assets/javascripts/kitten/components/navigation/header-nav/hooks/use-dropdown.js
  assets/javascripts/kitten/components/navigation/header-nav/index.js
  assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank-new.js
  assets/javascripts/kitten/components/navigation/header-nav/styles.js
Labels: Needs review :hand:

#2665 [TagButton] Fix style on selected prop
  CHANGELOG.md
  assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/buttons/tag-button/index.js
Labels: Needs review :hand:

#2667 [ContributionCard] Fix image ratio
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/contribution-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/contribution-card/components/action.js
  assets/javascripts/kitten/components/cards/contribution-card/components/amount.js
  assets/javascripts/kitten/components/cards/contribution-card/components/description.js
  assets/javascripts/kitten/components/cards/contribution-card/components/image.js
  assets/javascripts/kitten/components/cards/contribution-card/components/input.js
  assets/javascripts/kitten/components/cards/contribution-card/components/pill-number.js
  assets/javascripts/kitten/components/cards/contribution-card/components/title.js
  assets/javascripts/kitten/components/cards/contribution-card/context.js
  assets/javascripts/kitten/components/cards/contribution-card/contribution-card.stories.js
  assets/javascripts/kitten/components/cards/contribution-card/index.js
  assets/javascripts/kitten/components/cards/contribution-card/styles.js
  assets/javascripts/kitten/components/cards/contribution-card/test.js
Labels: Needs review :hand:

#2666 [ImageDropUploader] Center vertically manage text
  CHANGELOG.md
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/uploaders/image-drop-uploader/index.js
Labels: Feature :hatched_chick:, Needs review :hand:

#2668 v3.26.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/buttons/tag-button/index.js
  src/components/cards/contribution-card/components/action.js
  src/components/cards/contribution-card/components/input.js
  src/components/cards/contribution-card/context.js
  src/components/cards/contribution-card/index.js
  src/components/cards/contribution-card/styles.js
  src/components/navigation/header-nav/components/burger-menu-next.js
  src/components/navigation/header-nav/components/logged-out.js
  src/components/navigation/header-nav/components/logged.js
  src/components/navigation/header-nav/components/user-menu-next.js
  src/components/navigation/header-nav/hooks/use-dropdown.js
  src/components/navigation/header-nav/index.js
  src/components/navigation/header-nav/styles.js
  src/components/uploaders/image-drop-uploader/index.js
  src/esm/components/buttons/tag-button/index.js
  src/esm/components/cards/contribution-card/components/action.js
  src/esm/components/cards/contribution-card/components/input.js
  src/esm/components/cards/contribution-card/context.js
  src/esm/components/cards/contribution-card/index.js
  src/esm/components/cards/contribution-card/styles.js
  src/esm/components/navigation/header-nav/components/burger-menu-next.js
  src/esm/components/navigation/header-nav/components/logged-out.js
  src/esm/components/navigation/header-nav/components/logged.js
  src/esm/components/navigation/header-nav/components/user-menu-next.js
  src/esm/components/navigation/header-nav/hooks/use-dropdown.js
  src/esm/components/navigation/header-nav/index.js
  src/esm/components/navigation/header-nav/styles.js
  src/esm/components/uploaders/image-drop-uploader/index.js
Labels: Needs review :hand:

#2645 [Typography] Add letter-spacing to Title
  .storybook/preview-head.html
  CHANGELOG.md
  assets/javascripts/kitten/components/box/information-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/cart-reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/triptych/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card-with-action/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/meters/counter-block/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/common/title-modifier-styles.js
  assets/javascripts/kitten/components/typography/title-with-stroke/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/title/__snapshots__/test.js.snap
Labels: Needs review :hand:

#2629 [Utilities] Generalize `!important` on all utility classes
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/engagement-card/engagement-card.stories.js
  assets/javascripts/kitten/components/cards/team-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/team-card/components/phone-icon.js
  assets/javascripts/kitten/components/cards/triptych/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card-with-action/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card-with-action/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
  assets/javascripts/kitten/components/modals/next/Modal.stories.js
  assets/javascripts/kitten/components/modals/next/index.js
  assets/javascripts/kitten/components/navigation/header-nav/components/button.js
  assets/javascripts/kitten/components/navigation/header-nav/components/hidden.js
  assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank-new.js
  assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank.js
  assets/javascripts/kitten/components/navigation/header-nav/stories/lendopolis.js
  assets/javascripts/kitten/karl/pages/homepage/video/index.js
  assets/stylesheets/kitten/_utilities.scss
  assets/stylesheets/kitten/helpers/_utility.scss
  assets/stylesheets/kitten/helpers/utility/_reverse.scss
  assets/stylesheets/kitten/utilities/align-self/_align-self.scss
  assets/stylesheets/kitten/utilities/background/_background-color.scss
  assets/stylesheets/kitten/utilities/border/_border.scss
  assets/stylesheets/kitten/utilities/cursor/_cursor.scss
  assets/stylesheets/kitten/utilities/display/_block.scss
  assets/stylesheets/kitten/utilities/display/_hidden.scss
  assets/stylesheets/kitten/utilities/display/_inline-block.scss
  assets/stylesheets/kitten/utilities/event/_pointer-event.scss
  assets/stylesheets/kitten/utilities/flex/_align-items.scss
  assets/stylesheets/kitten/utilities/flex/_display-flex.scss
  assets/stylesheets/kitten/utilities/flex/_flex-direction.scss
  assets/stylesheets/kitten/utilities/flex/_flex-wrap.scss
  assets/stylesheets/kitten/utilities/flex/_gap.scss
  assets/stylesheets/kitten/utilities/flex/_justify-content.scss
  assets/stylesheets/kitten/utilities/image/_responsive.scss
  assets/stylesheets/kitten/utilities/link/_link.scss
  assets/stylesheets/kitten/utilities/spacing/_margin.scss
  assets/stylesheets/kitten/utilities/text/_active.scss
  assets/stylesheets/kitten/utilities/text/_align.scss
  assets/stylesheets/kitten/utilities/text/_anti-aliasing.scss
  assets/stylesheets/kitten/utilities/text/_color.scss
  assets/stylesheets/kitten/utilities/text/_decoration.scss
  assets/stylesheets/kitten/utilities/text/_font-feature-settings.scss
  assets/stylesheets/kitten/utilities/text/_inactive.scss
  assets/stylesheets/kitten/utilities/text/_line-height.scss
  assets/stylesheets/kitten/utilities/text/_size.scss
  assets/stylesheets/kitten/utilities/text/_style.scss
  assets/stylesheets/kitten/utilities/text/_transform.scss
  assets/stylesheets/kitten/utilities/text/_weight.scss
  assets/stylesheets/utilities.scss
  doc/introduction/introduction.stories.mdx
  doc/usage/using-utilities.stories.mdx
  doc/utilities/align-self.stories.mdx
  doc/utilities/flex/flex-gap.stories.mdx
  doc/utilities/flex/flex-wrap.stories.mdx
  doc/utilities/link.stories.mdx
  doc/utilities/margin.stories.mdx
  src/stylesheets/utilities.css
Labels: Needs review :hand:, Proposition

#2659 [Global] Use Gap whenever feasible
  CHANGELOG.md
  assets/javascripts/kitten/components/atoms/loader-with-paragraph/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/loader-with-paragraph/index.js
  assets/javascripts/kitten/components/atoms/loader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/loader/index.js
  assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/backing-card/styles.js
  assets/javascripts/kitten/components/cards/team-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/team-card/components/icons.js
  assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/index.js
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/styles.js
  assets/javascripts/kitten/components/layout/line/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/line/index.js
  assets/javascripts/kitten/components/menus/dashboard-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/menus/dashboard-menu/index.js
  assets/javascripts/kitten/components/steppers/stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/stepper/index.js
  assets/javascripts/kitten/components/videos/video/__snapshots__/test.js.snap
Labels: Needs review :hand:

#2670 [KittenV4] Use `getReactElements` utils on `BakingCard` and `ContributionCard`
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/backing-card/components/button.js
  assets/javascripts/kitten/components/cards/backing-card/components/image.js
  assets/javascripts/kitten/components/cards/backing-card/index.js
  assets/javascripts/kitten/components/cards/backing-card/test.js
  assets/javascripts/kitten/components/cards/contribution-card/components/image.js
  assets/javascripts/kitten/components/cards/contribution-card/index.js
  assets/javascripts/kitten/components/cards/contribution-card/styles.js
Labels: Needs review :hand:

#2673 [KittenV4] Delete deprecated `CONTAINER_PADDING_MOBILE`
  CHANGELOG.md
  assets/javascripts/kitten/constants/grid-config.js
Labels: Needs review :hand:

#2674 [Utilities] Add display utils
  CHANGELOG.md
  assets/stylesheets/kitten/_utilities.scss
  assets/stylesheets/kitten/utilities/display/_display.scss
  assets/stylesheets/utilities.scss
  doc/utilities/display.stories.mdx
  doc/utilities/display/block.stories.mdx
  doc/utilities/display/hidden.stories.mdx
  doc/utilities/display/inline-block.stories.mdx
  doc/utilities/flex/display-flex.stories.mdx
Labels: Needs review :hand:

#2675 [Utilities] Add child verification on `getReactElements` helpers
  CHANGELOG.md
  assets/javascripts/kitten/components/molecules/cards/backing-card/stories.js
  assets/javascripts/kitten/helpers/react/react-elements.js
Labels: Needs review :hand:

#2676 [ModalNext] Fix sizing of Modal content
  CHANGELOG.md
  assets/javascripts/kitten/components/molecules/modal-next/index.js
Labels: Needs review :hand:

#2677 [ContributionCard] Various fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/molecules/cards/contribution-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/molecules/cards/contribution-card/components/title.js
  assets/javascripts/kitten/components/molecules/cards/contribution-card/contribution-card.stories.js
  assets/javascripts/kitten/components/molecules/cards/contribution-card/contribution-card.stories.mdx
  assets/javascripts/kitten/components/molecules/cards/contribution-card/index.js
  assets/javascripts/kitten/components/molecules/cards/contribution-card/styles.js
  assets/javascripts/kitten/components/molecules/cards/contribution-card/test.js
Labels: Needs review :hand:

#2679 [BackingCard] Fix border style
  CHANGELOG.md
  assets/javascripts/kitten/components/molecules/cards/backing-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/molecules/cards/backing-card/styles.js
Labels: Needs review :hand:

#2680 [ToggleTip] Remove console warning in tests
  CHANGELOG.md
  assets/javascripts/kitten/components/molecules/toggletip/index.js
Labels: Needs review :hand:

#2682 [DashboardLayout/Flow] Fix Navigation styles
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
Labels: Needs review :hand:

#2681 [Modal] Remove deprecation console.warn
  CHANGELOG.md
  assets/javascripts/kitten/components/molecules/modal/test.js
Labels: Needs review :hand:

#2683 v4.0.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/layout/dashboard-layout/flow/index.js
  src/components/molecules/cards/backing-card/styles.js
  src/components/molecules/cards/contribution-card/components/title.js
  src/components/molecules/cards/contribution-card/index.js
  src/components/molecules/cards/contribution-card/styles.js
  src/components/molecules/modal-next/index.js
  src/components/molecules/toggletip/index.js
  src/esm/components/layout/dashboard-layout/flow/index.js
  src/esm/components/molecules/cards/backing-card/styles.js
  src/esm/components/molecules/cards/contribution-card/components/title.js
  src/esm/components/molecules/cards/contribution-card/index.js
  src/esm/components/molecules/cards/contribution-card/styles.js
  src/esm/components/molecules/modal-next/index.js
  src/esm/components/molecules/toggletip/index.js
Labels: Needs review :hand:

#2684 [TextCopy] Fix WebKit sizing bug
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
  assets/javascripts/kitten/components/molecules/cards/contribution-card/contribution-card.stories.js
  assets/javascripts/kitten/components/molecules/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/molecules/text-copy/index.js
Labels: Needs review :hand:

#2685 [RadioButton] Update styles on orion variant
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
Labels: Needs review :hand:

#2687 [RadioButtonSet] Fix dimensions
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/index.js
Labels: Needs review :hand:

#2689 [DocumentDropUploader]improve onChange and onError events
  CHANGELOG.md
  assets/javascripts/kitten/components/molecules/upload/documents-drop-uploader/index.js
  assets/javascripts/kitten/components/molecules/upload/documents-drop-uploader/stories.js
Labels: Needs review :hand:

#2690 v4.0.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/radio-button-set/index.js
  src/components/form/radio-button/index.js
  src/components/molecules/text-copy/index.js
  src/components/molecules/upload/documents-drop-uploader/index.js
  src/esm/components/form/radio-button-set/index.js
  src/esm/components/form/radio-button/index.js
  src/esm/components/molecules/text-copy/index.js
  src/esm/components/molecules/upload/documents-drop-uploader/index.js
Labels: Needs review :hand:

#2693 Fix tests
  assets/javascripts/kitten/components/molecules/cards/triptych/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/molecules/cards/triptych/test.js
  assets/javascripts/kitten/components/molecules/carousels/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/molecules/carousels/carousel/test.js
  assets/javascripts/kitten/components/molecules/carousels/simple-carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/molecules/carousels/simple-carousel/test.js
Labels: Needs review :hand:

#2692 [HorizontalCrowdfundingCard] New component
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/flex-wrapper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/flex-wrapper/index.js
  assets/javascripts/kitten/components/layout/flex-wrapper/stories.js
  assets/javascripts/kitten/components/layout/flex-wrapper/test.js
  assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/index.js
  assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/stories.js
  assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#2691 [BackingCard] Fix text input width
  CHANGELOG.md
  assets/javascripts/kitten/components/molecules/cards/backing-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/molecules/cards/backing-card/styles.js
Labels: Needs review :hand:
