Repository KissKissBankBank/kitten, pull requests merged in 2021-03, with the labels that each got.

#2411 [HeaderNav] Fix StickyContainer width
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/header-nav/index.js
  assets/stylesheets/kitten/components/navigation/_header-nav.scss
Labels: Needs review :hand:

#2413 [DashboardLayout] Add new icons
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/icons/people-icon/index.js
  assets/javascripts/kitten/components/icons/speech-bubble-icon/index.js
  assets/javascripts/kitten/components/icons/stats-icon/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
  assets/javascripts/kitten/components/menus/dashboard-menu/stories.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#2406 [Fix] Fix missing `gap` in Flexbox for Safari
  CHANGELOG.md
  assets/javascripts/kitten/components/atoms/loader-with-paragraph/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/loader-with-paragraph/index.js
  assets/javascripts/kitten/components/atoms/loader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/loader/index.js
  assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/backing-card/index.js
  assets/javascripts/kitten/components/cards/backing-card/styles.js
  assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/images/image-cropper/index.js
  assets/javascripts/kitten/components/images/image-cropper/styles.js
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/index.js
  assets/javascripts/kitten/components/menus/dashboard-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/menus/dashboard-menu/index.js
  assets/javascripts/kitten/components/videos/video/__snapshots__/test.js.snap
Labels: Kitten V3 🐱, Needs review :hand:

#2414 v2.123.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/icons/people-icon/index.js
  src/components/icons/speech-bubble-icon/index.js
  src/components/icons/stats-icon/index.js
  src/components/layout/dashboard-layout/index.js
  src/components/navigation/header-nav/index.js
  src/esm/components/icons/people-icon/index.js
  src/esm/components/icons/speech-bubble-icon/index.js
  src/esm/components/icons/stats-icon/index.js
  src/esm/components/layout/dashboard-layout/index.js
  src/esm/components/navigation/header-nav/index.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#2375 [KittenV3] Remove deprecated tooltip components
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/field/components/label.js
  assets/javascripts/kitten/components/tooltips/question-mark-with-tooltip/index.js
  assets/javascripts/kitten/components/tooltips/static-tooltip/index.js
  assets/javascripts/kitten/components/tooltips/static-tooltip/test.js
  assets/javascripts/kitten/components/tooltips/tooltip-new/index.js
  assets/javascripts/kitten/components/tooltips/tooltip/index.js
  assets/javascripts/kitten/components/tooltips/tooltip/test.js
  assets/javascripts/kitten/components/tooltips/tooltip/tooltip.stories.js
  assets/javascripts/kitten/hoc/with-tooltip.js
  assets/javascripts/kitten/index.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/tooltips/_static-tooltip.scss
  assets/stylesheets/kitten/components/tooltips/_tooltip-new.scss
  assets/stylesheets/kitten/components/tooltips/_tooltip.scss
  package-lock.json
  package.json
Labels: Kitten V3 🐱, Needs review :hand:

#2379 [KittenV3] SideLayout & SideGrid
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/side-grid/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/side-grid/index.js
  assets/javascripts/kitten/components/grid/side-grid/stories.js
  assets/javascripts/kitten/components/grid/side-grid/test.js
  assets/javascripts/kitten/components/layout/side-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/side-layout/index.js
  assets/javascripts/kitten/components/layout/side-layout/stories.js
  assets/javascripts/kitten/components/layout/side-layout/test.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/grid/_side-grid.scss
  assets/stylesheets/kitten/components/grid/_vertical-grid.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2404 [KittenV3] Remove deprecated LinkBox/deprecated component
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/box/doc-link-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/box/doc-link-box/index.js
  assets/javascripts/kitten/components/box/information-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/box/information-box/index.js
  assets/javascripts/kitten/components/box/link-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/box/link-box/deprecated.js
  assets/javascripts/kitten/components/box/link-box/index.js
  assets/javascripts/kitten/components/box/link-box/styles.js
  assets/javascripts/kitten/components/box/link-box/test.js
  assets/javascripts/kitten/components/uploaders/document-manager/document-manager.stories.mdx
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/box/_link-box.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2403 [KittenV3] Add story to Marger
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/marger/index.js
  assets/javascripts/kitten/components/layout/marger/stories.js
Labels: Kitten V3 🐱, Needs review :hand:

#2415 v3.0.0-beta.6
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/arrow-icon/stories.js
  package-lock.json
  package.json
  src/components/atoms/loader-with-paragraph/index.js
  src/components/atoms/loader/index.js
  src/components/box/doc-link-box/index.js
  src/components/box/information-box/index.js
  src/components/box/link-box/deprecated.js
  src/components/box/link-box/index.js
  src/components/box/link-box/styles.js
  src/components/cards/backing-card/index.js
  src/components/cards/backing-card/styles.js
  src/components/form/field/components/label.js
  src/components/grid/side-grid/index.js
  src/components/images/image-cropper/index.js
  src/components/images/image-cropper/styles.js
  src/components/layout/dashboard-layout/flow/index.js
  src/components/layout/dashboard-layout/index.js
  src/components/layout/line/index.js
  src/components/layout/marger/index.js
  src/components/layout/side-layout/index.js
  src/components/menus/dashboard-menu/index.js
  src/components/navigation/header-nav/index.js
  src/components/tooltips/question-mark-with-tooltip/index.js
  src/components/tooltips/static-tooltip/index.js
  src/components/tooltips/tooltip-new/index.js
  src/components/tooltips/tooltip/index.js
  src/esm/components/atoms/loader-with-paragraph/index.js
  src/esm/components/atoms/loader/index.js
  src/esm/components/box/doc-link-box/index.js
  src/esm/components/box/information-box/index.js
  src/esm/components/box/link-box/deprecated.js
  src/esm/components/box/link-box/index.js
  src/esm/components/box/link-box/styles.js
  src/esm/components/cards/backing-card/index.js
  src/esm/components/cards/backing-card/styles.js
  src/esm/components/form/field/components/label.js
  src/esm/components/grid/side-grid/index.js
  src/esm/components/images/image-cropper/index.js
  src/esm/components/images/image-cropper/styles.js
  src/esm/components/layout/dashboard-layout/flow/index.js
  src/esm/components/layout/dashboard-layout/index.js
  src/esm/components/layout/line/index.js
  src/esm/components/layout/marger/index.js
  src/esm/components/layout/side-layout/index.js
  src/esm/components/menus/dashboard-menu/index.js
  src/esm/components/navigation/header-nav/index.js
  src/esm/components/tooltips/question-mark-with-tooltip/index.js
  src/esm/components/tooltips/static-tooltip/index.js
  src/esm/components/tooltips/tooltip-new/index.js
  src/esm/components/tooltips/tooltip/index.js
  src/esm/helpers/dom/use-flex-gap-check/index.js
  src/esm/hoc/with-tooltip.js
  src/esm/index.js
  src/helpers/dom/use-flex-gap-check/index.js
  src/hoc/with-tooltip.js
  src/index.js
Labels: Kitten V3 🐱, Needs review :hand:

#2416 [HeaderNav] Allow for null value on stickyProps
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/header-nav/index.js
  assets/javascripts/kitten/components/navigation/header-nav/stories.js
  assets/javascripts/kitten/components/navigation/header-nav/stories/lendopolis.js
Labels: Needs review :hand:

#2417 v2.123.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/navigation/header-nav/index.js
  src/components/navigation/header-nav/stories/lendopolis.js
  src/esm/components/navigation/header-nav/index.js
  src/esm/components/navigation/header-nav/stories/lendopolis.js
Labels: Needs review :hand:

#2412 [KittenV3] beta5 fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/atoms/badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/badge/index.js
  assets/javascripts/kitten/components/buttons/button-image-with-text-and-badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/dev/dev-grid/index.js
  assets/javascripts/kitten/components/navigation/header-nav/styles.js
  assets/javascripts/kitten/index.js
Labels: Kitten V3 🐱, Needs review :hand:

#2418 v3.0.0-beta.7
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/atoms/badge/index.js
  src/components/dev/dev-grid/index.js
  src/components/navigation/header-nav/index.js
  src/components/navigation/header-nav/styles.js
  src/esm/components/atoms/badge/index.js
  src/esm/components/dev/dev-grid/index.js
  src/esm/components/navigation/header-nav/index.js
  src/esm/components/navigation/header-nav/styles.js
  src/esm/index.js
  src/index.js
Labels: Kitten

#2419 [useFlexGapCheck] Add DOM check
  CHANGELOG.md
  assets/javascripts/kitten/helpers/dom/use-flex-gap-check/index.js
Labels: Needs review :hand:

#2407 [KittenV3] Migrate Stepper components
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/atoms/icon-badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/icon-badge/index.js
  assets/javascripts/kitten/components/atoms/icon-badge/stories.js
  assets/javascripts/kitten/components/atoms/stepper-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/stepper-icon/index.js
  assets/javascripts/kitten/components/atoms/stepper-icon/stories.js
  assets/javascripts/kitten/components/atoms/stepper-icon/test.js
  assets/javascripts/kitten/components/steppers/next/stepper.js
  assets/javascripts/kitten/components/steppers/next/stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/stepper-icon.js
  assets/javascripts/kitten/components/steppers/stepper.js
  assets/javascripts/kitten/components/steppers/stepper.test.js
  assets/javascripts/kitten/components/steppers/stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/steppers/stepper/deprecated.js
  assets/javascripts/kitten/components/steppers/stepper/index.js
  assets/javascripts/kitten/components/steppers/stepper/stepper-deprecated.stories.js
  assets/javascripts/kitten/components/steppers/stepper/stepper.stories.js
  assets/javascripts/kitten/components/steppers/stepper/test.js
  assets/javascripts/kitten/index.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/steppers/_stepper.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2420 v3.0.0-beta.8
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/atoms/icon-badge/index.js
  src/components/atoms/stepper-icon/index.js
  src/components/steppers/next/stepper.js
  src/components/steppers/stepper-icon.js
  src/components/steppers/stepper.js
  src/components/steppers/stepper/deprecated.js
  src/components/steppers/stepper/index.js
  src/esm/components/atoms/icon-badge/index.js
  src/esm/components/atoms/stepper-icon/index.js
  src/esm/components/steppers/next/stepper.js
  src/esm/components/steppers/stepper-icon.js
  src/esm/components/steppers/stepper.js
  src/esm/components/steppers/stepper/deprecated.js
  src/esm/components/steppers/stepper/index.js
  src/esm/helpers/dom/use-flex-gap-check/index.js
  src/esm/index.js
  src/helpers/dom/use-flex-gap-check/index.js
  src/index.js
Labels: Needs review :hand:

#2428 Fix carousel perf issue
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
  src/components/carousel/carousel/components/carousel-inner.js
  src/esm/components/carousel/carousel/components/carousel-inner.js
Labels: Needs review :hand:

#2429 V2.123.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#2430 Bump kitten version to 3.0.0-beta.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#2435 Fix ref element
  CHANGELOG.md
  assets/javascripts/kitten/helpers/utils/lazy-hook.js
  src/esm/helpers/utils/lazy-hook.js
  src/helpers/utils/lazy-hook.js
Labels: Needs review :hand:

#2436 Release v2.123.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#2433 [Bundles] Split imports to prevent bundling the whole Lodash package
  CHANGELOG.md
  assets/javascripts/kitten/components/form/dropdown-phone-select/index.js
Labels: Work in progress :construction:

#2437 v3.0.0-beta.10
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/dropdown-phone-select/index.js
  src/esm/components/form/dropdown-phone-select/index.js
Labels: Needs review :hand:

#2358 [KittenV3] Update Paragraph component
  CHANGELOG.md
  assets/javascripts/kitten/components/typography/paragraph/next/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/paragraph/next/index.js
  assets/javascripts/kitten/components/typography/paragraph/next/stories.js
  assets/javascripts/kitten/components/typography/paragraph/next/test.js
Labels: Kitten V3 🐱, Needs review :hand:

#2359 [KittenV3] Update Title component
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/box/information-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/box/information-box/index.js
  assets/javascripts/kitten/components/cards/cart-reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/cart-reward-card/index.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/donation-card/index.js
  assets/javascripts/kitten/components/cards/simple-card/components/title.js
  assets/javascripts/kitten/components/cards/simple-card/test.js
  assets/javascripts/kitten/components/cards/triptych/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/triptych/stories.js
  assets/javascripts/kitten/components/cards/triptych/test.js
  assets/javascripts/kitten/components/cards/vertical-card-with-action/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card-with-action/index.js
  assets/javascripts/kitten/components/cards/vertical-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card/index.js
  assets/javascripts/kitten/components/carousel/simple-carousel/stories.js
  assets/javascripts/kitten/components/meters/counter-block/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/meters/counter-block/index.js
  assets/javascripts/kitten/components/modals/modal/stories.js
  assets/javascripts/kitten/components/modals/next/index.js
  assets/javascripts/kitten/components/pages/markdown/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/popovers/simple-popover/index.js
  assets/javascripts/kitten/components/typography/title/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/title/index.js
  assets/javascripts/kitten/components/typography/title/stories.js
  assets/javascripts/kitten/components/typography/title/test.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/typography/_title.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2382 [KittenV3] Paragraph/next migration
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/cart-reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/cart-reward-card/index.js
  assets/javascripts/kitten/components/cards/triptych/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card-with-action/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card-with-action/index.js
  assets/javascripts/kitten/components/cards/vertical-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/vertical-card/index.js
  assets/javascripts/kitten/components/carousel/simple-carousel/stories.js
  assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/images/image-cropper/index.js
  assets/javascripts/kitten/components/modals/modal/stories.js
  assets/javascripts/kitten/components/modals/next/index.js
  assets/javascripts/kitten/components/pages/markdown/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/pages/markdown/components/paragraph.js
  assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/popovers/simple-popover/index.js
Labels: Kitten V3 🐱, Needs review :hand:

#2405 [KittenV3] Convert `FormActions`
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/form/form-actions/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/form-actions/form-actions.stories.js
  assets/javascripts/kitten/components/form/form-actions/index.js
  assets/javascripts/kitten/components/form/form-actions/test.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/form/_form-actions.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2408 [KittenV3] Migrate Grid
  .storybook/stylesheets/custom/_background.scss
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/triptych/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/grid/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/grid/index.js
  assets/javascripts/kitten/components/grid/grid/stories.js
  assets/javascripts/kitten/components/grid/grid/test.js
  assets/javascripts/kitten/components/grid/side-grid/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/heroes/hero/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/side-layout/__snapshots__/test.js.snap
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/footer/_footer.scss
  assets/stylesheets/kitten/components/grid/_grid.scss
  assets/stylesheets/kitten/components/grid/_side-grid.scss
  assets/stylesheets/kitten/components/grid/_single-column.scss
  assets/stylesheets/kitten/components/press/_press-quotes.scss
  assets/stylesheets/kitten/components/teaser/_teaser.scss
  assets/stylesheets/kitten/components/testimonies/_testimony-list.scss
  assets/stylesheets/kitten/components/titles/title-with-actions.scss
  assets/stylesheets/kitten/helpers/_grid.scss
  assets/stylesheets/kitten/helpers/grid/_col.scss
  assets/stylesheets/kitten/helpers/grid/_grid.scss
  assets/stylesheets/kitten/helpers/grid/_offset.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2409 [MakerV3] Migrate Row
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/row/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/row/index.js
  assets/javascripts/kitten/components/grid/row/stories.js
  assets/javascripts/kitten/components/grid/row/test.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/grid/_row.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2439 [Helpers] Remove buggy FlexGapCheck
  CHANGELOG.md
  assets/javascripts/kitten/components/atoms/loader-with-paragraph/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/loader-with-paragraph/index.js
  assets/javascripts/kitten/components/atoms/loader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/loader/index.js
  assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/backing-card/index.js
  assets/javascripts/kitten/components/cards/backing-card/styles.js
  assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/form-actions/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/form-actions/index.js
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/images/image-cropper/index.js
  assets/javascripts/kitten/components/images/image-cropper/styles.js
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/index.js
  assets/javascripts/kitten/components/layout/line/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/line/index.js
  assets/javascripts/kitten/components/menus/dashboard-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/menus/dashboard-menu/index.js
  assets/javascripts/kitten/components/videos/video/__snapshots__/test.js.snap
  assets/javascripts/kitten/helpers/dom/use-flex-gap-check/index.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#2440 Release/v3.0.0 beta.11
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/atoms/loader-with-paragraph/index.js
  src/components/atoms/loader/index.js
  src/components/box/information-box/index.js
  src/components/cards/backing-card/index.js
  src/components/cards/backing-card/styles.js
  src/components/cards/cart-reward-card/index.js
  src/components/cards/crowdfunding-card/components/title.js
  src/components/cards/donation-card/index.js
  src/components/cards/simple-card/components/title.js
  src/components/cards/vertical-card-with-action/index.js
  src/components/cards/vertical-card/index.js
  src/components/form/form-actions/index.js
  src/components/grid/grid/index.js
  src/components/grid/row/index.js
  src/components/images/image-cropper/index.js
  src/components/images/image-cropper/styles.js
  src/components/layout/dashboard-layout/flow/index.js
  src/components/layout/dashboard-layout/index.js
  src/components/layout/line/index.js
  src/components/menus/dashboard-menu/index.js
  src/components/meters/counter-block/index.js
  src/components/modals/next/index.js
  src/components/pages/markdown/components/paragraph.js
  src/components/popovers/simple-popover/index.js
  src/components/typography/paragraph/next/index.js
  src/components/typography/title/index.js
  src/esm/components/atoms/loader-with-paragraph/index.js
  src/esm/components/atoms/loader/index.js
  src/esm/components/box/information-box/index.js
  src/esm/components/cards/backing-card/index.js
  src/esm/components/cards/backing-card/styles.js
  src/esm/components/cards/cart-reward-card/index.js
  src/esm/components/cards/crowdfunding-card/components/title.js
  src/esm/components/cards/donation-card/index.js
  src/esm/components/cards/simple-card/components/title.js
  src/esm/components/cards/vertical-card-with-action/index.js
  src/esm/components/cards/vertical-card/index.js
  src/esm/components/form/form-actions/index.js
  src/esm/components/grid/grid/index.js
  src/esm/components/grid/row/index.js
  src/esm/components/images/image-cropper/index.js
  src/esm/components/images/image-cropper/styles.js
  src/esm/components/layout/dashboard-layout/flow/index.js
  src/esm/components/layout/dashboard-layout/index.js
  src/esm/components/layout/line/index.js
  src/esm/components/menus/dashboard-menu/index.js
  src/esm/components/meters/counter-block/index.js
  src/esm/components/modals/next/index.js
  src/esm/components/pages/markdown/components/paragraph.js
  src/esm/components/popovers/simple-popover/index.js
  src/esm/components/typography/paragraph/next/index.js
  src/esm/components/typography/title/index.js
  src/esm/helpers/dom/use-flex-gap-check/index.js
  src/esm/index.js
  src/helpers/dom/use-flex-gap-check/index.js
  src/index.js
Labels: Needs review :hand:

#2443 v3.0.0 beta.12
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/atoms/loader-with-paragraph/index.js
  src/components/atoms/loader/index.js
  src/components/cards/backing-card/index.js
  src/components/cards/backing-card/styles.js
  src/components/images/image-cropper/index.js
  src/components/images/image-cropper/styles.js
  src/components/layout/dashboard-layout/flow/index.js
  src/components/layout/dashboard-layout/index.js
  src/components/layout/line/index.js
  src/components/menus/dashboard-menu/index.js
  src/esm/components/atoms/loader-with-paragraph/index.js
  src/esm/components/atoms/loader/index.js
  src/esm/components/cards/backing-card/index.js
  src/esm/components/cards/backing-card/styles.js
  src/esm/components/images/image-cropper/index.js
  src/esm/components/images/image-cropper/styles.js
  src/esm/components/layout/dashboard-layout/flow/index.js
  src/esm/components/layout/dashboard-layout/index.js
  src/esm/components/layout/line/index.js
  src/esm/components/menus/dashboard-menu/index.js
  src/esm/helpers/dom/use-flex-gap-check/index.js
  src/esm/index.js
  src/helpers/dom/use-flex-gap-check/index.js
  src/index.js
Labels: Needs review :hand:

#2445 v3.0.0-beta.13
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#2446 [Paragraph] Move Next version to default
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/atoms/loader-with-paragraph/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/paragraph/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/paragraph/helpers/modifier-styles.js
  assets/javascripts/kitten/components/typography/paragraph/index.js
  assets/javascripts/kitten/components/typography/paragraph/next.js
  assets/javascripts/kitten/components/typography/paragraph/next/index.js
  assets/javascripts/kitten/components/typography/paragraph/next/test.js
  assets/javascripts/kitten/components/typography/paragraph/stories.js
  assets/javascripts/kitten/components/typography/paragraph/test.js
  assets/javascripts/kitten/next/index.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/typography/_paragraph.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2421 [ToggleTip] Fix warnings
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/field/components/label.js
  assets/javascripts/kitten/components/form/field/field.examples.js
  assets/javascripts/kitten/components/form/field/field.stories.js
  assets/javascripts/kitten/components/form/field/field.test.js
  assets/javascripts/kitten/components/tooltips/toggletip/index.js
  assets/javascripts/kitten/components/tooltips/toggletip/test.js
Labels: To release :rocket:

#2422 [KittenV3] Remove `DonationCard` and `TextInputWithUnitForm`
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/donation-card/donation-card.stories.js
  assets/javascripts/kitten/components/cards/donation-card/donation-card.stories.mdx
  assets/javascripts/kitten/components/cards/donation-card/index.js
  assets/javascripts/kitten/components/cards/donation-card/test.js
  assets/javascripts/kitten/components/form/text-input-with-unit-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit-form/index.js
  assets/javascripts/kitten/components/form/text-input-with-unit-form/test.js
  assets/javascripts/kitten/components/form/text-input-with-unit-form/text-input-with-unit-form.stories.js
  assets/javascripts/kitten/components/form/text-input-with-unit-form/text-input-with-unit-form.stories.mdx
  assets/javascripts/kitten/components/typography/title/index.js
  assets/javascripts/kitten/index.js
Labels: Kitten V3 🐱, To release :rocket:

#2423 [KittenV3] Migrate AvatarWithTextAndBadge
  CHANGELOG.md
  assets/javascripts/kitten/components/avatar/avatar-with-text-and-badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/avatar/avatar-with-text-and-badge/index.js
  assets/javascripts/kitten/components/avatar/avatar-with-text-and-badge/stories.js
  assets/javascripts/kitten/components/avatar/avatar-with-text-and-badge/test.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
  assets/javascripts/kitten/components/navigation/header-nav/styles.js
  assets/stylesheets/kitten/utilities/event/_pointer-event.scss
Labels: Kitten V3 🐱, To release :rocket:

#2424 [StatusWithBullet] Refactor component and add props
  CHANGELOG.md
  assets/javascripts/kitten/components/atoms/status-with-bullet/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/status-with-bullet/index.js
  assets/javascripts/kitten/components/atoms/status-with-bullet/status-with-bullet.stories.js
  assets/javascripts/kitten/components/atoms/status-with-bullet/status-with-bullet.stories.mdx
  assets/javascripts/kitten/components/atoms/status-with-bullet/test.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
  assets/javascripts/kitten/components/status-with-bullet/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/status-with-bullet/index.js
  assets/javascripts/kitten/components/status-with-bullet/test.js
  assets/javascripts/kitten/components/tables/list-table/list-table.stories.js
  assets/javascripts/kitten/index.js
Labels: To release :rocket:

#2426 [LongArrowIcon] Add component LongArrowIcon
  CHANGELOG.md
  assets/javascripts/kitten/components/icons/icons.stories.js
  assets/javascripts/kitten/components/icons/long-arrow-icon/__snapshots__/long-arrow-icon.test.js.snap
  assets/javascripts/kitten/components/icons/long-arrow-icon/index.js
  assets/javascripts/kitten/components/icons/long-arrow-icon/long-arrow-icon.test.js
  assets/javascripts/kitten/components/icons/long-arrow-icon/stories.js
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/index.js
  assets/javascripts/kitten/index.js
Labels: Feature :hatched_chick:, Needs review :hand:

#2447 v3.0.0-beta.14
  CHANGELOG.md
  assets/javascripts/kitten/components/atoms/loader-with-paragraph/index.js
  assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/paragraph/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/paragraph/index.js
  assets/javascripts/kitten/components/typography/paragraph/test.js
  package-lock.json
  package.json
  src/components/atoms/loader-with-paragraph/index.js
  src/components/atoms/status-with-bullet/index.js
  src/components/avatar/avatar-with-text-and-badge/index.js
  src/components/cards/donation-card/index.js
  src/components/form/field/components/label.js
  src/components/form/field/field.examples.js
  src/components/form/text-input-with-unit-form/index.js
  src/components/icons/long-arrow-icon/index.js
  src/components/layout/dashboard-layout/index.js
  src/components/navigation/header-nav/styles.js
  src/components/status-with-bullet/index.js
  src/components/tooltips/toggletip/index.js
  src/components/typography/paragraph/helpers/modifier-styles.js
  src/components/typography/paragraph/index.js
  src/components/typography/paragraph/next.js
  src/components/typography/paragraph/next/index.js
  src/esm/components/atoms/loader-with-paragraph/index.js
  src/esm/components/atoms/status-with-bullet/index.js
  src/esm/components/avatar/avatar-with-text-and-badge/index.js
  src/esm/components/cards/donation-card/index.js
  src/esm/components/form/field/components/label.js
  src/esm/components/form/field/field.examples.js
  src/esm/components/form/text-input-with-unit-form/index.js
  src/esm/components/icons/long-arrow-icon/index.js
  src/esm/components/layout/dashboard-layout/index.js
  src/esm/components/navigation/header-nav/styles.js
  src/esm/components/status-with-bullet/index.js
  src/esm/components/tooltips/toggletip/index.js
  src/esm/components/typography/paragraph/helpers/modifier-styles.js
  src/esm/components/typography/paragraph/index.js
  src/esm/components/typography/paragraph/next.js
  src/esm/components/typography/paragraph/next/index.js
  src/esm/index.js
  src/esm/next/index.js
  src/index.js
  src/next/index.js
  src/stylesheets/utilities.css
Labels: Needs review :hand:

#2448 [Tables] Fix classNames on SingleEntryTable and DoubleEntryTable
  CHANGELOG.md
  assets/javascripts/kitten/components/tables/double-entry-table/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/tables/double-entry-table/index.js
  assets/javascripts/kitten/components/tables/double-entry-table/test.js
  assets/javascripts/kitten/components/tables/single-entry-table/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/tables/single-entry-table/index.js
  assets/javascripts/kitten/components/tables/single-entry-table/test.js
Labels: Enhancement, Feature :hatched_chick:, Needs review :hand:

#2450 [Title] Fix default value for `noMargin`
  CHANGELOG.md
  assets/javascripts/kitten/components/pages/markdown/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/title/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/title/index.js
  assets/javascripts/kitten/components/typography/title/test.js
Labels: Kitten V3 🐱, Needs review :hand:

#2449 v2.124.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/tables/double-entry-table/index.js
  src/components/tables/single-entry-table/index.js
  src/esm/components/tables/double-entry-table/index.js
  src/esm/components/tables/single-entry-table/index.js
Labels: Needs review :hand:

#2451 v3.0.0-beta.15
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/typography/title/index.js
  src/esm/components/typography/title/index.js
Labels: Needs review :hand:

#2427 [HorizontalTimeline] Add component
  CHANGELOG.md
  assets/javascripts/kitten/components/lists/horizontal-timeline/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/lists/horizontal-timeline/index.js
  assets/javascripts/kitten/components/lists/horizontal-timeline/stories.js
  assets/javascripts/kitten/components/lists/horizontal-timeline/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#2457 [Grid] Fix `GridCol` offset class for `0` value.
  CHANGELOG.md
  assets/javascripts/kitten/components/grid/grid/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/grid/grid/index.js
  assets/javascripts/kitten/components/grid/grid/test.js
Labels: Bug :bug:, To release :rocket:

#2456 [HeaderNav] Fix `UserMenuButton` alignment on Chrome
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/header-nav/styles.js
Labels: Bug :bug:, To release :rocket:

#2455 [AvatarWithTextAndBadge] Fix ellipsis for children of `AvaratWithText…
  CHANGELOG.md
  assets/javascripts/kitten/components/atoms/status-with-bullet/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/atoms/status-with-bullet/index.js
  assets/javascripts/kitten/components/avatar/avatar-with-text-and-badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/avatar/avatar-with-text-and-badge/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
Labels: Bug :bug:, To release :rocket:

#2453 [Accordion] Fix error on fold
  CHANGELOG.md
  assets/javascripts/kitten/components/accordeon/index.js
Labels: Bug :bug:, To release :rocket:

#2401 [KittenV3] Migrate `ResponsiveIframeContainer`
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/responsive-iframe-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/responsive-iframe-container/index.js
  assets/javascripts/kitten/components/layout/responsive-iframe-container/stories.js
  assets/javascripts/kitten/components/layout/responsive-iframe-container/test.js
  assets/javascripts/kitten/components/videos/embed-player/__snapshots__/test.js.snap
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/layout/_responsive-iframe-container.scss
Labels: Kitten V3 🐱, To release :rocket:

#2395 [KittenV3] Drop SelectWithState (in favour of DrodownSelect)
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/accordeon/stories.js
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/field/components/select.js
  assets/javascripts/kitten/components/form/field/field.examples.js
  assets/javascripts/kitten/components/form/field/field.stories.js
  assets/javascripts/kitten/components/form/field/field.test.js
  assets/javascripts/kitten/components/form/field/index.js
  assets/javascripts/kitten/components/form/form-amount-and-currency/index.js
  assets/javascripts/kitten/components/form/form-amount-and-currency/test.js
  assets/javascripts/kitten/components/form/form-phone-number/index.js
  assets/javascripts/kitten/components/form/select-with-state/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select-with-state/index.js
  assets/javascripts/kitten/components/form/select-with-state/stories.js
  assets/javascripts/kitten/components/form/select-with-state/test.js
  assets/javascripts/kitten/components/form/text-input-and-select/index.js
  assets/javascripts/kitten/components/form/text-input-and-select/test.js
  assets/javascripts/kitten/index.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/form/_select.scss
  package-lock.json
  package.json
Labels: Kitten V3 🐱, To release :rocket:

#2462 [KittenV3] Delete `card` HOC and `k-Card` mixin
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/image.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/styles.js
  assets/javascripts/kitten/components/cards/simple-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/simple-card/components/image.js
  assets/javascripts/kitten/components/cards/simple-card/components/paragraph.js
  assets/javascripts/kitten/components/cards/simple-card/components/subtitle.js
  assets/javascripts/kitten/components/cards/simple-card/components/title.js
  assets/javascripts/kitten/components/cards/simple-card/index.js
  assets/javascripts/kitten/components/cards/simple-card/stories.js
  assets/javascripts/kitten/components/cards/simple-card/test.js
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/cards/_card.scss
Labels: Kitten V3 🐱, Needs base jump :baseball:, Needs review :hand:

#2454 [KittenV3] Add Exports to ESM
  CHANGELOG.md
  assets/javascripts/kitten/index.js
Labels: Kitten V3 🐱, Needs review :hand:

#2431 [KittenV3] Refacto BulletList
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/reward-edition/stories.js
  assets/javascripts/kitten/components/lists/bullet-list/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/lists/bullet-list/bullet-list.stories.js
  assets/javascripts/kitten/components/lists/bullet-list/bullet-list.stories.mdx
  assets/javascripts/kitten/components/lists/bullet-list/index.js
  assets/javascripts/kitten/components/lists/bullet-list/test.js
  assets/javascripts/kitten/components/pages/markdown/__snapshots__/test.js.snap
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/lists/_bullet-list.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2425 [KittenV3] Update SimpleCard
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/image.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
  assets/javascripts/kitten/components/cards/crowdfunding-card/styles.js
  assets/javascripts/kitten/components/cards/simple-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/simple-card/components/image.js
  assets/javascripts/kitten/components/cards/simple-card/components/paragraph.js
  assets/javascripts/kitten/components/cards/simple-card/components/subtitle.js
  assets/javascripts/kitten/components/cards/simple-card/components/title.js
  assets/javascripts/kitten/components/cards/simple-card/index.js
  assets/javascripts/kitten/components/cards/simple-card/stories.js
  assets/javascripts/kitten/components/cards/simple-card/test.js
  assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/cards/_card.scss
Labels: Kitten V3 🐱, To release :rocket:

#2458 [KittenV3] Delete MarkdownPage, TabBar, HorizontalNav
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/lists/bullet-list/bullet-list.stories.js
  assets/javascripts/kitten/components/lists/bullet-list/test.js
  assets/javascripts/kitten/components/navigation/horizontal-nav/index.js
  assets/javascripts/kitten/components/navigation/horizontal-nav/stories.js
  assets/javascripts/kitten/components/navigation/horizontal-nav/test.js
  assets/javascripts/kitten/components/navigation/tab-bar/index.js
  assets/javascripts/kitten/components/navigation/tab-bar/tab-bar.stories.js
  assets/javascripts/kitten/components/navigation/tab-bar/test.js
  assets/javascripts/kitten/components/pages/markdown/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/pages/markdown/components/context.js
  assets/javascripts/kitten/components/pages/markdown/components/heading.js
  assets/javascripts/kitten/components/pages/markdown/components/link.js
  assets/javascripts/kitten/components/pages/markdown/components/list.js
  assets/javascripts/kitten/components/pages/markdown/components/paragraph.js
  assets/javascripts/kitten/components/pages/markdown/index.js
  assets/javascripts/kitten/components/pages/markdown/stories.js
  assets/javascripts/kitten/components/pages/markdown/test.js
  assets/javascripts/kitten/index.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/navigation/_horizontal-nav.scss
  assets/stylesheets/kitten/components/navigation/_tab-bar.scss
  package-lock.json
  package.json
Labels: Kitten V3 🐱, Needs review :hand:

#2345 [V3] Migrate Label and remove `k-Label` styles
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/form/checkbox-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/label/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/label/index.js
  assets/javascripts/kitten/components/form/label/label.stories.js
  assets/javascripts/kitten/components/form/label/test.js
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/form/_label.scss
Labels: Kitten V3 🐱, Needs review :hand:

#2432 [KittenV3] Refacto size prop on TextInput
  CHANGELOG.md
  assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-button/index.js
  assets/javascripts/kitten/components/form/text-input-with-button/test.js
  assets/javascripts/kitten/components/form/text-input-with-button/text-input-with-button.stories.js
  assets/javascripts/kitten/components/form/text-input-with-button/text-input-with-button.stories.mdx
  assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-icon/index.js
  assets/javascripts/kitten/components/form/text-input-with-icon/text-input-with-icon.stories.mdx
  assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-limit/test.js
  assets/javascripts/kitten/components/form/text-input-with-limit/text-input-with-limit.stories.mdx
  assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input-with-unit/index.js
  assets/javascripts/kitten/components/form/text-input-with-unit/test.js
  assets/javascripts/kitten/components/form/text-input-with-unit/text-input-with-unit.stories.js
  assets/javascripts/kitten/components/form/text-input-with-unit/text-input-with-unit.stories.mdx
  assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/text-input/index.js
  assets/javascripts/kitten/components/form/text-input/test.js
  assets/javascripts/kitten/components/form/text-input/text-input.stories.js
  assets/javascripts/kitten/components/form/text-input/text-input.stories.mdx
Labels: Kitten V3 🐱, Needs review :hand:

#2463 v3.0.0-beta.17
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/cards/crowdfunding-card/components/image.js
  src/components/cards/crowdfunding-card/components/title.js
  src/components/cards/crowdfunding-card/styles.js
  src/components/cards/simple-card/components/image.js
  src/components/cards/simple-card/components/paragraph.js
  src/components/cards/simple-card/components/subtitle.js
  src/components/cards/simple-card/components/title.js
  src/components/cards/simple-card/index.js
  src/components/form/label/index.js
  src/components/form/text-input-with-button/index.js
  src/components/form/text-input-with-icon/index.js
  src/components/form/text-input-with-unit/index.js
  src/components/form/text-input/index.js
  src/components/lists/bullet-list/index.js
  src/components/navigation/horizontal-nav/index.js
  src/components/navigation/tab-bar/index.js
  src/components/pages/markdown/components/context.js
  src/components/pages/markdown/components/heading.js
  src/components/pages/markdown/components/link.js
  src/components/pages/markdown/components/list.js
  src/components/pages/markdown/components/paragraph.js
  src/components/pages/markdown/index.js
  src/esm/components/cards/crowdfunding-card/components/image.js
  src/esm/components/cards/crowdfunding-card/components/title.js
  src/esm/components/cards/crowdfunding-card/styles.js
  src/esm/components/cards/simple-card/components/image.js
  src/esm/components/cards/simple-card/components/paragraph.js
  src/esm/components/cards/simple-card/components/subtitle.js
  src/esm/components/cards/simple-card/components/title.js
  src/esm/components/cards/simple-card/index.js
  src/esm/components/form/label/index.js
  src/esm/components/form/text-input-with-button/index.js
  src/esm/components/form/text-input-with-icon/index.js
  src/esm/components/form/text-input-with-unit/index.js
  src/esm/components/form/text-input/index.js
  src/esm/components/lists/bullet-list/index.js
  src/esm/components/navigation/horizontal-nav/index.js
  src/esm/components/navigation/tab-bar/index.js
  src/esm/components/pages/markdown/components/context.js
  src/esm/components/pages/markdown/components/heading.js
  src/esm/components/pages/markdown/components/link.js
  src/esm/components/pages/markdown/components/list.js
  src/esm/components/pages/markdown/components/paragraph.js
  src/esm/components/pages/markdown/index.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#2452 [KittenV3] Add logos
  CHANGELOG.md
  assets/javascripts/kitten/components/logos/goodeedlogo/index.js
  assets/javascripts/kitten/components/logos/kkbb-co/index.js
  assets/javascripts/kitten/components/logos/logos.stories.js
  assets/javascripts/kitten/components/logos/mdc/index.js
  assets/javascripts/kitten/components/logos/microdonlogo/index.js
  assets/javascripts/kitten/index.js
Labels: Kitten V3 🐱, Needs review :hand:, To release :rocket:

#2461 [KittenV3] Refactor & move Dropdown V2
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/form/text-input-with-button/index.js
  assets/javascripts/kitten/components/form/text-input-with-icon/index.js
  assets/javascripts/kitten/components/form/text-input-with-unit/index.js
  assets/javascripts/kitten/components/navigation/header-nav/components/burger-menu.js
  assets/javascripts/kitten/components/navigation/header-nav/components/dropdown-button.js
  assets/javascripts/kitten/components/navigation/header-nav/components/dropdown.js
  assets/javascripts/kitten/components/navigation/header-nav/components/user-menu.js
  assets/javascripts/kitten/components/navigation/header-nav/styles.js
  assets/javascripts/kitten/index.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/dropdowns/_dropdown.scss
  assets/stylesheets/kitten/components/navigation/_platform-switch.scss
  assets/stylesheets/kitten/components/navigation/_user-menu.scss
Labels: Needs review :hand:, To release :rocket:

#2466 [KittenV3] Add missing exports to ESM exports
  CHANGELOG.md
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:, To release :rocket:

#2468 v3.0.0-beta.19
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/logos/goodeedlogo/index.js
  src/components/logos/kkbb-co/index.js
  src/components/logos/mdc/index.js
  src/components/logos/microdonlogo/index.js
  src/components/navigation/header-nav/components/burger-menu.js
  src/components/navigation/header-nav/components/dropdown-button.js
  src/components/navigation/header-nav/components/dropdown.js
  src/components/navigation/header-nav/components/user-menu.js
  src/components/navigation/header-nav/styles.js
  src/esm/components/logos/goodeedlogo/index.js
  src/esm/components/logos/kkbb-co/index.js
  src/esm/components/logos/mdc/index.js
  src/esm/components/logos/microdonlogo/index.js
  src/esm/components/navigation/header-nav/components/burger-menu.js
  src/esm/components/navigation/header-nav/components/dropdown-button.js
  src/esm/components/navigation/header-nav/components/dropdown.js
  src/esm/components/navigation/header-nav/components/user-menu.js
  src/esm/components/navigation/header-nav/styles.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#2471 Bump de packages devDependencies
  .husky/.gitignore
  .husky/pre-commit
  .storybook/decorators/grid.js
  .storybook/main.js
  .storybook/preview.js
  assets/javascripts/kitten/components/accordeon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/cards/triptych/index.js
  assets/javascripts/kitten/components/form/rich-text-input/index.js
  assets/javascripts/kitten/components/links/link-list/link-list.stories.mdx
  assets/javascripts/kitten/components/typography/sup-title/sup-title.stories.js
  assets/javascripts/kitten/components/typography/sup-title/sup-title.stories.mdx
  assets/javascripts/kitten/components/typography/text/text.stories.mdx
  assets/javascripts/kitten/config/jest-setup.js
  assets/javascripts/kitten/helpers/utils/debounce.js
  assets/javascripts/kitten/karl/pages/pre-deposit/pre-deposit.stories.js
  babel.config.js
  package-lock.json
  package.json
  postcss.config.js
  webpack.config.js
  webpack.config.sass.js
  webpack/sass.config.js
  webpack/utilities.config.js
Labels: Needs review :hand:

#2472 Bump packages
  assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/side-layout/index.js
  package-lock.json
  package.json
Labels: Needs review :hand:

#2474 Remove unused packages
  assets/javascripts/kitten/components/form/credit-card-form/examples.js
  package-lock.json
  package.json
Labels: Needs review :hand:

#2475 set back npm install before I run storybook
  package.json
Labels: Needs review :hand:

#2476 [KittenV3] fix Carousel resize observer
  CHANGELOG.md
  assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
  assets/javascripts/kitten/components/carousel/carousel/project-carousel.stories.js
Labels: To release :rocket:

#2473 [HorizontalTimeline] Fix `className` property name
  CHANGELOG.md
  assets/javascripts/kitten/components/lists/horizontal-timeline/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/lists/horizontal-timeline/index.js
Labels: To release :rocket:

#2467 [KittenV3] Remove `src/next` exports and add `ModalNext` ESM export.
  CHANGELOG.md
  assets/javascripts/kitten/components/modals/modal/index.js
  assets/javascripts/kitten/components/modals/next/Modal.stories.js
  assets/javascripts/kitten/components/modals/next/index.js
  assets/javascripts/kitten/index.js
  assets/javascripts/kitten/next/index.js
Labels: Kitten V3 🐱, To release :rocket:

#2400 [KittenV3] Migrate location input
  .storybook/stylesheets/kitten/_components.scss
  CHANGELOG.md
  assets/javascripts/kitten/components/form/location-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/location-input/index.js
  assets/javascripts/kitten/components/form/location-input/stories.js
  assets/javascripts/kitten/components/form/location-input/test.js
  assets/javascripts/kitten/config/__mocks__/googleMock.js
  assets/stylesheets/kitten/_components.scss
  assets/stylesheets/kitten/components/form/_location-input.scss
  package-lock.json
  package.json
Labels: Kitten V3 🐱, To release :rocket:

#2477 Use CustomEvent instead of event-emitter
  assets/javascripts/kitten/components/navigation/header-nav/components/dropdown.js
  assets/javascripts/kitten/components/navigation/header-nav/index.js
  assets/javascripts/kitten/helpers/utils/emitter.js
  package-lock.json
  package.json
Labels: Needs review :hand:, To release :rocket:

#2480 Remove `RichTextInput`
  CHANGELOG.md
  assets/javascripts/kitten/components/form/rich-text-input/index.js
  assets/javascripts/kitten/components/form/rich-text-input/test.js
  assets/javascripts/kitten/index.js
  package-lock.json
  package.json
Labels: Kitten V3 🐱, To release :rocket:

#2482 Improve dependencies instalIation
  package-lock.json
  package.json
Labels: Needs review :hand:

#2483 improve dependencies installation
  package-lock.json
  package.json
Labels: Needs review :hand:

#2487 rollback-cropper
  CHANGELOG.md
  package.json
Labels: Needs review :hand:

#2488 3.0.0-beta.22
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs review :hand:

#2486 [LocationInput] Fix style and warning
  CHANGELOG.md
  assets/javascripts/kitten/components/form/location-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/location-input/index.js
  assets/javascripts/kitten/components/form/location-input/stories.js
Labels: Needs review :hand:

#2492 [BulletList] Fix item classes transmission
  CHANGELOG.md
  assets/javascripts/kitten/components/lists/bullet-list/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/lists/bullet-list/index.js
  assets/javascripts/kitten/components/lists/bullet-list/test.js
Labels: Needs review :hand:
