Repository KissKissBankBank/kitten, pull requests merged in 2022-05, with the labels that each got.

#3166 [AvatarWithTextAndBadge] Better prop propagation on `Image` subcomponent
  CHANGELOG.md
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/index.js
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/test.js
Labels: Needs review :hand:

#3155 [Toggletip] Improve styles.
  CHANGELOG.md
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/components/label.js
  assets/javascripts/kitten/components/information/toggletip/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/toggletip/index.js
  assets/javascripts/kitten/components/information/toggletip/stories.js
  assets/javascripts/kitten/components/information/toggletip/test.js
  assets/javascripts/kitten/components/layer/toggletip/__snapshots__/test.js.snap
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3164 [HeaderNav] Fix BurgerButton icon position
  CHANGELOG.md
  assets/javascripts/kitten/components/navigation/header-nav/styles.js
Labels: Needs review :hand:

#3169 [ManagerCard] Fix multiline content
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/manager-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/manager-card/index.js
  assets/javascripts/kitten/components/structure/cards/manager-card/stories.js
Labels: Needs review :hand:

#3170 [Modal] Add `as` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/layer/modal/index.js
  assets/javascripts/kitten/components/layer/modal/stories.js
  assets/javascripts/kitten/components/layer/modal/test.js
Labels: Needs review :hand:

#3171 [DropdownMenu] Add onOpen and onClose props
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/expand/dropdown-menu/index.js
  assets/javascripts/kitten/components/structure/expand/dropdown-menu/stories.js
  assets/javascripts/kitten/helpers/hooks/use-focus-trap/index.js
Labels: Needs review :hand:

#3172 [Tests] Remove warnings and errors
  assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select/test.js
  assets/javascripts/kitten/components/information/toggletip/test.js
  assets/javascripts/kitten/components/structure/cards/editorial-card/test.js
Labels: Needs review :hand:

#3173 v10.6.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/layer/modal/index.js
  src/components/structure/cards/manager-card/index.js
  src/components/structure/expand/dropdown-menu/index.js
  src/esm/components/layer/modal/index.js
  src/esm/components/structure/cards/manager-card/index.js
  src/esm/components/structure/expand/dropdown-menu/index.js
  src/esm/helpers/hooks/use-focus-trap/index.js
  src/helpers/hooks/use-focus-trap/index.js
Labels: Needs review :hand:

#3168 [Cards] Add `BoxShadow` variable
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/project-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/project-card/styles.js
  assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/reward-card/styles.js
  assets/javascripts/kitten/components/structure/carousels/carousel/__snapshots__/test.js.snap
  assets/stylesheets/kitten/tokens/_box-shadow.scss
  data/output.json
  data/tokens.json
  sd.config.js
  src/stylesheets/tokens.css
Labels: Needs review :hand:

#3179 [Carousel] Add shadowSize prop
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/project-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/project-card/styles.js
  assets/javascripts/kitten/components/structure/carousels/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/carousels/carousel/index.js
  assets/javascripts/kitten/components/structure/carousels/carousel/stories.js
  assets/javascripts/kitten/components/structure/carousels/carousel/styles.js
  assets/javascripts/kitten/components/structure/carousels/carousel/test.js
Labels: Needs review :hand:

#3180 v10.8.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/structure/cards/project-card/styles.js
  src/components/structure/carousels/carousel/index.js
  src/components/structure/carousels/carousel/styles.js
  src/esm/components/structure/cards/project-card/styles.js
  src/esm/components/structure/carousels/carousel/index.js
  src/esm/components/structure/carousels/carousel/styles.js
Labels: Kitten

#3181 [DashboardLayout] New dashboard story
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
  assets/javascripts/kitten/components/graphics/icons-next/microphone-icon-next/index.js
  assets/javascripts/kitten/components/graphics/icons-next/question-bubble-icon-next/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories/with-dashboard.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3182 [Composition] Button with clickable link
  assets/javascripts/kitten/karl/compositions/button-with-link.stories.js
  assets/javascripts/kitten/karl/compositions/editor/components/actions.js
  assets/javascripts/kitten/karl/compositions/editor/components/button.js
  assets/javascripts/kitten/karl/compositions/editor/components/layout.js
  assets/javascripts/kitten/karl/compositions/editor/components/tag-list.js
  assets/javascripts/kitten/karl/compositions/editor/components/toolbar.js
  assets/javascripts/kitten/karl/compositions/editor/stories.js
Labels: Needs review :hand:, Kitten

#3185 v10.9.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/graphics/icons-next/microphone-icon-next/index.js
  src/components/graphics/icons-next/question-bubble-icon-next/index.js
  src/components/layout/hero-layout/index.js
  src/components/layout/hero-layout/styles.js
  src/components/navigation/floating-menu/index.js
  src/components/structure/cards/profile-card/index.js
  src/esm/components/graphics/icons-next/microphone-icon-next/index.js
  src/esm/components/graphics/icons-next/question-bubble-icon-next/index.js
  src/esm/components/layout/hero-layout/index.js
  src/esm/components/layout/hero-layout/styles.js
  src/esm/components/navigation/floating-menu/index.js
  src/esm/components/structure/cards/profile-card/index.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#3189 [HeroLayout] Fix automated assignment of hasTopMenu
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/hero-layout/index.js
Labels: Needs review :hand:

#3187 [ContentCard] Improve style.
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/content-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/content-card/index.js
Labels: Needs review :hand:

#3188 [Icons] Add `GoogleIconNext` and `FacebookIconCircleNext` components.
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/facebook-icon-circle-next/index.js
  assets/javascripts/kitten/components/graphics/icons-next/google-icon-next/index.js
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3186 [RadioButton] Optimization css
  CHANGELOG.md
  assets/javascripts/kitten/components/form/checkbox-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/checkbox-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/checkbox-button/index.js
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
Labels: Needs review :hand:

#3190 [Utilities] Add border utility classes
  CHANGELOG.md
  assets/stylesheets/kitten/tokens/_borders.scss
  assets/stylesheets/kitten/utilities/border/_border.scss
Labels: Needs review :hand:

#3193 [ContentCard] Add `box-shadow` variable.
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/content-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/content-card/index.js
Labels: Needs review :hand:

#3192 [AlertBox] Improve `IconBadge` style.
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/status-icon-next/index.js
  assets/javascripts/kitten/components/information/alert/__snapshots__/test.js.snap
Labels: Needs review :hand:

#3196 v10.11.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/field/components/autocomplete.js
  src/components/form/field/components/checkbox.js
  src/components/form/field/components/error.js
  src/components/form/field/components/help.js
  src/components/form/field/components/input.js
  src/components/form/field/components/label.js
  src/components/form/field/components/password.js
  src/components/form/field/components/radio-button-set.js
  src/components/form/field/components/radio-set.js
  src/components/form/field/examples.js
  src/components/form/field/index.js
  src/components/graphics/icons-next/status-icon-next/index.js
  src/components/information/toggletip/index.js
  src/components/navigation/messages-menu/index.js
  src/components/structure/cards/content-card/index.js
  src/esm/components/form/field/components/autocomplete.js
  src/esm/components/form/field/components/checkbox.js
  src/esm/components/form/field/components/error.js
  src/esm/components/form/field/components/help.js
  src/esm/components/form/field/components/input.js
  src/esm/components/form/field/components/label.js
  src/esm/components/form/field/components/password.js
  src/esm/components/form/field/components/radio-button-set.js
  src/esm/components/form/field/components/radio-set.js
  src/esm/components/form/field/examples.js
  src/esm/components/form/field/index.js
  src/esm/components/graphics/icons-next/status-icon-next/index.js
  src/esm/components/information/toggletip/index.js
  src/esm/components/navigation/messages-menu/index.js
  src/esm/components/structure/cards/content-card/index.js
Labels: Needs review :hand:

#3200 [Footer] Add variant="minimalist"
  assets/javascripts/kitten/karl/pages/footer/components/created-with.js
  assets/javascripts/kitten/karl/pages/footer/components/index.js
  assets/javascripts/kitten/karl/pages/footer/index.js
  assets/javascripts/kitten/karl/pages/footer/stories.js
  assets/javascripts/kitten/karl/pages/footer/styles.js
Labels: Needs review :hand:

#3204 [Bullet] Add hasBullet prop
  CHANGELOG.md
  assets/javascripts/kitten/components/action/button-group/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/button-question-mark-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/button-with-tooltip/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/button/index.js
  assets/javascripts/kitten/components/action/button/stories.js
  assets/javascripts/kitten/components/action/checkable-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/close-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/social-button-icon-words/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/social-button-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/color-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/modal-footer-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/standalone-range-date-picker/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/discussion/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/drag-and-drop-list/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/upload/basic-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/upload/document-manager/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/upload/image-drop-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layer/modal/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/header-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/contribution-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/team-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/triptych/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/vertical-card-with-action/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/expand/expand-board/__snapshots__/test.js.snap
Labels: Needs review :hand:

#3201 [AirplaneIconNext] Add `direction` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/airplane-icon-next/index.js
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
Labels: Needs review :hand:

#3205 v10.12.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/action/button/index.js
  src/components/action/checkable-button/index.js
  src/components/form/input/tag-input-autocomplete/index.js
  src/components/graphics/icons-next/airplane-icon-next/index.js
  src/components/interaction/drag-and-drop-list/index.js
  src/components/layout/dashboard-layout/index.js
  src/components/navigation/header-nav/index.js
  src/esm/components/action/button/index.js
  src/esm/components/action/checkable-button/index.js
  src/esm/components/form/input/tag-input-autocomplete/index.js
  src/esm/components/graphics/icons-next/airplane-icon-next/index.js
  src/esm/components/interaction/drag-and-drop-list/index.js
  src/esm/components/layout/dashboard-layout/index.js
  src/esm/components/navigation/header-nav/index.js
Labels: Needs review :hand:

#3206 [HorizontalProjectCard] Remove last line if no info
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/horizontal-project-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/horizontal-project-card/index.js
  assets/javascripts/kitten/components/structure/cards/horizontal-project-card/test.js
Labels: Needs review :hand:

#3207 [Footer] Little fixe
  assets/javascripts/kitten/karl/pages/footer/index.js
  assets/javascripts/kitten/karl/pages/footer/styles.js
Labels: Needs review :hand:
