Repository KissKissBankBank/kitten, pull requests merged in 2022-06, with the labels that each got.

#3215 [V11/TagButton] Remove old deprecated props
  CHANGELOG.md
  assets/javascripts/kitten/components/action/tag-button/index.js
Labels: Needs review :hand:, Breaking change :broken_heart:

#3214 [V11] Remove andromeda variant
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/examples.js
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/index.js
  assets/javascripts/kitten/components/form/radio-button-set/stories.js
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
  assets/javascripts/kitten/components/form/radio-button/stories.js
Labels: Needs review :hand:, Breaking change :broken_heart:

#3213 [V11/AvatarWithTextAndBadge] Remove `textClassName` prop.
  CHANGELOG.md
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/index.js
Labels: Needs review :hand:, Breaking change :broken_heart:

#3212 [V11] Remove deprecated value prop
  CHANGELOG.md
  assets/javascripts/kitten/components/form/input/text-input-with-button/index.js
Labels: Needs review :hand:, Breaking change :broken_heart:

#3209 [V11] Remove deprecated cards
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/components/button.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/components/image.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/components/informations.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/components/progress.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/components/state.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/components/subtitle.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/components/title.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/index.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/stories.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/stories/project-state.js
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/styles.js
  assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/reward-card/components/index.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/info.js
  assets/javascripts/kitten/components/structure/cards/reward-card/index.js
  assets/javascripts/kitten/components/structure/cards/reward-card/styles.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:, Breaking change :broken_heart:

#3211 [V11] Remove deprecated Alert props
  CHANGELOG.md
  assets/javascripts/kitten/components/information/alert/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/alert/index.js
Labels: Needs review :hand:, Breaking change :broken_heart:

#3210 [V11] Button changes
  CHANGELOG.md
  assets/javascripts/kitten/components/action/button-group/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/button-question-mark-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/button-with-tooltip/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/button/helpers/modifier-styles.js
  assets/javascripts/kitten/components/action/button/index.js
  assets/javascripts/kitten/components/action/checkable-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/close-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/social-button-icon-words/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/social-button-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/color-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/modal-footer-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/index.js
  assets/javascripts/kitten/components/form/radio-button/index.js
  assets/javascripts/kitten/components/form/radio-set/index.js
  assets/javascripts/kitten/components/form/radio/index.js
  assets/javascripts/kitten/components/form/standalone-range-date-picker/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/toggletip/test.js
  assets/javascripts/kitten/components/interaction/discussion/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/drag-and-drop-list/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/upload/basic-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/upload/document-manager/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/upload/image-drop-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layer/modal/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/header-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/link-list/index.js
  assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/contribution-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/project-card/stories.js
  assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/reward-card/stories.js
  assets/javascripts/kitten/components/structure/cards/reward-card/test.js
  assets/javascripts/kitten/components/structure/cards/summary-card/stories.js
  assets/javascripts/kitten/components/structure/cards/team-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/triptych/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/vertical-card-with-action/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/expand/expand-board/__snapshots__/test.js.snap
  assets/javascripts/kitten/constants/typography-config.js
  assets/javascripts/kitten/karl/pages/news-list/index.js
  assets/javascripts/kitten/karl/pages/partner/components/text-with-icon-list.js
Labels: Needs review :hand:, Breaking change :broken_heart:

#3218 [V11] Put it back `RewardCard.Info`.
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/reward-card/components/index.js
  assets/javascripts/kitten/components/structure/cards/reward-card/index.js
Labels: Needs review :hand:, Breaking change :broken_heart:

#3219 [BackerCard] Modernize component
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/backer-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/backer-card/index.js
  assets/javascripts/kitten/components/structure/cards/backer-card/stories.js
Labels: Needs review :hand:, Kitten

#3223 [DropdownSelect] Change outline style on `combobox` input
  CHANGELOG.md
  assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select/styles.js
Labels: Needs review :hand:

#3224 v10.12.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/action/button/index.js
  src/components/form/select/dropdown-select/styles.js
  src/esm/components/action/button/index.js
  src/esm/components/form/select/dropdown-select/styles.js
Labels: Needs review :hand:

#3227 [RadioButton] Better font weight styles
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
Labels: Needs review :hand:

#3232 [ChatLayout] Fix main error
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/chat-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/chat-layout/index.js
Labels: Needs review :hand:

#3230 [MessagesMenu] Add close button
  CHANGELOG.md
  assets/javascripts/kitten/components/interaction/discussion/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/discussion/index.js
  assets/javascripts/kitten/components/navigation/messages-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/messages-menu/index.js
  assets/javascripts/kitten/components/navigation/messages-menu/stories.js
  assets/javascripts/kitten/components/navigation/messages-menu/test.js
Labels: Needs review :hand:

#3233 v11.2.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/interaction/discussion/index.js
  src/components/layout/chat-layout/index.js
  src/components/navigation/messages-menu/index.js
  src/esm/components/interaction/discussion/index.js
  src/esm/components/layout/chat-layout/index.js
  src/esm/components/navigation/messages-menu/index.js
Labels: Needs review :hand:

#3235 v11.2.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/interaction/discussion/index.js
  src/esm/components/interaction/discussion/index.js
Labels: Needs review :hand:

#3236 [MessagesMenu] Fix message height
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/chat-layout/stories.js
  assets/javascripts/kitten/components/navigation/messages-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/messages-menu/index.js
Labels: Needs review :hand:

#3240 [DashboardLayout] Fix side column width
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/styles.js
Labels: Needs review :hand:

#3239 [PeopleCard] Add `disabled` prop.
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/people-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/people-card/index.js
  assets/javascripts/kitten/components/structure/cards/people-card/stories.js
Labels: Needs review :hand:

#3243 v11.4.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/navigation/dashboard-menu/index.js
  src/esm/components/navigation/dashboard-menu/index.js
Labels: Needs review :hand:

#3245 [RewardCard] Fix background color
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/reward-card/styles.js
Labels: Needs review :hand:

#3244 [TextCopy] Fix resize bug on Webkit
  CHANGELOG.md
  assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/text-copy/index.js
Labels: Needs review :hand:

#3246 v11.4.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/action/text-copy/index.js
  src/components/structure/cards/reward-card/styles.js
  src/esm/components/action/text-copy/index.js
  src/esm/components/structure/cards/reward-card/styles.js
Labels: Needs review :hand:

#3247 [Video] Update player icon
  CHANGELOG.md
  assets/javascripts/kitten/components/embed/embed-player/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/embed/embed-player/index.js
  assets/javascripts/kitten/components/embed/video/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/embed/video/index.js
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
  assets/javascripts/kitten/components/graphics/icons-next/player-icon-next/index.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3248 [LoaderWithParagraph] Add loaderComponent prop
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/index.js
  assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/stories.js
  assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/test.js
Labels: Needs review :hand:

#3249 [DashboardLayout] Add position style to main
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/styles.js
Labels: Needs review :hand:

#3250 v11.5.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/embed/embed-player/index.js
  src/components/embed/video/index.js
  src/components/graphics/animations/loader-with-paragraph/index.js
  src/components/graphics/icons-next/player-icon-next/index.js
  src/components/layout/dashboard-layout/styles.js
  src/esm/components/embed/embed-player/index.js
  src/esm/components/embed/video/index.js
  src/esm/components/graphics/animations/loader-with-paragraph/index.js
  src/esm/components/graphics/icons-next/player-icon-next/index.js
  src/esm/components/layout/dashboard-layout/styles.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#3251 [DashboardLayout] Fix main section positionning
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/styles.js
Labels: Needs review :hand:

#3252 v11.5.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/layout/dashboard-layout/styles.js
  src/esm/components/layout/dashboard-layout/styles.js
Labels: Needs review :hand:

#3254 [EmbedPlayer] Disable embed code sanitization
  CHANGELOG.md
  assets/javascripts/kitten/components/embed/embed-player/index.js
Labels: Needs review :hand:

#3257 v11.5.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/embed/embed-player/index.js
  src/components/graphics/animations/loader-with-paragraph/index.js
  src/esm/components/embed/embed-player/index.js
  src/esm/components/graphics/animations/loader-with-paragraph/index.js
Labels: Needs review :hand:

#3261 [Docs] Remove tokens docs -> ZeroHeight
  .storybook/main.js
  .storybook/preview.js
  doc/tokens/border.stories.mdx
  doc/tokens/colors.stories.mdx
  doc/tokens/shadow.stories.mdx
  doc/tokens/spacing.stories.mdx
  doc/tokens/typography.stories.mdx
  package-lock.json
  package.json
Labels: Needs review :hand:
