Repository KissKissBankBank/kitten, pull requests merged in 2022-04, with the labels that each got.

#3114 [AlertBox] Add `pending` new status.
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
  assets/javascripts/kitten/components/graphics/icons-next/status-icon-next/index.js
  assets/javascripts/kitten/components/information/alert-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/alert-box/index.js
  assets/javascripts/kitten/components/information/alert-box/stories.js
  assets/javascripts/kitten/components/information/icon-badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/icon-badge/index.js
  assets/javascripts/kitten/components/information/icon-badge/stories.js
  assets/javascripts/kitten/components/interaction/stepper-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/stepper/__snapshots__/test.js.snap
Labels: Needs review :hand:

#3118 [OpenLockIconNext] New component.
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
  assets/javascripts/kitten/components/graphics/icons-next/open-lock-icon-next/index.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3120 [DashboredLayout] Flow improvements
  CHANGELOG.md
  assets/javascripts/kitten/components/action/text-copy/index.js
  assets/javascripts/kitten/components/graphics/illustrations/lightbulb-illustration.js
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories/with-flow.js
Labels: Needs review :hand:

#3104 [Form] Improve prop size values
  CHANGELOG.md
  assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/color-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/color-select/index.js
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/date-picker/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/stories.js
  assets/javascripts/kitten/components/form/input/password-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-button/index.js
  assets/javascripts/kitten/components/form/input/text-input-with-button/test.js
  assets/javascripts/kitten/components/form/input/text-input-with-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-unit/index.js
  assets/javascripts/kitten/components/form/input/text-input-with-unit/test.js
  assets/javascripts/kitten/components/form/input/text-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input/index.js
  assets/javascripts/kitten/components/form/input/text-input/stories.js
  assets/javascripts/kitten/components/form/input/text-input/test.js
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/index.js
  assets/javascripts/kitten/components/form/radio-button-set/stories.js
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
  assets/javascripts/kitten/components/form/radio-button/stories.js
  assets/javascripts/kitten/components/form/radio-button/test.js
  assets/javascripts/kitten/components/form/radio-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio/index.js
  assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select/combobox.js
  assets/javascripts/kitten/components/form/select/dropdown-select/index.js
  assets/javascripts/kitten/components/form/select/dropdown-select/stories.js
  assets/javascripts/kitten/components/form/select/dropdown-select/styles.js
  assets/javascripts/kitten/components/structure/cards/contribution-card/__snapshots__/test.js.snap
Labels: Needs review :hand:

#3106 [Graphics] Improve prop size values
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/illustrations/kkbb-flash-illustration.js
  assets/javascripts/kitten/components/graphics/illustrations/lightbulb-illustration.js
  assets/javascripts/kitten/components/graphics/logos/kisskissbankbanklogo/index.js
  assets/javascripts/kitten/components/graphics/logos/lendopolis-logo/index.js
  assets/javascripts/kitten/components/graphics/logos/logos.stories.js
  assets/javascripts/kitten/components/navigation/header-nav/stories/minimalist.js
Labels: Needs review :hand:

#3110 [Information] Improve size prop values
  CHANGELOG.md
  assets/javascripts/kitten/components/information/alert-box/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/alert-box/index.js
  assets/javascripts/kitten/components/information/alert-box/stories.js
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/index.js
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/stories.js
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/test.js
  assets/javascripts/kitten/components/information/icon-badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/icon-badge/index.js
  assets/javascripts/kitten/components/information/icon-badge/stories.js
  assets/javascripts/kitten/components/information/icon-badge/test.js
  assets/javascripts/kitten/components/information/status-with-bullet/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/status-with-bullet/index.js
  assets/javascripts/kitten/components/information/status-with-bullet/stories.js
  assets/javascripts/kitten/components/information/tag/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/tag/index.js
  assets/javascripts/kitten/components/information/tag/stories.js
  assets/javascripts/kitten/components/information/tag/test.js
  assets/javascripts/kitten/components/interaction/stepper-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/stepper-icon/index.js
  assets/javascripts/kitten/components/interaction/stepper/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/upload/documents-drop-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/backing-card/__snapshots__/test.js.snap
Labels: Needs review :hand:

#3111 [Structure] Improve prop size values
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/backing-card/stories.js
  assets/javascripts/kitten/components/structure/carousels/carousel/index.js
  assets/javascripts/kitten/components/structure/carousels/carousel/stories.js
  assets/javascripts/kitten/components/structure/carousels/carousel/test.js
  assets/javascripts/kitten/components/structure/expand/expand-board/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/expand/expand-board/index.js
  assets/javascripts/kitten/components/structure/hero/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/hero/index.js
  assets/javascripts/kitten/components/structure/hero/stories.js
  assets/javascripts/kitten/karl/pages/homepage/engagements-carousel/index.js
  assets/javascripts/kitten/karl/pages/homepage/featured-projects/index.js
  assets/javascripts/kitten/karl/pages/homepage/partners/index.js
  assets/javascripts/kitten/karl/pages/homepage/popular-projects/index.js
Labels: Needs review :hand:

#3116 [Label] Remplace `small` prop size default value.
  CHANGELOG.md
  assets/javascripts/kitten/components/form/checkbox-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/label/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/label/index.js
  assets/javascripts/kitten/components/form/label/stories.js
  assets/javascripts/kitten/components/form/label/test.js
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/test.js.snap
Labels: Needs review :hand:, Breaking change :broken_heart:

#3119 [BulletList] Breaking change: Remplace old prop size values
  CHANGELOG.md
  assets/javascripts/kitten/components/interaction/upload/document-manager/stories.js
  assets/javascripts/kitten/components/structure/bullet-list/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/bullet-list/index.js
  assets/javascripts/kitten/components/structure/bullet-list/stories.js
  assets/javascripts/kitten/components/structure/bullet-list/test.js
Labels: Needs review :hand:, Breaking change :broken_heart:

#3123 [RewardCard] Migrate from `BackingCard`
  CHANGELOG.md
  assets/javascripts/kitten/components/interaction/upload/image-drop-uploader/stories.js
  assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/reward-card/components/amount.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/button.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/contents.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/description.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/form.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/heading-tag.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/image.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/index.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/info.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/tag-list.js
  assets/javascripts/kitten/components/structure/cards/reward-card/components/title.js
  assets/javascripts/kitten/components/structure/cards/reward-card/index.js
  assets/javascripts/kitten/components/structure/cards/reward-card/stories.js
  assets/javascripts/kitten/components/structure/cards/reward-card/styles.js
  assets/javascripts/kitten/components/structure/cards/reward-card/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3122 [HorizontalProjectCard] Migrate from `HorizontalCrowdfundingCard`
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/flex-wrapper/stories.js
  assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank.js
  assets/javascripts/kitten/components/structure/cards/horizontal-crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/horizontal-project-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/horizontal-project-card/index.js
  assets/javascripts/kitten/components/structure/cards/horizontal-project-card/stories.js
  assets/javascripts/kitten/components/structure/cards/horizontal-project-card/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3124 [ScrollableContainer] Remove scrollableContainerStyle
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/scrollable-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/scrollable-container/index.js
  assets/javascripts/kitten/components/layout/scrollable-container/styled.js
  assets/javascripts/kitten/components/structure/cards/project-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/project-card/test.js
Labels: Needs review :hand:

#3127 [CrowdfundingCard] Fix tests
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/crowdfunding-card/test.js
  assets/javascripts/kitten/components/structure/carousels/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/carousels/carousel/test.js
Labels: Needs review :hand:

#3125 [Size] Improve prop size values
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/stories.js
  assets/javascripts/kitten/components/form/field/test.js
  assets/javascripts/kitten/components/form/input/tag-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/tag-input/index.js
  assets/javascripts/kitten/components/form/input/tag-input/stories.js
  assets/javascripts/kitten/components/form/input/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-limit/test.js
  assets/javascripts/kitten/components/form/label/index.js
  assets/javascripts/kitten/components/form/radio-button/stories.js
  assets/javascripts/kitten/components/form/select/dropdown-phone-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-phone-select/stories.js
  assets/javascripts/kitten/components/form/select/dropdown-select-with-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select-with-input/index.js
  assets/javascripts/kitten/components/form/select/dropdown-select-with-input/stories.js
  assets/javascripts/kitten/components/graphics/icons/cross-icon/index.js
  assets/javascripts/kitten/components/interaction/upload/basic-uploader/stories.js
  assets/javascripts/kitten/components/interaction/upload/document-manager/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/upload/document-manager/test.js
  assets/javascripts/kitten/components/layout/dashboard-layout/stories/layout.js
  assets/javascripts/kitten/components/layout/hero-layout/stories.js
  assets/javascripts/kitten/components/navigation/header-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/header-menu/components/item.js
  assets/javascripts/kitten/components/navigation/header-menu/styles.js
  assets/javascripts/kitten/components/navigation/header-nav/components/search-input.js
  assets/javascripts/kitten/components/navigation/nav-bar/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/nav-bar/index.js
  assets/javascripts/kitten/components/navigation/nav-bar/stories.js
  assets/javascripts/kitten/components/navigation/nav-bar/test.js
  assets/javascripts/kitten/components/structure/bullet-list/stories.js
  assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/reward-card/components/title.js
  assets/javascripts/kitten/components/structure/expand/expand-board/stories.js
  assets/javascripts/kitten/components/structure/info-lines/stories.js
  assets/javascripts/kitten/karl/pages/footer/components/legal.js
  assets/javascripts/kitten/karl/pages/modal-edit-project/index.js
  assets/javascripts/kitten/karl/pages/partner/components/text-with-image.js
  assets/javascripts/kitten/karl/pages/partner/components/text-with-images.js
  assets/javascripts/kitten/karl/pages/partner/components/text-with-video.js
  assets/javascripts/kitten/karl/pages/partner/components/title.js
Labels: Needs review :hand:

#3129 [KittenV10] Lint + clean tests
  assets/javascripts/kitten/components/action/button-image/index.js
  assets/javascripts/kitten/components/action/checkable-button/index.js
  assets/javascripts/kitten/components/action/tag-button/index.js
  assets/javascripts/kitten/components/action/text-button/index.js
  assets/javascripts/kitten/components/form/input/textarea-auto-resize/index.js
  assets/javascripts/kitten/components/form/radio-button-set/index.js
  assets/javascripts/kitten/components/form/radio-button/index.js
  assets/javascripts/kitten/components/form/select/dropdown-select/index.js
  assets/javascripts/kitten/components/graphics/icons-next/open-lock-icon-next/index.js
  assets/javascripts/kitten/components/graphics/illustrations/kkbb-flash-illustration.js
  assets/javascripts/kitten/components/graphics/illustrations/lightbulb-illustration.js
  assets/javascripts/kitten/components/graphics/logos/kisskissbankbanklogo/index.js
  assets/javascripts/kitten/components/graphics/logos/lendopolis-logo/index.js
  assets/javascripts/kitten/components/information/alert-box/index.js
  assets/javascripts/kitten/components/information/alert-box/stories.js
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/index.js
  assets/javascripts/kitten/components/information/icon-badge/index.js
  assets/javascripts/kitten/components/information/icon-badge/stories.js
  assets/javascripts/kitten/components/information/status-with-bullet/index.js
  assets/javascripts/kitten/components/information/tag/index.js
  assets/javascripts/kitten/components/layer/modal-next/index.js
  assets/javascripts/kitten/components/navigation/header-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/header-menu/components/item.js
  assets/javascripts/kitten/components/navigation/header-menu/styles.js
  assets/javascripts/kitten/components/navigation/nav-bar/index.js
  assets/javascripts/kitten/components/structure/cards/horizontal-project-card/stories.js
  assets/javascripts/kitten/components/structure/cards/reward-card/styles.js
  assets/javascripts/kitten/components/structure/cards/reward-card/test.js
  assets/javascripts/kitten/components/structure/cards/summary-card/test.js
  assets/javascripts/kitten/components/structure/cards/team-card/components/icons.js
  assets/javascripts/kitten/components/structure/carousels/carousel/test.js
  assets/javascripts/kitten/components/structure/expand/expand-board/index.js
  assets/javascripts/kitten/components/typography/text/index.js
  assets/javascripts/kitten/components/typography/vertical-stroke/index.js
  assets/javascripts/kitten/helpers/utils/deprecated.js
  assets/javascripts/kitten/helpers/utils/margin/index.js
  assets/javascripts/kitten/index.js
  assets/javascripts/kitten/karl/pages/common/projects-carousel.js
  assets/javascripts/kitten/karl/pages/news-list/index.js
Labels: Needs review :hand:

#3132 [Text] Use full utility class name to avoid purge
  CHANGELOG.md
  assets/javascripts/kitten/components/typography/text/index.js
Labels: Needs review :hand:

#3133 v10.0.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/typography/text/index.js
  src/esm/components/typography/text/index.js
Labels: Needs review :hand:

#3134 [RadioButton] Improve style.
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/radio-button/index.js
Labels: Needs review :hand:

#3136 [OpenLockIconNext] Improve styles.
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/open-lock-icon-next/index.js
Labels: Needs review :hand:

#3137 [TextCopy] Improve tooltip styles
  CHANGELOG.md
  assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/text-copy/index.js
Labels: Needs review :hand:

#3117 [ChatLayout] Add component 🐱
  CHANGELOG.md
  assets/javascripts/kitten/components/form/input/text-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input/index.js
  assets/javascripts/kitten/components/interaction/discussion/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/interaction/discussion/index.js
  assets/javascripts/kitten/components/interaction/discussion/stories.js
  assets/javascripts/kitten/components/interaction/discussion/test.js
  assets/javascripts/kitten/components/layout/chat-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/chat-layout/index.js
  assets/javascripts/kitten/components/layout/chat-layout/stories.js
  assets/javascripts/kitten/components/layout/chat-layout/styles.js
  assets/javascripts/kitten/components/layout/chat-layout/test.js
  assets/javascripts/kitten/components/navigation/messages-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/messages-menu/index.js
  assets/javascripts/kitten/components/navigation/messages-menu/stories.js
  assets/javascripts/kitten/components/navigation/messages-menu/test.js
  assets/javascripts/kitten/index.js
  assets/stylesheets/kitten/utilities/reset/_button.scss
Labels: Needs review :hand:

#3139 [EditorialCard] Add component
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
  assets/javascripts/kitten/components/graphics/icons-next/long-arrow-icon-next/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/graphics/icons-next/long-arrow-icon-next/index.js
  assets/javascripts/kitten/components/graphics/icons-next/long-arrow-icon-next/stories.js
  assets/javascripts/kitten/components/graphics/icons-next/long-arrow-icon-next/test.js
  assets/javascripts/kitten/components/structure/cards/editorial-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/editorial-card/index.js
  assets/javascripts/kitten/components/structure/cards/editorial-card/stories.js
  assets/javascripts/kitten/components/structure/cards/editorial-card/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3138 [ArrowContainer] Allow CSS Custom Properties as prop values
  CHANGELOG.md
  assets/javascripts/kitten/components/action/button-with-tooltip/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/text-copy/index.js
  assets/javascripts/kitten/components/information/boxes/arrow-container/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/boxes/arrow-container/index.js
  assets/javascripts/kitten/components/information/boxes/arrow-container/stories.js
  assets/javascripts/kitten/components/information/boxes/arrow-container/test.js
  assets/javascripts/kitten/components/structure/expand/dropdown-menu/__snapshots__/test.js.snap
Labels: Needs review :hand:

#3143 [PeopleCard] Add new component
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
  assets/javascripts/kitten/components/graphics/icons-next/people-circle-icon-next/index.js
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/index.js
  assets/javascripts/kitten/components/information/avatar-with-text-and-badge/stories.js
  assets/javascripts/kitten/components/structure/cards/people-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/people-card/index.js
  assets/javascripts/kitten/components/structure/cards/people-card/stories.js
  assets/javascripts/kitten/components/structure/cards/people-card/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3144 [SummaryCard] Replace `xlarge` by `huge` prop size value
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/summary-card/components/title-bar.js
  assets/javascripts/kitten/components/structure/cards/summary-card/hooks/use-resize-observer.js
  assets/javascripts/kitten/components/structure/cards/summary-card/index.js
Labels: Needs review :hand:

#3145 [Autocomplete] Improve style
  CHANGELOG.md
  assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/autocomplete/index.js
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
Labels: Needs review :hand:

#3148 [Release] Add built js files for 10.2.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/autocomplete/index.js
  src/components/graphics/icons-next/people-circle-icon-next/index.js
  src/components/information/avatar-with-text-and-badge/index.js
  src/components/interaction/upload/image-drop-uploader/index.js
  src/components/structure/cards/people-card/index.js
  src/components/structure/cards/summary-card/components/title-bar.js
  src/components/structure/cards/summary-card/hooks/use-resize-observer.js
  src/components/structure/cards/summary-card/index.js
  src/esm/components/form/autocomplete/index.js
  src/esm/components/graphics/icons-next/people-circle-icon-next/index.js
  src/esm/components/information/avatar-with-text-and-badge/index.js
  src/esm/components/interaction/upload/image-drop-uploader/index.js
  src/esm/components/structure/cards/people-card/index.js
  src/esm/components/structure/cards/summary-card/components/title-bar.js
  src/esm/components/structure/cards/summary-card/hooks/use-resize-observer.js
  src/esm/components/structure/cards/summary-card/index.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#3147 [ProfileCard] New component
  CHANGELOG.md
  assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/autocomplete/index.js
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/profile-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/profile-card/index.js
  assets/javascripts/kitten/components/structure/cards/profile-card/stories.js
  assets/javascripts/kitten/components/structure/cards/profile-card/test.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3149 [DropdownSelect] Change list style to cut last item if scrollable
  CHANGELOG.md
  assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/combobox.test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/select/dropdown-select/index.js
  assets/javascripts/kitten/components/form/select/dropdown-select/stories.js
  assets/javascripts/kitten/components/form/select/dropdown-select/styles.js
  assets/javascripts/kitten/components/form/select/dropdown-select/test.js
Labels: Needs review :hand:

#3150 [LightbulbIllustration] Revert color change
  assets/javascripts/kitten/components/graphics/illustrations/lightbulb-illustration.js
  assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
Labels: Needs review :hand:

#3152 [CheckboxButton] Add component
  CHANGELOG.md
  assets/javascripts/kitten/components/form/checkbox-button-set/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/checkbox-button-set/index.js
  assets/javascripts/kitten/components/form/checkbox-button-set/stories.js
  assets/javascripts/kitten/components/form/checkbox-button-set/test.js
  assets/javascripts/kitten/components/form/checkbox-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/checkbox-button/index.js
  assets/javascripts/kitten/components/form/checkbox-button/stories.js
  assets/javascripts/kitten/components/form/checkbox-button/test.js
Labels: Needs review :hand:

#3151 [ContentCard] Improve styles.
  assets/javascripts/kitten/components/structure/cards/content-card/stories.js
Labels: Needs review :hand:

#3156 [ImageDropUploader] Fix async function
  CHANGELOG.md
  assets/javascripts/kitten/components/interaction/upload/image-drop-uploader/index.js
Labels: Bug :bug:, Needs review :hand:

#3157 v10.3.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/autocomplete/index.js
  src/components/form/checkbox-button-set/index.js
  src/components/form/checkbox-button/index.js
  src/components/form/select/dropdown-select/index.js
  src/components/form/select/dropdown-select/styles.js
  src/components/graphics/illustrations/lightbulb-illustration.js
  src/components/interaction/upload/image-drop-uploader/index.js
  src/components/structure/cards/profile-card/index.js
  src/esm/components/form/autocomplete/index.js
  src/esm/components/form/checkbox-button-set/index.js
  src/esm/components/form/checkbox-button/index.js
  src/esm/components/form/select/dropdown-select/index.js
  src/esm/components/form/select/dropdown-select/styles.js
  src/esm/components/graphics/illustrations/lightbulb-illustration.js
  src/esm/components/interaction/upload/image-drop-uploader/index.js
  src/esm/components/structure/cards/profile-card/index.js
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#3158 Add CheckboxButton and CheckButtonSet export
  CHANGELOG.md
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3154 [HeroLayout] Add Simple mode
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/hero-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/hero-layout/index.js
  assets/javascripts/kitten/components/layout/hero-layout/stories.js
  assets/javascripts/kitten/components/layout/hero-layout/styles.js
  assets/javascripts/kitten/components/navigation/floating-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/navigation/floating-menu/index.js
  assets/javascripts/kitten/components/structure/cards/profile-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/profile-card/index.js
  assets/javascripts/kitten/components/structure/cards/profile-card/stories.js
  assets/javascripts/kitten/components/structure/cards/profile-card/test.js
  assets/stylesheets/kitten/_tokens.scss
  assets/stylesheets/kitten/_utilities.scss
  assets/stylesheets/kitten/tokens/_shadows.scss
  assets/stylesheets/kitten/utilities/shadow/_shadow.scss
  assets/stylesheets/utilities.scss
Labels: Needs review :hand:

#3142 [Modal] New componant
  CHANGELOG.md
  assets/javascripts/kitten/components/layer/modal/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layer/modal/index.js
  assets/javascripts/kitten/components/layer/modal/stories.js
  assets/javascripts/kitten/components/layer/modal/styles.js
  assets/javascripts/kitten/components/layer/modal/test.js
Labels: Work in progress :construction:

#3153 [Tag] Improve styles
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/flash-icon-next/index.js
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
  assets/javascripts/kitten/components/information/tag/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/information/tag/index.js
  assets/javascripts/kitten/components/information/tag/stories.js
  assets/javascripts/kitten/components/interaction/upload/documents-drop-uploader/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3159 v10.4.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/graphics/icons-next/flash-icon-next/index.js
  src/components/information/tag/index.js
  src/components/layer/modal/index.js
  src/components/layer/modal/styles.js
  src/components/layout/hero-layout/index.js
  src/components/layout/hero-layout/styles.js
  src/components/navigation/floating-menu/index.js
  src/components/structure/cards/profile-card/index.js
  src/esm/components/graphics/icons-next/flash-icon-next/index.js
  src/esm/components/information/tag/index.js
  src/esm/components/layer/modal/index.js
  src/esm/components/layer/modal/styles.js
  src/esm/components/layout/hero-layout/index.js
  src/esm/components/layout/hero-layout/styles.js
  src/esm/components/navigation/floating-menu/index.js
  src/esm/components/structure/cards/profile-card/index.js
  src/esm/index.js
  src/index.js
  src/stylesheets/tokens.css
  src/stylesheets/utilities.css
Labels: Needs review :hand:

#3160 [HeroLayout] Fix Hero z-index
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/hero-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/hero-layout/stories.js
  assets/javascripts/kitten/components/layout/hero-layout/styles.js
Labels: Needs review :hand:

#3162 [HeroLayout] Fix background position in Simple mode
  CHANGELOG.md
  assets/javascripts/kitten/components/layout/hero-layout/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/layout/hero-layout/styles.js
Labels: Needs review :hand:

#3163 v10.4.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/layout/hero-layout/styles.js
  src/esm/components/layout/hero-layout/styles.js
Labels: Needs review :hand:
