Repository KissKissBankBank/kitten, pull requests merged in 2022-07, with the labels that each got.

#3263 v11.6.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/action/button/helpers/modifier-styles.js
  src/components/form/input/autocomplete/index.js
  src/esm/components/action/button/helpers/modifier-styles.js
  src/esm/components/form/input/autocomplete/index.js
Labels: Needs review :hand:

#3264 [Autocomplete] Update updateSuggestionsStrategy function
  assets/javascripts/kitten/components/form/input/autocomplete/index.js
Labels: Needs review :hand:

#3268 [Icons] Add GarbageIconNext
  CHANGELOG.md
  assets/javascripts/kitten/components/graphics/icons-next/garbage-icon-next/index.js
  assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
  assets/javascripts/kitten/index.js
Labels: Needs review :hand:

#3267 [DropdownMenu] Add textProps class
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/expand/dropdown-menu/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/expand/dropdown-menu/index.js
  assets/javascripts/kitten/components/structure/expand/dropdown-menu/stories.js
  assets/javascripts/kitten/components/structure/expand/dropdown-menu/test.js
Labels: Needs review :hand:

#3258 [Token] Add `font-weight` variables
  CHANGELOG.md
  assets/stylesheets/kitten/_tokens.scss
  assets/stylesheets/kitten/tokens/_font-weight.scss
  data/output.json
  data/tokens.json
  sd.config.js
  src/stylesheets/tokens.css
Labels: Needs review :hand:

#3269 v11.7.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/graphics/icons-next/garbage-icon-next/index.js
  src/components/structure/expand/dropdown-menu/index.js
  src/esm/components/graphics/icons-next/garbage-icon-next/index.js
  src/esm/components/structure/expand/dropdown-menu/index.js
  src/esm/index.js
  src/index.js
Labels: Kitten

#3259 [Token] Add `typography` css tokens
  .github/workflows/create-tokens.yml
  CHANGELOG.md
  assets/stylesheets/kitten/_tokens.scss
  assets/stylesheets/kitten/tokens/_border-radius.scss
  assets/stylesheets/kitten/tokens/_borders.scss
  assets/stylesheets/kitten/tokens/_box-shadow.scss
  assets/stylesheets/kitten/tokens/_colors.scss
  assets/stylesheets/kitten/tokens/_font-size.scss
  assets/stylesheets/kitten/tokens/_font-weight.scss
  assets/stylesheets/kitten/tokens/_outlines.scss
  assets/stylesheets/kitten/tokens/_spacing.scss
  assets/stylesheets/kitten/tokens/_typography.scss
  data/output.json
  data/tokens.json
  sd.config.js
  src/stylesheets/tokens.css
Labels: Work in progress :construction:

#3274 [Utilities] Automagically generate utility classes from tokens
  .github/workflows/create-tokens.yml
  CHANGELOG.md
  assets/stylesheets/kitten/_utilities.scss
  assets/stylesheets/kitten/tokens/_border-radius.scss
  assets/stylesheets/kitten/tokens/_box-shadow.scss
  assets/stylesheets/kitten/tokens/_colors.scss
  assets/stylesheets/kitten/tokens/_spacing.scss
  assets/stylesheets/kitten/tokens/_typography.scss
  assets/stylesheets/kitten/utilities/_token.scss
  assets/stylesheets/kitten/utilities/shadow/_box-shadow.scss
  assets/stylesheets/kitten/utilities/text/_color.scss
  assets/stylesheets/kitten/utilities/text/_line-height.scss
  assets/stylesheets/utilities.scss
  data/tokens.json
  doc/utilities/text/font.stories.mdx
  sd.config.js
  src/stylesheets/tokens.css
  src/stylesheets/utilities.css
Labels: Needs review :hand:

#3280 [Button] Set valid default size
  CHANGELOG.md
  assets/javascripts/kitten/components/action/button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/action/button/index.js
  assets/javascripts/kitten/components/action/button/test.js
  assets/javascripts/kitten/components/structure/carousels/carousel/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/carousels/carousel/index.js
  assets/javascripts/kitten/components/structure/carousels/carousel/test.js
Labels: Needs review :hand:

#3279 [RichText] Add component
  CHANGELOG.md
  assets/javascripts/kitten/components/typography/rich-text/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/rich-text/index.js
  assets/javascripts/kitten/components/typography/rich-text/stories.js
  assets/javascripts/kitten/components/typography/rich-text/test.js
Labels: Needs product review :watermelon:

#3283 [v12] Fixes
  CHANGELOG.md
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/autocomplete/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/autocomplete/index.js
  assets/javascripts/kitten/components/form/input/tag-input-autocomplete/index.js
  assets/javascripts/kitten/components/form/standalone-range-date-picker/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/standalone-range-date-picker/index.js
  assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/__snapshots__/test.js.snap
Labels: Work in progress :construction:, Needs review :hand:

#3284 v12.0.0 beta2
  CHANGELOG.md
  assets/javascripts/kitten/components/form/input/autocomplete/index.js
  package-lock.json
  package.json
  src/components/form/input/autocomplete/index.js
  src/components/form/input/tag-input-autocomplete/index.js
  src/components/form/standalone-range-date-picker/index.js
  src/esm/components/form/input/autocomplete/index.js
  src/esm/components/form/input/tag-input-autocomplete/index.js
  src/esm/components/form/standalone-range-date-picker/index.js
Labels: Needs review :hand:

#3285 v12.0.0
  CHANGELOG.md
  assets/javascripts/kitten/index.js
  package-lock.json
  package.json
  src/esm/index.js
  src/index.js
Labels: Needs review :hand:

#3287 [RewardCard] Fix Info import
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/reward-card/index.js
Labels: Needs review :hand:

#3288 v12.0.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/structure/cards/reward-card/index.js
  src/esm/components/structure/cards/reward-card/index.js
Labels: Needs review :hand:

#3289 [Front] Refix RewarCard info
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/reward-card/components/index.js
  assets/javascripts/kitten/components/structure/cards/reward-card/test.js
Labels: Needs review :hand:

#3290 v12.1.0
  CHANGELOG.md
  assets/javascripts/kitten/components/structure/cards/reward-card/components/info.js
  package-lock.json
  package.json
  src/components/structure/cards/reward-card/components/index.js
  src/components/structure/cards/reward-card/components/info.js
  src/esm/components/structure/cards/reward-card/components/index.js
  src/esm/components/structure/cards/reward-card/components/info.js
Labels: Needs review :hand:, Facepalm 🤦

#3292 Fix text input defautvalue/value
  CHANGELOG.md
  assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/color-select/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/autocomplete/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/location-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/password-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-button/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-icon/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-limit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input-with-unit/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/form/input/text-input/index.js
  assets/javascripts/kitten/components/form/input/text-input/test.js
  assets/javascripts/kitten/components/interaction/discussion/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/structure/cards/contribution-card/__snapshots__/test.js.snap
Labels: Bug :bug:, Needs review :hand:

#3291 [Utilities] Add gap values
  CHANGELOG.md
  assets/stylesheets/kitten/utilities/flex/_gap.scss
  src/stylesheets/utilities.css
Labels: Needs review :hand:

#3293 v12.2.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/input/text-input/index.js
  src/esm/components/form/input/text-input/index.js
Labels: Needs review :hand:, Kitten

#3294 [CHANGELOG] Update emoji
  CHANGELOG.md
Labels: Needs review :hand:

#3295 [TitleWithStroke] Add `noMargin` prop
  CHANGELOG.md
  assets/javascripts/kitten/components/typography/title-with-stroke/__snapshots__/test.js.snap
  assets/javascripts/kitten/components/typography/title-with-stroke/index.js
  assets/javascripts/kitten/components/typography/title-with-stroke/stories.js
  assets/javascripts/kitten/components/typography/title-with-stroke/test.js
Labels: Needs review :hand:
